        proxy_set_header X-DEVOPS-UID $uid;
		proxy_set_header X-BKREPO-UID $uid;
		proxy_set_header X-DEVOPS-SID $uid;
		proxy_set_header X-DEVOPS-SNAME $uid;
		proxy_set_header X-DEVOPS-BK-TOKEN $bk_token;
		proxy_set_header X-DEVOPS-BK-TICKET $bk_token;
		proxy_set_header X-DEVOPS-ACCESS-TOKEN $accessToken;
		proxy_set_header X-BK-TENANT-ID $tenant_id;
		proxy_set_header X-BK-USER-TIMEZONE $user_timezone;

		include proxy.set.header.common.conf;
