# apigw层服务分发
location ~ /bkcode/api/(.*) {
    header_filter_by_lua_file 'conf/lua/cors_filter_apigw.lua';
    set $service "bkcode";
    set $path $1;
    # 设置proxy header的变量
    include proxy.set.header.common.conf;
    proxy_set_header X-DEVOPS-SERVICE-NAME $service;
    # 反向代理到目标ip，端口，路径和参数
    proxy_pass http://bkcode.woa.com/api/$path?$args;
}
