	# agent日志记录
	location = /ms/environment/api/buildAgent/agent/thirdPartyAgent/agents/metrix/write {
		return 200;
	}
	# agent日志记录
	location = /ms/environment/api/buildAgent/agent/thirdPartyAgent/agents/metrix {
		return 200;
	}
	# agent日志记录
	location = /environment/api/buildAgent/agent/thirdPartyAgent/agents/metrix/write {
		return 200;
	}
	# agent日志记录
	location = /environment/api/buildAgent/agent/thirdPartyAgent/agents/metrix {
		return 200;
	}
