# apigw层服务分发
location ~ /scc/(ms/|)([\w-_]+)/api/(apigw|apigw-user|apigw-app)/(.*) {
    header_filter_by_lua_file 'conf/lua/cors_filter_apigw.lua';
    set $access_type $3;
    set $service "scc";
    set $path $4;
    set $target '';
    access_by_lua_file 'conf/lua/router_srv.lua';
    # 设置proxy header的变量
    include proxy.set.header.common.conf;
    proxy_set_header X-DEVOPS-SERVICE-NAME $service;
    # 反向代理到目标ip，端口，路径和参数
    proxy_pass http://$target/ms/$2/api/$access_type/$path?$args;
}