object Versions {
    const val HashIds = "1.0.3"
    const val Jaxrs = "2.0"
    const val CommonExec = "1.3"
    const val Vmware = "5.1"
    const val BouncyCastle = "1.46"
    const val Dom4j = "1.6.1"
    const val JsonSchema = "2.2.6"
    const val Jasypt = "2.0.0"
    const val Lucene = "8.6.0"
    const val Swagger = "1.6.2"
    const val Mockito = "1.10.19"
    const val JsonLib = "2.4"
    const val CronUtils = "7.0.1"
    const val Sigar = "1.7.0.0"
    const val Thumbnailator = "0.4.8"
    const val EmojiJava = "5.1.1"
    const val CommonCsv = "1.8"
    const val CommonCollections4 = "4.4"
    const val MockitoKt = "1.6.0"
    const val DockerJava = "3.2.5"
    const val DdPlist = "1.23"
    const val ApkParser = "2.5.3"
    const val OshiCore = "3.4.0"
    const val TencentBkRepo = "1.0.0"
}
