FROM scratch

COPY --chown=33333:33333 devopsRemoting-ide-desktop-config.json /ide-desktop/devopsRemoting-ide-desktop-config.json
COPY --chown=33333:33333 status/bin/vscode-desktop-status /ide-desktop/
