use devops_ci_environment;
SET NAMES utf8mb4;

-- 初始化标签
INSERT IGNORE INTO `T_NODE_TAG_INTERNAL_KEY` (`ID`,`KEY_NAME` ) VALUES (-1, 'os');
INSERT IGNORE INTO `T_NODE_TAG_INTERNAL_KEY` (`ID`,`KEY_NAME` ) VALUES (-2, 'arch');
INSERT IGNORE INTO `T_NODE_TAG_INTERNAL_VALUES` (`ID`,`TAG_KEY_ID`,`VALUE_NAME` ) VALUES (-1, -1, 'linux');
INSERT IGNORE INTO `T_NODE_TAG_INTERNAL_VALUES` (`ID`,`TAG_KEY_ID`,`VALUE_NAME` ) VALUES (-2, -1, 'windows');
INSERT IGNORE INTO `T_NODE_TAG_INTERNAL_VALUES` (`ID`,`TAG_KEY_ID`,`VALUE_NAME` ) VALUES (-3, -1, 'macos');
INSERT IGNORE INTO `T_NODE_TAG_INTERNAL_VALUES` (`ID`,`TAG_KEY_ID`,`VALUE_NAME` ) VALUES (-4, -2, 'amd64');
INSERT IGNORE INTO `T_NODE_TAG_INTERNAL_VALUES` (`ID`,`TAG_KEY_ID`,`VALUE_NAME` ) VALUES (-5, -2, 'arm64');
INSERT IGNORE INTO `T_NODE_TAG_INTERNAL_VALUES` (`ID`,`TAG_KEY_ID`,`VALUE_NAME` ) VALUES (-6, -2, 'loong64');