import 'package:flutter/material.dart';

class BkIcons {
  static const IconData more = IconData(0xe101, fontFamily: 'BkIcon');
  static const IconData search = IconData(0xe102, fontFamily: 'BkIcon');
  static const IconData download = IconData(0xe103, fontFamily: 'BkIcon');
  static const IconData home = IconData(0xe105, fontFamily: 'BkIcon');
  static const IconData info = IconData(0xe106, fontFamily: 'BkIcon');
  static const IconData homeFill = IconData(0xe104, fontFamily: 'BkIcon');
  static const IconData userFill = IconData(0xe107, fontFamily: 'BkIcon');
  static const IconData user = IconData(0xe109, fontFamily: 'BkIcon');
  static const IconData experienceFill = IconData(0xe10a, fontFamily: 'BkIcon');
  static const IconData experience = IconData(0xe10b, fontFamily: 'BkIcon');
  static const IconData conversion = IconData(0xe108, fontFamily: 'BkIcon');
  static const IconData scan = IconData(0xe10c, fontFamily: 'BkIcon');
  static const IconData share = IconData(0xe10d, fontFamily: 'BkIcon');
  static const IconData link = IconData(0xe10e, fontFamily: 'BkIcon');
  static const IconData pipeline = IconData(0xe10f, fontFamily: 'BkIcon');
  static const IconData returnIcon = IconData(0xe110, fontFamily: 'BkIcon');
  static const IconData delete = IconData(0xe111, fontFamily: 'BkIcon');
  static const IconData up = IconData(0xe112, fontFamily: 'BkIcon');
  static const IconData down = IconData(0xe113, fontFamily: 'BkIcon');
  static const IconData right = IconData(0xe114, fontFamily: 'BkIcon');
  static const IconData left = IconData(0xe115, fontFamily: 'BkIcon');
  static const IconData wrongFill = IconData(0xe116, fontFamily: 'BkIcon');
  static const IconData qr = IconData(0xe117, fontFamily: 'BkIcon');
  static const IconData collectFill = IconData(0xe118, fontFamily: 'BkIcon');
  static const IconData unfavoriteFill = IconData(0xe119, fontFamily: 'BkIcon');
  static const IconData remindFill = IconData(0xe11a, fontFamily: 'BkIcon');
  static const IconData version = IconData(0xe11b, fontFamily: 'BkIcon');
  static const IconData time = IconData(0xe11c, fontFamily: 'BkIcon');
  static const IconData correctFill = IconData(0xe11d, fontFamily: 'BkIcon');
  static const IconData upFill = IconData(0xe11e, fontFamily: 'BkIcon');
  static const IconData downFill = IconData(0xe11f, fontFamily: 'BkIcon');
  static const IconData checkSmall = IconData(0xe124, fontFamily: 'BkIcon');
  static const IconData filter = IconData(0xe125, fontFamily: 'BkIcon');
  static const IconData close = IconData(0xe126, fontFamily: 'BkIcon');
  static const IconData check = IconData(0xe127, fontFamily: 'BkIcon');
  static const IconData jinzhi = IconData(0xe128, fontFamily: 'BkIcon');
  static const IconData flag = IconData(0xe129, fontFamily: 'BkIcon');
  static const IconData eye = IconData(0xe12a, fontFamily: 'BkIcon');
  static const IconData circle = IconData(0xe12f, fontFamily: 'BkIcon');
  static const IconData placeholder = IconData(0xe130, fontFamily: 'BkIcon');
  static const IconData closeFill = IconData(0xe132, fontFamily: 'BkIcon');
}
