USE devops_dispatch_macos;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;


CREATE TABLE IF NOT EXISTS `T_BUILD_HISTORY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` varchar(128) NOT NULL,
  `BUILD_ID` varchar(128) NOT NULL,
  `VM_SEQ_ID` varchar(128) NOT NULL,
  `VM_IP` varchar(64) NOT NULL,
  `START_TIME` datetime DEFAULT NULL,
  `END_TIME` datetime DEFAULT NULL,
  `STATUS` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `IDX_SEQ` (`BUILD_ID`,`VM_SEQ_ID`) USING BTREE,
  KEY `IDX_VMIP` (`VM_IP`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Table structure for T_MAC_HOST_MACHINE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `T_MAC_HOST_MACHINE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(64) NOT NULL DEFAULT '',
  `IP` varchar(64) NOT NULL,
  `USER_NAME` varchar(64) NOT NULL,
  `PASSWORD` varchar(64) NOT NULL DEFAULT '',
  `CREATE_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `IDX_IP` (`IP`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Table structure for T_VIRTUAL_MACHINE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `T_VIRTUAL_MACHINE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(128) NOT NULL,
  `IP` varchar(64) NOT NULL,
  `USER_NAME` varchar(64) NOT NULL,
  `PASSWORD` varchar(64) NOT NULL DEFAULT '',
  `MOTHER_MACHINE_IP` varchar(64) NOT NULL,
  `STATUS` varchar(64) NOT NULL DEFAULT 'Unknown',
  `VM_TYPE_ID` int(11) NOT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `START_TIME` datetime DEFAULT NULL,
  `STATUS_CHANGE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `IDX_IP` (`IP`) USING BTREE,
  UNIQUE KEY `IDX_NAME` (`NAME`) USING BTREE,
  KEY `IDX_STATUS_START` (`STATUS`,`START_TIME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Table structure for T_VIRTUAL_MACHINE_TYPE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `T_VIRTUAL_MACHINE_TYPE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `SYSTEM_VERSION` varchar(255) NOT NULL,
  `XCODE_VERSION` varchar(2048) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;

SET FOREIGN_KEY_CHECKS = 1;
