USE devops_process;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `T_PIPELINE_CONTAINER_DISPATCH` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTAINER_ID` varchar(34) NOT NULL,
  `PIPELINE_ID` varchar(34) NOT NULL,
  `PIPELINE_VERSION` int(11) NOT NULL,
  `PROJECT_ID` varchar(64) NOT NULL,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DISPATCH_BUILD_TYPE` varchar(40) NOT NULL,
  `DISPATCH_VALUE` varchar(254) NOT NULL,
  `DISPATCH_IMAGE_TYPE` varchar(32) DEFAULT NULL,
  `DISPATCH_CREDENTIAL_ID` varchar(34) DEFAULT NULL,
  `DISPATCH_WORKSPACE` varchar(254) DEFAULT NULL,
  `DISPATCH_AGENT_TYPE` varchar(32) DEFAULT NULL,
  `DISPATCH_SYSTEM_VERSION` varchar(255) DEFAULT NULL,
  `DISPATCH_XCODE_VERSION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `DISPATCH_BUILD_TYPE_DISPATCH_VALUE` (`DISPATCH_BUILD_TYPE`,`DISPATCH_VALUE`),
  KEY `DISPATCH_VALUE` (`DISPATCH_VALUE`),
  KEY `PIPELINE_ID_PIPELINE_VERSION` (`PIPELINE_ID`,`PIPELINE_VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
