USE devops_ci_support;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for T_APP_VERSION
-- ----------------------------

CREATE TABLE IF NOT EXISTS  `T_APP_VERSION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VERSION_ID` varchar(100) NOT NULL DEFAULT '' COMMENT '版本号',
  `RELEASE_DATE` datetime DEFAULT NULL COMMENT '发布日期',
  `RELEASE_CONTENT` text NOT NULL COMMENT '发布内容',
  `CHANNEL_TYPE` tinyint(1) NOT NULL DEFAULT '1' COMMENT '渠道类型（1:"安卓", 2:"IOS"）',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- ----------------------------
-- Table structure for T_MESSAGE_CODE_DETAIL
-- ----------------------------

CREATE TABLE IF NOT EXISTS  `T_MESSAGE_CODE_DETAIL` (
  `ID` varchar(32) NOT NULL DEFAULT '' COMMENT '主键',
  `MESSAGE_CODE` varchar(128) NOT NULL DEFAULT '' COMMENT 'code码',
  `MODULE_CODE` char(2) NOT NULL COMMENT '模块代码',
  `MESSAGE_DETAIL_ZH_CN` varchar(200) NOT NULL COMMENT '中文简体描述信息',
  `MESSAGE_DETAIL_ZH_TW` varchar(200) DEFAULT NULL COMMENT '中文繁体描述信息',
  `MESSAGE_DETAIL_EN` varchar(200) DEFAULT NULL COMMENT '英文描述信息',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `uni_inx_tmcd_message_code` (`MESSAGE_CODE`) USING BTREE,
  KEY `inx_tmcd_module_code` (`MODULE_CODE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='信息码详情表';

CREATE TABLE IF NOT EXISTS `T_NOTICE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOTICE_TITLE` varchar(100) NOT NULL COMMENT '公告标题',
  `EFFECT_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '生效日期',
  `INVALID_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '失效日期',
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  `UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期',
  `NOTICE_CONTENT` text NOT NULL COMMENT '公告内容',
  `REDIRECT_URL` varchar(200) DEFAULT NULL COMMENT '跳转地址',
  `NOTICE_TYPE` tinyint(4) NOT NULL DEFAULT '0' COMMENT '消息类型:0.弹框 1.跑马灯',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `inx_tn_effect_date` (`EFFECT_DATE`) USING BTREE,
  KEY `inx_tn_invalid_date` (`INVALID_DATE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `T_WECHAT_WORK_MESSAGE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MESSAGE_ID` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `MESSAGE_ID_INDEX` (`MESSAGE_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `T_WECHAT_WORK_PROJECT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `GROUP_ID` varchar(32) NOT NULL DEFAULT '',
  `PROJECT_ID` varchar(32) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;


SET FOREIGN_KEY_CHECKS = 1;

