USE devops_ci_dispatch_idc;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `T_IDC_IP_INFO` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `IDC_IP` varchar(64) NOT NULL DEFAULT '' COMMENT 'IDC IP',
  `CAPACITY` int(11) NOT NULL DEFAULT '0' COMMENT '节点容器总容量',
  `USED_NUM` int(11) NOT NULL DEFAULT '0' COMMENT '节点容器已使用容量',
  `ENABLE` bit(1) DEFAULT b'0' COMMENT '节点是否可用',
  `GRAY_ENV` bit(1) DEFAULT b'0' COMMENT '是否为灰度节点',
  `GMT_CREATE` datetime DEFAULT NULL COMMENT '创建时间',
  `GMT_MODIFIED` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_IP` (`IDC_IP`),
  KEY `idx_1` (`ENABLE`,`GRAY_ENV`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COMMENT='IDC构建机负载表';

CREATE TABLE IF NOT EXISTS `T_IDC_TASK_HISTORY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PIPELINE_ID` varchar(64) NOT NULL DEFAULT '' COMMENT '流水线ID',
  `BUILD_ID` varchar(64) NOT NULL DEFAULT '' COMMENT '构建ID',
  `VM_SEQ` varchar(64) NOT NULL DEFAULT '' COMMENT '构建机序号',
  `CONTAINER_ID` varchar(64) NOT NULL DEFAULT '' COMMENT '构建容器ID',
  `IDC_IP` varchar(64) NOT NULL DEFAULT '' COMMENT '构建容器IP',
  `STATUS` int(11) DEFAULT '0' COMMENT '构建机状态',
  `GMT_CREATE` datetime DEFAULT NULL COMMENT '创建时间',
  `GMT_MODIFIED` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_BUILD_SEQ` (`BUILD_ID`,`VM_SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=331 DEFAULT CHARSET=utf8 COMMENT='IDC构建任务历史表';
SET FOREIGN_KEY_CHECKS = 1;
