USE devops_ci_experience;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for T_AUTH_GROUP
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ARTIFACTORY_TYPE` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ARTIFACTORY_PATH` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `ARTIFACTORY_SHA1` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAME` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `PLATFORM` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `BUNDLE_IDENTIFIER` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `VERSION` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `REMARK` text COLLATE utf8mb4_unicode_ci,
  `END_DATE` datetime NOT NULL,
  `EXPERIENCE_GROUPS` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `INNER_USERS` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `OUTER_USERS` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `NOTIFY_TYPES` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `WECHAT_GROUPS` mediumtext COLLATE utf8mb4_unicode_ci,
  `ONLINE` bit(1) NOT NULL DEFAULT b'1',
  `SOURCE` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `CREATOR` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `UPDATOR` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CREATE_TIME` datetime NOT NULL,
  `UPDATE_TIME` datetime NOT NULL,
  `ENABLE_WECHAT_GROUPS` bit(1) NOT NULL DEFAULT b'1',
  `EXPERIENCE_NAME` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '体验名称',
  `VERSION_TITLE` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '版本标题',
  `CATEGORY` int(11) NOT NULL DEFAULT '-1' COMMENT '产品类别',
  `PRODUCT_OWNER` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '[]' COMMENT '产品负责人',
  `LOGO_URL` varchar(300) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '图标地址',
  `SIZE` bigint(20) NOT NULL DEFAULT '-1' COMMENT '包大小',
  `SCHEME` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '应用的SCHEME',
  PRIMARY KEY (`ID`),
  KEY `PROJECT_ID` (`PROJECT_ID`) USING BTREE,
  KEY `ARTIFACTORY_SHA1` (`ARTIFACTORY_SHA1`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_BANNER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `RECORD_ID` bigint(20) NOT NULL COMMENT '对应的T_EXPERIENCE主键',
  `BANNER_URL` varchar(100) NOT NULL COMMENT 'banner_url',
  `ONLINE` bit(1) NOT NULL COMMENT '是否上线',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建日期',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新日期',
  `PLATFORM` varchar(10) NOT NULL COMMENT '操作系统',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体验--banner表';

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_DOWNLOAD` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EXPERIENCE_ID` bigint(20) NOT NULL,
  `USER_ID` varchar(64) NOT NULL,
  `TIMES` int(11) NOT NULL,
  `CREATE_TIME` datetime NOT NULL,
  `UPDATE_TIME` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EXPERIENCE_ID_USER_ID` (`EXPERIENCE_ID`,`USER_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_GROUP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `RECORD_ID` bigint(20) NOT NULL COMMENT '对应的体验记录ID',
  `GROUP_ID` bigint(20) NOT NULL COMMENT '体验组ID',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建日期',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新日期',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_RECORDID_GROUPID` (`RECORD_ID`,`GROUP_ID`),
  KEY `IDX_GROUP_ID` (`GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体验--记录对应体验组';

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_GROUP_INNER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `GROUP_ID` bigint(20) NOT NULL COMMENT '对应的组号',
  `USER_ID` varchar(20) NOT NULL COMMENT '用户名',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建日期',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新日期',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_GROUPID_USERID` (`GROUP_ID`,`USER_ID`),
  KEY `IDX_USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体验--体验组--内部用户';

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_INNER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `RECORD_ID` bigint(20) NOT NULL COMMENT '对应的体验记录ID',
  `USER_ID` varchar(20) NOT NULL COMMENT '用户名',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建日期',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新日期',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_RECORDID_USERID` (`RECORD_ID`,`USER_ID`),
  KEY `IDX_USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体验--记录对应内部用户';

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_PUBLIC` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `RECORD_ID` bigint(20) NOT NULL COMMENT '对应的T_EXPERIENCE主键',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `EXPERIENCE_NAME` varchar(100) NOT NULL DEFAULT '' COMMENT '体验名称',
  `CATEGORY` int(11) NOT NULL DEFAULT '-1' COMMENT '产品类别',
  `PLATFORM` varchar(10) NOT NULL COMMENT '操作系统',
  `BUNDLE_IDENTIFIER` varchar(100) NOT NULL COMMENT '包的bundle',
  `END_DATE` datetime NOT NULL COMMENT '结束日期',
  `ONLINE` bit(1) NOT NULL COMMENT '是否上线',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建日期',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新日期',
  `DOWNLOAD_TIME` int(11) NOT NULL DEFAULT '0' COMMENT '下载次数',
  `SIZE` bigint(20) NOT NULL COMMENT '包大小',
  `LOGO_URL` varchar(300) NOT NULL DEFAULT '' COMMENT '图标地址',
  `NECESSARY` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否为鹅厂必备',
  `BANNER_URL` varchar(200) NOT NULL DEFAULT '' COMMENT '配置的BannerURL',
  `NECESSARY_INDEX` int(11) NOT NULL DEFAULT '0' COMMENT '鹅厂必备排序(越小排越前)',
  `BANNER_INDEX` int(11) NOT NULL DEFAULT '0' COMMENT '鹅厂Banner排序(越小排越前)',
  `TYPE` int(11) NOT NULL DEFAULT '1' COMMENT '公开体验类型,1--公司内部,2--外部链接跳转',
  `EXTERNAL_LINK` varchar(300) NOT NULL DEFAULT '' COMMENT '外部链接',
  `SCHEME` text NOT NULL COMMENT '应用的SCHEME',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_PRODUCTID_IDENTIFIER_PLATFORM` (`PROJECT_ID`,`BUNDLE_IDENTIFIER`,`PLATFORM`),
  KEY `IDX_RECORDID` (`RECORD_ID`),
  KEY `IDX_NECESSARY_PLATFORM` (`NECESSARY`,`PLATFORM`),
  KEY `IDX_BANNER_PLATFORM` (`BANNER_URL`,`PLATFORM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公开体验表';

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_SRCH_RECOMMEND` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `CONTENT` varchar(100) NOT NULL COMMENT '搜索内容',
  `ONLINE` bit(1) NOT NULL COMMENT '是否上线',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建日期',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新日期',
  `PLATFORM` varchar(10) NOT NULL COMMENT '操作系统',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体验--搜索推荐表';

CREATE TABLE IF NOT EXISTS `T_TOKEN`(
  `ID`  bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `EXPERIENCE_ID` bigint(20) NOT NULL COMMENT '体验ID',
  `USER_ID`  varchar(64) NOT NULL COMMENT '用户ID',
  `TOKEN`  varchar(64) NOT NULL COMMENT 'Token',
  `EXPIRE_TIME`  datetime  NOT NULL COMMENT 'Token过期时间',
  `CREATE_TIME`  datetime  NOT NULL COMMENT '创建时间',
  `UPDATE_TIME`  datetime  NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TOKEN` (`TOKEN`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体验--用户体验TOKEN表';

CREATE TABLE IF NOT EXISTS `T_GROUP` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` varchar(64) NOT NULL,
  `NAME` varchar(64) NOT NULL,
  `INNER_USERS` text NOT NULL,
  `INNER_USERS_COUNT` int(11) NOT NULL,
  `OUTER_USERS` text NOT NULL,
  `OUTER_USERS_COUNT` int(11) NOT NULL,
  `REMARK` text,
  `CREATOR` varchar(64) NOT NULL,
  `UPDATOR` varchar(64) NOT NULL,
  `CREATE_TIME` datetime NOT NULL,
  `UPDATE_TIME` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `PROJECT_ID` (`PROJECT_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_OUTER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `RECORD_ID` bigint(20) NOT NULL COMMENT '对应的体验记录ID',
  `OUTER` varchar(100) NOT NULL COMMENT '外部用户',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建日期',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新日期',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_RECORDID_OUTER` (`RECORD_ID`,`OUTER`),
  KEY `IDX_OUTER` (`OUTER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体验--外部用户';

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_GROUP_OUTER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `GROUP_ID` bigint(20) NOT NULL COMMENT '对应的组号',
  `OUTER` varchar(100) NOT NULL COMMENT '外部用户',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建日期',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新日期',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_GROUPID_USERID` (`GROUP_ID`,`OUTER`),
  KEY `IDX_OUTER` (`OUTER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体验--体验组--外部用户';

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_DOWNLOAD_DETAIL` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_ID` varchar(20) NOT NULL COMMENT '用户ID',
  `RECORD_ID` bigint(20) NOT NULL COMMENT '体验ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `BUNDLE_IDENTIFIER` varchar(100) NOT NULL COMMENT '包的bundle',
  `PLATFORM` varchar(10) NOT NULL COMMENT '操作系统',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建日期',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新日期',
  PRIMARY KEY (`ID`),
  KEY `IDX_PID_BID_PLA` (`PROJECT_ID`,`BUNDLE_IDENTIFIER`,`PLATFORM`),
  KEY `IDX_UID` (`USER_ID`),
  KEY `IDX_RID` (`RECORD_ID`),
  KEY `IDX_CTIME` (`CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体验下载详细记录';

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_LAST_DOWNLOAD` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `USER_ID` varchar(20) NOT NULL COMMENT '用户名',
  `BUNDLE_IDENTIFIER` varchar(100) NOT NULL COMMENT '包的bundle',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `PLATFORM` varchar(10) NOT NULL COMMENT '操作系统',
  `LAST_DONWLOAD_RECORD_ID` bigint(20) NOT NULL COMMENT '对应的T_EXPERIENCE主键',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建日期',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新日期',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_USER_BUNDLE_PROJECTID_PLATFORM` (`USER_ID`,`BUNDLE_IDENTIFIER`,`PROJECT_ID`,`PLATFORM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='上次下载记录表';

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_OUTER_LOGIN_HISTORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `USERNAME` varchar(50) NOT NULL COMMENT '用户名',
  `REAL_IP` varchar(20) NOT NULL COMMENT '客户端IP',
  `LOGIN_TIME` datetime NOT NULL COMMENT '登录时间',
  `APP_VERSION` varchar(10) NOT NULL COMMENT 'APP版本',
  `PLATFORM` int(11) NOT NULL COMMENT '平台 , 1--安卓 , 2--IOS',
  PRIMARY KEY (`ID`),
  KEY `idx_username` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外部人员登录记录';

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_SUBSCRIBE`
(
    `ID`                BIGINT(20)   NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `USER_ID`           VARCHAR(64)  NOT NULL COMMENT '用户id',
    `PROJECT_ID`        VARCHAR(64)  Not NULL COMMENT '项目ID',
    `BUNDLE_IDENTIFIER` VARCHAR(100) Not NULL COMMENT '包的bundle',
    `PLATFORM`          VARCHAR(10)  Not NULL COMMENT '平台',
    `CREATE_TIME`       DATETIME     NOT NULL COMMENT '创建时间',
    `UPDATE_TIME`       DATETIME     NOT NULL COMMENT '修改时间',
    PRIMARY KEY (`ID`),
    INDEX `IDX_USERID` (`USER_ID`),
    INDEX `IDX_PROJECTED_IDENTIFIER_PLATFORM` (`PROJECT_ID`, `BUNDLE_IDENTIFIER`, `PLATFORM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户订阅体验表';

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_PUSH_TOKEN` (
   `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
   `USER_ID` VARCHAR(64) NOT NULL COMMENT '用户id',
   `TOKEN` VARCHAR(64) NOT NULL COMMENT 'TOKEN',
   `PLATFORM`    VARCHAR(10) NOT NULL COMMENT '平台',
   `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
   `UPDATE_TIME` DATETIME NOT NULL COMMENT '修改时间',
   INDEX `IDX_USER_ID` (USER_ID),
   INDEX `IDX_TOKEN` (TOKEN),
   INDEX `IDX_PLATFORM` (PLATFORM),
   PRIMARY KEY (`ID`),
   UNIQUE INDEX `TOKEN_UNIQUE` (`TOKEN` ASC)
)ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT '用户设备TOKEN';

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_PUSH_HISTORY`
(
    `ID`           BIGINT(20)  NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `STATUS`       INT(2)      NOT NULL COMMENT '发送状态 0-待发送 ,1-发送成功,2-发送失败 ',
    `RECEIVERS`    VARCHAR(64) NOT NULL COMMENT '接收者',
    `CONTENT`      text        NOT NULL COMMENT '内容',
    `URL`          text        NOT NULL COMMENT '跳转路径',
    `PLATFORM`     VARCHAR(10) NOT NULL COMMENT '平台',
    `TITLE`        text        NOT NULL COMMENT '标题',
    `CREATED_TIME` DATETIME    NOT NULL COMMENT '创建时间',
    `UPDATED_TIME` DATETIME    NOT NULL COMMENT '更新时间',
    INDEX `IDX_RECEIVERS` (RECEIVERS),
    INDEX `IDX_CREATED_TIME` (CREATED_TIME),
    INDEX `IDX_STATUS` (STATUS),
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '推送消息记录';

CREATE TABLE IF NOT EXISTS `T_EXPERIENCE_EXTEND_BANNER`
(
    `ID`          bigint(20)   NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `BANNER_URL`  varchar   (200) NOT NULL DEFAULT '' COMMENT '配置的BannerURL',
    `TYPE`        int(2)       NOT NULL COMMENT '类型',
    `LINK`        varchar(300) NOT NULL DEFAULT '' COMMENT '跳转链接',
    `ONLINE`      bit(1)       NOT NULL COMMENT '是否上线',
    `END_DATE`    datetime     NOT NULL COMMENT '结束日期',
    `CREATE_TIME` datetime     NOT NULL COMMENT '创建日期',
    `UPDATE_TIME` datetime     NOT NULL COMMENT '更新日期',
    PRIMARY KEY (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT ='体验Banner扩展表';

SET FOREIGN_KEY_CHECKS = 1;
