USE devops_ci_sign;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for T_SIGN_HISTORY
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_SIGN_HISTORY` (
  `RESIGN_ID` varchar(64) NOT NULL COMMENT '签名ID',
  `USER_ID` varchar(64) NOT NULL DEFAULT 'system' COMMENT '用户ID',
  `PROJECT_ID` varchar(64) DEFAULT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(64) DEFAULT NULL COMMENT '流水线ID',
  `BUILD_ID` varchar(64) DEFAULT NULL COMMENT '构建ID',
  `TASK_ID` varchar(64) DEFAULT NULL COMMENT '任务ID',
  `TASK_EXECUTE_COUNT` int(11) DEFAULT NULL COMMENT '任务执行计数',
  `ARCHIVE_TYPE` varchar(32) DEFAULT NULL COMMENT '归档类型',
  `ARCHIVE_PATH` text COMMENT '归档路径',
  `FILE_MD5` varchar(64) DEFAULT NULL COMMENT '文件MD5',
  `STATUS` varchar(32) DEFAULT NULL COMMENT '状态',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `END_TIME` timestamp NULL DEFAULT NULL COMMENT '结束时间',
  `RESULT_FILE_MD5` varchar(64) DEFAULT NULL COMMENT '文件MD5',
  `RESULT_FILE_NAME` varchar(512) DEFAULT NULL COMMENT '文件名称',
  `UPLOAD_FINISH_TIME` timestamp NULL DEFAULT NULL COMMENT '上传完成时间',
  `UNZIP_FINISH_TIME` timestamp NULL DEFAULT NULL COMMENT '解压完成时间',
  `RESIGN_FINISH_TIME` timestamp NULL DEFAULT NULL COMMENT '签名完成时间',
  `ZIP_FINISH_TIME` timestamp NULL DEFAULT NULL COMMENT '打包完成时间',
  `ARCHIVE_FINISH_TIME` timestamp NULL DEFAULT NULL COMMENT '归档完成时间',
  `ERROR_MESSAGE` text COMMENT '错误信息',
  PRIMARY KEY (`RESIGN_ID`) USING BTREE,
  KEY `INX_BUILD_TASK_COUNT` (`BUILD_ID`,`TASK_ID`,`TASK_EXECUTE_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签名历史记录表';

-- ----------------------------
-- Table structure for T_SIGN_IPA_INFO
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_SIGN_IPA_INFO` (
  `RESIGN_ID` varchar(64) NOT NULL COMMENT '签名ID',
  `USER_ID` varchar(64) NOT NULL COMMENT '用户ID',
  `WILDCARD` bit(1) NOT NULL COMMENT '是否采用通配符重签',
  `CERT_ID` varchar(128) DEFAULT NULL COMMENT '证书ID',
  `PROJECT_ID` varchar(64) DEFAULT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(64) DEFAULT NULL COMMENT '流水线ID',
  `BUILD_ID` varchar(64) DEFAULT NULL COMMENT '构建ID',
  `TASK_ID` varchar(64) DEFAULT NULL COMMENT '任务ID',
  `ARCHIVE_TYPE` varchar(32) DEFAULT NULL COMMENT '归档类型',
  `ARCHIVE_PATH` text COMMENT '归档路径',
  `MOBILE_PROVISION_ID` varchar(128) DEFAULT NULL COMMENT '移动设备 ID',
  `UNIVERSAL_LINKS` text COMMENT 'Universal Link的设置',
  `KEYCHAIN_ACCESS_GROUPS` text COMMENT '钥匙串访问组',
  `REPLACE_BUNDLE` bit(1) DEFAULT NULL COMMENT '是否替换bundleId',
  `APPEX_SIGN_INFO` text COMMENT '拓展应用名和对应的描述文件ID',
  `FILENAME` text COMMENT '文件名称',
  `FILE_SIZE` bigint(32) DEFAULT NULL COMMENT '文件大小',
  `FILE_MD5` varchar(64) DEFAULT NULL COMMENT '文件MD5',
  `REQUEST_CONTENT` text NOT NULL COMMENT '事件内容',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`RESIGN_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签名任务信息表';

-- ----------------------------
-- Table structure for T_SIGN_IPA_UPLOAD
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_SIGN_IPA_UPLOAD` (
  `UPLOAD_TOKEN` varchar(64) NOT NULL COMMENT 'token',
  `USER_ID` varchar(64) NOT NULL COMMENT '用户ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(64) NOT NULL COMMENT '流水线ID',
  `BUILD_ID` varchar(64) NOT NULL COMMENT '构建ID',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `RESIGN_ID` varchar(64) DEFAULT NULL COMMENT '签名ID',
  PRIMARY KEY (`UPLOAD_TOKEN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='签名包上传记录表';

SET FOREIGN_KEY_CHECKS = 1;