USE devops_ci_dispatch_codecc;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `T_BUILD_CONTAINER_POOL_NO` (
  `BUILD_ID` varchar(64) NOT NULL COMMENT '构建ID',
  `VM_SEQ_ID` varchar(64) NOT NULL COMMENT 'VmSeqID',
  `CONTAINER_NAME` varchar(128) DEFAULT NULL COMMENT '容器名称',
  `POOL_NO` varchar(128) DEFAULT NULL COMMENT '构建机池编号',
  `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`BUILD_ID`,`VM_SEQ_ID`),
  KEY `inx_tpi_create_time` (`CREATE_TIME`),
  KEY `inx_tpi_build_id` (`BUILD_ID`),
  KEY `inx_tpi_vm_seq_id` (`VM_SEQ_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='buildId和containerName,poolNo的映射关系';

CREATE TABLE IF NOT EXISTS `T_DEVCLOUD_BUILD` (
  `PIPELINE_ID` varchar(34) NOT NULL,
  `VM_SEQ_ID` varchar(34) NOT NULL,
  `POOL_NO` int(11) NOT NULL,
  `PROJECT_ID` varchar(64) NOT NULL,
  `CONTAINER_NAME` varchar(128) NOT NULL,
  `IMAGES` varchar(1024) NOT NULL,
  `STATUS` int(11) NOT NULL,
  `CREATED_TIME` timestamp NULL DEFAULT NULL,
  `UPDATE_TIME` timestamp NULL DEFAULT NULL,
  `USER_ID` varchar(34) NOT NULL,
  PRIMARY KEY (`PIPELINE_ID`,`VM_SEQ_ID`,`POOL_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DevCloud流水线构建机信息';

CREATE TABLE IF NOT EXISTS `T_DEVCLOUD_BUILD_HIS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `PIPELINE_ID` varchar(64) NOT NULL DEFAULT '' COMMENT 'pipeline id',
  `BUIDLD_ID` varchar(64) NOT NULL DEFAULT '' COMMENT 'build id',
  `VM_SEQ_ID` varchar(64) NOT NULL DEFAULT '' COMMENT 'vm seq id',
  `CONTAINER_NAME` varchar(128) DEFAULT '' COMMENT '容器名称',
  `SECRET_KEY` varchar(64) NOT NULL DEFAULT '' COMMENT '构建密钥',
  `GMT_CREATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `GMT_MODIFIED` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  KEY `idx_1` (`BUIDLD_ID`,`PIPELINE_ID`,`VM_SEQ_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1248 DEFAULT CHARSET=utf8 COMMENT='devcloud 构建历史记录';

CREATE TABLE IF NOT EXISTS `T_DISPATCH_CODECC_BUILD_TASK` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` varchar(64) NOT NULL,
  `CODECC_TASK_ID` bigint(20) NOT NULL,
  `AGENT_ID` varchar(32) NOT NULL,
  `PIPELINE_ID` varchar(34) NOT NULL,
  `BUILD_ID` varchar(34) NOT NULL,
  `VM_SEQ_ID` int(20) NOT NULL,
  `STATUS` int(11) NOT NULL,
  `SECRET_KEY` varchar(128) NOT NULL,
  `IMAGE_NAME` varchar(1024) NOT NULL,
  `CHANNEL_CODE` varchar(128) DEFAULT NULL,
  `HOST_TAG` varchar(128) DEFAULT NULL,
  `CONTAINER_ID` varchar(128) DEFAULT NULL,
  `CREATED_TIME` datetime NOT NULL,
  `UPDATED_TIME` datetime NOT NULL,
  `REGISTRY_USER` varchar(128) DEFAULT NULL,
  `REGISTRY_PWD` varchar(128) DEFAULT NULL,
  `IMAGE_TYPE` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `BUILD_ID_IDX` (`BUILD_ID`,`VM_SEQ_ID`),
  KEY `HOST_TAG_IDX` (`HOST_TAG`)
) ENGINE=InnoDB AUTO_INCREMENT=2907870 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `T_DISPATCH_PIPELINE_DOCKER_BUILD` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BUILD_ID` varchar(64) NOT NULL,
  `VM_SEQ_ID` int(20) NOT NULL,
  `SECRET_KEY` varchar(64) NOT NULL DEFAULT '',
  `STATUS` int(11) NOT NULL,
  `CREATED_TIME` datetime NOT NULL,
  `UPDATED_TIME` datetime NOT NULL,
  `ZONE` varchar(128) DEFAULT NULL,
  `PROJECT_ID` varchar(34) DEFAULT '',
  `PIPELINE_ID` varchar(34) DEFAULT '',
  `DISPATCH_MESSAGE` varchar(4096) DEFAULT '',
  `STARTUP_MESSAGE` text,
  `ROUTE_KEY` varchar(64) DEFAULT '',
  `DOCKER_INST_ID` bigint(20) DEFAULT NULL,
  `VERSION_ID` int(20) DEFAULT NULL,
  `TEMPLATE_ID` int(20) DEFAULT NULL,
  `NAMESPACE_ID` bigint(20) DEFAULT NULL,
  `DOCKER_IP` varchar(64) DEFAULT '' COMMENT '构建机IP',
  `CONTAINER_ID` varchar(128) DEFAULT '' COMMENT '构建容器ID',
  `POOL_NO` int(11) DEFAULT '0' COMMENT '构建容器池序号',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `BUILD_ID` (`BUILD_ID`,`VM_SEQ_ID`),
  KEY `idx_1` (`STATUS`,`UPDATED_TIME`)
) ENGINE=InnoDB AUTO_INCREMENT=37497570 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `T_DISPATCH_PIPELINE_DOCKER_HOST` (
  `PROJECT_CODE` varchar(128) NOT NULL,
  `HOST_IP` varchar(128) NOT NULL,
  `REMARK` varchar(1024) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_TIME` datetime DEFAULT CURRENT_TIMESTAMP,
  `TYPE` int(11) NOT NULL DEFAULT '0' COMMENT '母机类型, 0表示是构建环境的构建机, 1表示是无编译环境的机器',
  `ROUTE_KEY` varchar(45) DEFAULT NULL COMMENT '消息队列的路由KEY',
  PRIMARY KEY (`PROJECT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='codecc专机配置表';

CREATE TABLE IF NOT EXISTS `T_DISPATCH_PIPELINE_DOCKER_IP_INFO` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `DOCKER_IP` varchar(64) NOT NULL DEFAULT '' COMMENT 'DOCKER IP',
  `DOCKER_HOST_PORT` int(11) NOT NULL DEFAULT '80' COMMENT 'DOCKER PORT',
  `CAPACITY` int(11) NOT NULL DEFAULT '0' COMMENT '节点容器总容量',
  `USED_NUM` int(11) NOT NULL DEFAULT '0' COMMENT '节点容器已使用容量',
  `CPU_LOAD` int(11) NOT NULL DEFAULT '0' COMMENT '节点容器CPU负载',
  `MEM_LOAD` int(11) NOT NULL DEFAULT '0' COMMENT '节点容器MEM负载',
  `DISK_LOAD` int(11) NOT NULL DEFAULT '0' COMMENT '节点容器DISK负载',
  `DISK_IO_LOAD` int(11) NOT NULL DEFAULT '0' COMMENT '节点容器DISK IO负载',
  `ENABLE` bit(1) DEFAULT b'0' COMMENT '节点是否可用',
  `SPECIAL_ON` bit(1) DEFAULT b'0' COMMENT '节点是否作为专用机',
  `GRAY_ENV` bit(1) DEFAULT b'0' COMMENT '是否为灰度节点',
  `GMT_CREATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `GMT_MODIFIED` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `CLUSTER_NAME` varchar(64) DEFAULT 'OPENSOURCE' COMMENT '节点所属集群',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_IP` (`DOCKER_IP`),
  KEY `idx_1` (`ENABLE`,`GRAY_ENV`,`CPU_LOAD`,`MEM_LOAD`,`DISK_LOAD`,`DISK_IO_LOAD`)
) ENGINE=InnoDB AUTO_INCREMENT=439 DEFAULT CHARSET=utf8mb4 COMMENT='DOCKER构建机负载表';

CREATE TABLE IF NOT EXISTS `T_DISPATCH_PIPELINE_DOCKER_POOL` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `PIPELINE_ID` varchar(64) NOT NULL DEFAULT '' COMMENT '流水线ID',
  `VM_SEQ` varchar(64) NOT NULL DEFAULT '' COMMENT '构建机序号',
  `POOL_NO` int(11) NOT NULL DEFAULT '0' COMMENT '构建池序号',
  `STATUS` int(11) NOT NULL DEFAULT '0' COMMENT '构建池状态',
  `GMT_CREATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `GMT_MODIFIED` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_BUILD_SEQ` (`PIPELINE_ID`,`VM_SEQ`,`POOL_NO`),
  KEY `idx_2` (`STATUS`,`GMT_MODIFIED`)
) ENGINE=InnoDB AUTO_INCREMENT=291285 DEFAULT CHARSET=utf8mb4 COMMENT='DOCKER并发构建池状态表';

CREATE TABLE IF NOT EXISTS `T_DISPATCH_PIPELINE_DOCKER_TASK_DRIFT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `PIPELINE_ID` varchar(64) NOT NULL DEFAULT '' COMMENT '流水线ID',
  `BUILD_ID` varchar(64) NOT NULL DEFAULT '' COMMENT '构建ID',
  `VM_SEQ` varchar(64) NOT NULL DEFAULT '' COMMENT '构建机序号',
  `OLD_DOCKER_IP` varchar(64) NOT NULL DEFAULT '' COMMENT '旧构建容器IP',
  `NEW_DOCKER_IP` varchar(64) NOT NULL DEFAULT '' COMMENT '新构建容器IP',
  `OLD_DOCKER_IP_INFO` varchar(1024) NOT NULL DEFAULT '' COMMENT '旧容器IP负载',
  `GMT_CREATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `GMT_MODIFIED` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_P_B` (`PIPELINE_ID`,`BUILD_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4235950 DEFAULT CHARSET=utf8mb4 COMMENT='DOCKER构建任务漂移记录表';

CREATE TABLE IF NOT EXISTS `T_DISPATCH_PIPELINE_DOCKER_TASK_SIMPLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `PIPELINE_ID` varchar(64) NOT NULL DEFAULT '' COMMENT '流水线ID',
  `VM_SEQ` varchar(64) NOT NULL DEFAULT '' COMMENT '构建机序号',
  `DOCKER_IP` varchar(64) NOT NULL DEFAULT '' COMMENT '构建容器IP',
  `GMT_CREATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `GMT_MODIFIED` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_BUILD_SEQ` (`PIPELINE_ID`,`VM_SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=457169 DEFAULT CHARSET=utf8mb4 COMMENT='DOCKER构建任务表';

SET FOREIGN_KEY_CHECKS = 1;
