USE devops_ci_sign;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for T_SIGN_HISTORY
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_SIGN_HISTORY` (
  `RESIGN_ID` varchar(64) NOT NULL,
  `USER_ID` varchar(64) NOT NULL DEFAULT 'system',
  `PROJECT_ID` varchar(64) DEFAULT NULL,
  `PIPELINE_ID` varchar(64) DEFAULT NULL,
  `BUILD_ID` varchar(64) DEFAULT NULL,
  `TASK_ID` varchar(64) DEFAULT NULL,
  `TASK_EXECUTE_COUNT` int(11) DEFAULT NULL,
  `ARCHIVE_TYPE` varchar(32) DEFAULT NULL,
  `ARCHIVE_PATH` text,
  `FILE_MD5` varchar(64) DEFAULT NULL,
  `STATUS` varchar(32) DEFAULT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `END_TIME` timestamp NULL DEFAULT NULL,
  `RESULT_FILE_MD5` varchar(64) DEFAULT NULL,
  `RESULT_FILE_NAME` varchar(512) DEFAULT NULL,
  `UPLOAD_FINISH_TIME` timestamp NULL DEFAULT NULL,
  `UNZIP_FINISH_TIME` timestamp NULL DEFAULT NULL,
  `RESIGN_FINISH_TIME` timestamp NULL DEFAULT NULL,
  `ZIP_FINISH_TIME` timestamp NULL DEFAULT NULL,
  `ARCHIVE_FINISH_TIME` timestamp NULL DEFAULT NULL,
  `ERROR_MESSAGE` text,
  PRIMARY KEY (`RESIGN_ID`) USING BTREE,
  KEY `inx_build_task_count` (`BUILD_ID`,`TASK_ID`,`TASK_EXECUTE_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


SET FOREIGN_KEY_CHECKS = 1;

