USE devops_ci_dispatch_gitci;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `T_BUILD_CONTAINER_POOL_NO` (
  `BUILD_ID` varchar(64) NOT NULL COMMENT '构建ID',
  `VM_SEQ_ID` varchar(64) NOT NULL COMMENT 'VmSeqID',
  `CONTAINER_NAME` varchar(128) DEFAULT NULL COMMENT '容器名称',
  `POOL_NO` varchar(128) DEFAULT NULL COMMENT '构建机池编号',
  `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`BUILD_ID`,`VM_SEQ_ID`),
  KEY `inx_tpi_create_time` (`CREATE_TIME`),
  KEY `inx_tpi_build_id` (`BUILD_ID`),
  KEY `inx_tpi_vm_seq_id` (`VM_SEQ_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='buildId和containerName,poolNo的映射关系';

CREATE TABLE IF NOT EXISTS `T_DEVCLOUD_BUILD` (
  `PIPELINE_ID` varchar(34) NOT NULL,
  `VM_SEQ_ID` varchar(34) NOT NULL,
  `POOL_NO` int(11) NOT NULL,
  `PROJECT_ID` varchar(64) NOT NULL,
  `CONTAINER_NAME` varchar(128) NOT NULL,
  `IMAGES` varchar(1024) NOT NULL,
  `STATUS` int(11) NOT NULL,
  `CREATED_TIME` timestamp NULL DEFAULT NULL,
  `UPDATE_TIME` timestamp NULL DEFAULT NULL,
  `USER_ID` varchar(34) NOT NULL,
  PRIMARY KEY (`PIPELINE_ID`,`VM_SEQ_ID`,`POOL_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DevCloud流水线构建机信息';

CREATE TABLE IF NOT EXISTS `T_GIT_CI_BUILD` (
  `PIPELINE_ID` varchar(34) NOT NULL,
  `VM_SEQ_ID` varchar(34) NOT NULL,
  `POOL_NO` int(11) NOT NULL,
  `PROJECT_ID` varchar(64) NOT NULL,
  `JOB_NAME` varchar(128) NOT NULL,
  `CREATED_TIME` timestamp NULL DEFAULT NULL,
  `UPDATE_TIME` timestamp NULL DEFAULT NULL,
  `USER_ID` varchar(34) NOT NULL,
  PRIMARY KEY (`PIPELINE_ID`,`VM_SEQ_ID`,`POOL_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='GITCI流水线JOB信息';

CREATE TABLE IF NOT EXISTS `T_GIT_PROJECT_CFS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `GIT_PROJECT_ID` int(11) NOT NULL DEFAULT '0' COMMENT '工蜂项目ID',
  `CFS_ID` int(11) NOT NULL DEFAULT '0' COMMENT 'cfs文件ID',
  `NAME` varchar(64) NOT NULL DEFAULT '' COMMENT '自定义文件系统名称',
  `VOLUME` int(11) NOT NULL DEFAULT '0' COMMENT '容量，单位为G',
  `SERVER_IP` varchar(256) NOT NULL DEFAULT '' COMMENT 'cfs服务地址',
  `DESCRIPTION` varchar(256) NOT NULL DEFAULT '' COMMENT '描述',
  `GMT_CREATE` datetime DEFAULT NULL COMMENT '创建时间',
  `GMT_MODIFIED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_PROJECT_ID` (`GIT_PROJECT_ID`),
  KEY `IDX_PROJECT_ID` (`GIT_PROJECT_ID`,`CFS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='GITCI CFS记录表';

CREATE TABLE IF NOT EXISTS `T_VOLUME_POOL` (
  `PIPELINE_ID` varchar(34) NOT NULL,
  `POOL_NO` int(11) NOT NULL,
  `PROJECT_ID` varchar(64) NOT NULL,
  `STATUS` int(11) NOT NULL,
  `VOLUME_ID` int(11) NOT NULL,
  `VOLUME_NAME` varchar(128) NOT NULL,
  `VOLUME` int(11) NOT NULL,
  `DESCRIPTION` varchar(1024) NOT NULL,
  `DEFAULT_MOUNT_IP` varchar(128) NOT NULL,
  `MOUNT_TARGETS` mediumtext NOT NULL,
  `USER_ID` varchar(34) NOT NULL,
  `CREATED_TIME` timestamp NULL DEFAULT NULL,
  `UPDATE_TIME` timestamp NULL DEFAULT NULL,
  `BUILD_ID` varchar(34) DEFAULT NULL,
  PRIMARY KEY (`PIPELINE_ID`,`POOL_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='GITCI VOLUME pool信息';
SET FOREIGN_KEY_CHECKS = 1;
