USE devops_ci_gitci;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for T_GIT_CI_SERVICES_CONF
-- ----------------------------

CREATE TABLE IF NOT EXISTS  `T_GIT_CI_SERVICES_CONF` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `IMAGE_NAME` varchar(64) NOT NULL DEFAULT '' COMMENT '镜像名称',
  `IMAGE_TAG` varchar(64) NOT NULL DEFAULT '' COMMENT '镜像标签',
  `REPO_URL` varchar(64) NOT NULL DEFAULT '' COMMENT '镜像仓库地址',
  `REPO_USERNAME` varchar(64) DEFAULT '' COMMENT '镜像仓库地址',
  `REPO_PWD` varchar(64) DEFAULT '' COMMENT '镜像仓库地址',
  `ENABLE` bit(1) DEFAULT b'0' COMMENT '是否启用',
  `ENV` text COMMENT '环境变量，json结构',
  `CREATE_USER` varchar(64) DEFAULT '' COMMENT '创建者',
  `UPDATE_USER` varchar(64) DEFAULT '' COMMENT '更新者',
  `GMT_CREATE` datetime DEFAULT NULL COMMENT '创建时间',
  `GMT_MODIFIED` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IMAGE_NAME` (`IMAGE_NAME`,`IMAGE_TAG`,`REPO_URL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='GITCI services配置记录表';

-- ----------------------------
-- Table structure for T_GIT_PIPELINE_RESOURCE
-- ----------------------------

CREATE TABLE IF NOT EXISTS  `T_GIT_PIPELINE_RESOURCE` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `GIT_PROJECT_ID` bigint(11) NOT NULL COMMENT '工蜂项目ID',
  `FILE_PATH` varchar(600) CHARACTER SET utf8mb4 NOT NULL DEFAULT '.ci.yml' COMMENT '工程中yml文件路径',
  `PIPELINE_ID` varchar(34) CHARACTER SET utf8mb4 NOT NULL DEFAULT '' COMMENT '对应蓝盾流水线ID',
  `DISPLAY_NAME` varchar(255) CHARACTER SET utf8mb4 NOT NULL DEFAULT '.ci' COMMENT '工蜂CI流水线名称',
  `CREATOR` varchar(64) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '最初创建人',
  `ENABLED` bit(1) NOT NULL DEFAULT b'1' COMMENT '流水线启用状态',
  `LATEST_BUILD_ID` varchar(34) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '最新一次构建ID',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `EXIST_BRANCHES` longtext COLLATE utf8mb4_bin COMMENT '当前流水线文件存在的分支',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `PIPELINE_ID` (`PIPELINE_ID`),
  UNIQUE KEY `pipeline` (`GIT_PROJECT_ID`,`FILE_PATH`),
  KEY `projectId` (`GIT_PROJECT_ID`),
  KEY `pipelineId` (`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='工蜂流水线资源表-存储流水线相关信息';

CREATE TABLE IF NOT EXISTS  `T_GIT_PROJECT_CONF` (
  `ID` bigint(11) NOT NULL COMMENT '工蜂项目ID',
  `NAME` varchar(128) NOT NULL COMMENT '工蜂项目名',
  `URL` varchar(1024) NOT NULL COMMENT '工蜂项目URL',
  `ENABLE` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否可以开启CI功能，默认false',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='工蜂项目灰度配置';

CREATE TABLE IF NOT EXISTS  `T_GIT_PROJECT_PIPELINE` (
  `ID` bigint(11) NOT NULL COMMENT '工蜂项目ID',
  `PROJECT_CODE` varchar(128) NOT NULL COMMENT '蓝盾项目Code',
  `PIPELINE_ID` varchar(128) NOT NULL COMMENT '蓝盾流水线ID',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  KEY `PROJECT_CODE` (`PROJECT_CODE`),
  KEY `PIPELINE_ID` (`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='工蜂CI项目与流水线对应关系';

CREATE TABLE IF NOT EXISTS  `T_GIT_REQUEST_EVENT` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `OBJECT_KIND` varchar(128) NOT NULL COMMENT '触发类型：push,tag_push,merge_request,issue,note,',
  `OPERATION_KIND` varchar(128) DEFAULT NULL COMMENT 'operation_kind, create, delete, update',
  `EXTENSION_ACTION` varchar(128) DEFAULT NULL COMMENT 'open, close, reopen, update, push-update, merge',
  `GIT_PROJECT_ID` bigint(11) NOT NULL COMMENT '工蜂项目ID',
  `BRANCH` varchar(1024) NOT NULL COMMENT 'branch',
  `TARGET_BRANCH` varchar(1024) DEFAULT NULL COMMENT 'targetBranch',
  `COMMIT_ID` varchar(1024) DEFAULT NULL COMMENT 'commit id',
  `COMMIT_MSG` varchar(1024) DEFAULT NULL COMMENT 'commit message',
  `COMMIT_TIMESTAMP` varchar(128) DEFAULT NULL COMMENT 'commit timestamp',
  `USER_NAME` varchar(1024) NOT NULL COMMENT 'user name',
  `TOTAL_COMMIT_COUNT` bigint(11) DEFAULT NULL COMMENT 'total_commits_count',
  `MERGE_REQUEST_ID` bigint(11) DEFAULT NULL COMMENT 'merge_request_id',
  `EVENT` longtext NOT NULL COMMENT 'event',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `DESCRIPTION` varchar(1024) DEFAULT NULL COMMENT '描述',
  `MR_TITLE` varchar(1024) DEFAULT NULL,
  `SOURCE_GIT_PROJECT_ID` bigint(11) DEFAULT NULL COMMENT 'fork库工蜂项目ID',
  PRIMARY KEY (`ID`),
  KEY `IDX_CREATE_TIME` (`CREATE_TIME`)
) ENGINE=InnoDB AUTO_INCREMENT=31127 DEFAULT CHARSET=utf8 COMMENT='工蜂CI WebHooks请求';

CREATE TABLE IF NOT EXISTS  `T_GIT_REQUEST_EVENT_BUILD` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `EVENT_ID` bigint(11) NOT NULL COMMENT 'EVENT_ID',
  `ORIGIN_YAML` longtext NOT NULL COMMENT '初始yaml',
  `NORMALIZED_YAML` longtext NOT NULL COMMENT '格式化后的yaml',
  `PIPELINE_ID` varchar(128) DEFAULT NULL COMMENT '蓝盾流水线ID',
  `BUILD_ID` varchar(128) DEFAULT NULL COMMENT '蓝盾流水线BuildId',
  `GIT_PROJECT_ID` bigint(11) NOT NULL COMMENT '工蜂项目ID',
  `BRANCH` varchar(1024) NOT NULL COMMENT 'branch',
  `OBJECT_KIND` varchar(128) NOT NULL COMMENT '触发类型：push,tag_push,merge_request,issue,note,',
  `DESCRIPTION` varchar(1024) DEFAULT NULL COMMENT '描述',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `TRIGGER_USER` varchar(64) DEFAULT NULL COMMENT '触发人',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '刷新时间',
  `RETRY_USER` varchar(64) DEFAULT NULL COMMENT '重试人',
  `SOURCE_GIT_PROJECT_ID` bigint(11) DEFAULT NULL COMMENT '源分支的所属库ID(为了支持fork库)',
  PRIMARY KEY (`ID`),
  KEY `EVENT_ID` (`EVENT_ID`),
  KEY `PIPELINE_ID` (`PIPELINE_ID`),
  KEY `BUILD_ID` (`BUILD_ID`),
  KEY `BRANCH` (`BRANCH`),
  KEY `idx_2` (`GIT_PROJECT_ID`,`BUILD_ID`,`OBJECT_KIND`)
) ENGINE=InnoDB AUTO_INCREMENT=1384 DEFAULT CHARSET=utf8 COMMENT='工蜂CI WebHooks请求触发的构建记录';


CREATE TABLE IF NOT EXISTS  `T_GIT_REQUEST_EVENT_NOT_BUILD` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `EVENT_ID` bigint(11) NOT NULL COMMENT 'EVENT_ID',
  `ORIGIN_YAML` longtext COMMENT '初始yaml',
  `NORMALIZED_YAML` longtext COMMENT '格式化后的yaml',
  `REASON` varchar(1024) DEFAULT NULL COMMENT '未触发构建原因',
  `GIT_PROJECT_ID` bigint(11) NOT NULL COMMENT '工蜂项目ID',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `REASON_DETAIL` varchar(1024) DEFAULT NULL COMMENT '未触发构建原因',
  `PIPELINE_ID` varchar(34) DEFAULT NULL,
  `FILE_PATH` varchar(1024) DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `EVENT_ID` (`EVENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=30285 DEFAULT CHARSET=utf8 COMMENT='工蜂CI WebHooks请求未触发的记录';

CREATE TABLE IF NOT EXISTS  `T_GIT_WEB_STARTER_YAML` (
  `NAME` varchar(32) NOT NULL,
  `DESCRIPTION` text,
  `ICON_NAME` varchar(64) DEFAULT NULL,
  `CATEGORIES` text,
  `YAML_CONTENT` longtext,
  `ICON_URL` text,
  `YAML_URL` text,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS  `T_REPOSITORY_CONF` (
  `ID` bigint(11) NOT NULL COMMENT '工蜂项目ID',
  `NAME` varchar(128) NOT NULL COMMENT '工蜂项目名',
  `URL` varchar(1024) NOT NULL COMMENT '工蜂项目URL',
  `HOME_PAGE` varchar(1024) NOT NULL COMMENT '工蜂项目HomePage',
  `GIT_HTTP_URL` varchar(1024) NOT NULL COMMENT '工蜂项目httpUrl',
  `GIT_SSH_URL` varchar(1024) NOT NULL COMMENT '工蜂项目sshUrl',
  `ENABLE_CI` bit(1) NOT NULL COMMENT '是否启用CI功能',
  `BUILD_PUSHED_BRANCHES` bit(1) NOT NULL COMMENT 'Build pushed branches',
  `LIMIT_CONCURRENT_JOBS` int(11) DEFAULT NULL COMMENT 'Limit concurrent jobs',
  `BUILD_PUSHED_PULL_REQUEST` bit(1) NOT NULL COMMENT 'Build pushed pull request',
  `AUTO_CANCEL_BRANCH_BUILDS` bit(1) NOT NULL COMMENT 'Auto cancel branch builds',
  `AUTO_CANCEL_PULL_REQUEST_BUILDS` bit(1) NOT NULL COMMENT 'Auto cancel pull request builds',
  `ENV` text COMMENT 'Environment variable',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `PROJECT_CODE` varchar(128) NOT NULL COMMENT '蓝盾项目Code',
  PRIMARY KEY (`ID`),
  KEY `PROJECT_CODE` (`PROJECT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='工蜂CI项目配置';

SET FOREIGN_KEY_CHECKS = 1;

