USE devops_ci_ai;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `T_AI_KB_SOURCE` (
  `ID` varchar(64) NOT NULL COMMENT '知识库ID',
  `SOURCE_NAME` varchar(128) NOT NULL COMMENT '知识库名称',
  `DESCRIPTION` varchar(512) DEFAULT NULL COMMENT '说明',
  `PROJECT_ID` varchar(64) DEFAULT NULL COMMENT '项目ID，空=平台级知识库',
  `SPACE_KEY` varchar(128) DEFAULT NULL COMMENT '文档空间 key',
  `SPACE_ID` varchar(64) DEFAULT NULL COMMENT '文档空间 ID',
  `ROOT_DOC_ID` varchar(64) DEFAULT NULL COMMENT '根文档 ID',
  `ROOT_URL` varchar(512) DEFAULT NULL COMMENT '根文档 URL',
  `URL_TEMPLATE` varchar(256) NOT NULL DEFAULT 'https://iwiki.woa.com/p/{docId}' COMMENT '链接模板',
  `BIND_AGENT` varchar(64) NOT NULL DEFAULT 'supervisor' COMMENT '绑定智能体',
  `MAX_SEARCH` int(11) NOT NULL DEFAULT 1 COMMENT '最多搜索',
  `MAX_LOCATE` int(11) NOT NULL DEFAULT 1 COMMENT '最多定位',
  `MAX_GET` int(11) NOT NULL DEFAULT 2 COMMENT '最多拉正文',
  `ENABLED` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否启用',
  `CREATED_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `UPDATED_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  INDEX `IDX_PROJECT_ID` (`PROJECT_ID`),
  INDEX `IDX_UPDATED_TIME` (`UPDATED_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI知识库（平台级或项目自有）';

CREATE TABLE IF NOT EXISTS `T_AI_KB_ENTRY` (
  `ID` varchar(64) NOT NULL COMMENT '条目ID',
  `SOURCE_ID` varchar(64) NOT NULL COMMENT '所属知识库',
  `TITLE` varchar(256) NOT NULL COMMENT '目录标题',
  `DOC_ID` varchar(64) DEFAULT NULL COMMENT '文档ID',
  `KEYWORDS` varchar(1024) DEFAULT NULL COMMENT '关键词，逗号分隔',
  `HINT` varchar(512) DEFAULT NULL COMMENT '路径提示',
  `SORT_ORDER` int(11) NOT NULL DEFAULT 0 COMMENT '排序',
  `ENABLED` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否启用',
  `CREATED_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `UPDATED_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  INDEX `IDX_SOURCE_ID` (`SOURCE_ID`),
  INDEX `IDX_SORT_ORDER` (`SOURCE_ID`, `SORT_ORDER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI知识库目录条目';
