export const PROCESS_API_URL_PREFIX = '/process/api'
export const STORE_API_URL_PREFIX = '/store/api'
export const ENVIRONMENT_API_URL_PREFIX = 'environment/api'
export const AUTH_API_URL_PREFIX = '/auth/api'
export const ARTIFACTORY_API_URL_PREFIX = '/artifactory/api'
