CREATE TABLE `T_GIT_CI_SERVICES_CONF` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `IMAGE_NAME` varchar(64) NOT NULL DEFAULT '' COMMENT '镜像名称',
  `IMAGE_TAG` varchar(64) NOT NULL DEFAULT '' COMMENT '镜像标签',
  `REPO_URL` varchar(64) NOT NULL DEFAULT '' COMMENT '镜像仓库地址',
  `REPO_USERNAME` varchar(64) DEFAULT '' COMMENT '镜像仓库地址',
  `REPO_PWD` varchar(64) DEFAULT '' COMMENT '镜像仓库地址',
  `ENABLE` bit DEFAULT 0 COMMENT '是否启用',
  `ENV` TEXT DEFAULT '' COMMENT '环境变量，json结构',
  `CREATE_USER` varchar(64) DEFAULT '' COMMENT '创建者',
  `UPDATE_USER` varchar(64) DEFAULT '' COMMENT '更新者',
  `GMT_CREATE` datetime DEFAULT NULL COMMENT '创建时间',
  `GMT_MODIFIED` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  INDEX `IDX_IMAGE` (`IMAGE_NAME`, `IMAGE_TAG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='GITCI services配置记录表';

ALTER TABLE T_GIT_CI_SERVICES_CONF DROP INDEX `IDX_IMAGE`;
ALTER TABLE T_GIT_CI_SERVICES_CONF ADD UNIQUE (`IMAGE_NAME`, `IMAGE_TAG`, `REPO_URL`)
