version: "v2.0"
name: "bk-ci前端部署【test-devx】"

on:
  manual: enabled

concurrency:
  group: frontend-test-devx

stages:
- template: frontend-stage.yml
  parameters:
    ips: "11.185.145.49"
    tag: devx
    env: test
    code-branch: test
    config-branch: integration

notices:
  - type: wework-message
