CREATE DATABASE IF NOT EXISTS `devops_ci_image` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `devops_ci_measure` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `devops_ci_notify` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `devops_ci_op` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `devops_ci_quality` DEFAULT CHARACTER SET utf8mb4;
