# 定义前端服务的upstream
set $frontend_upstream "frontend-bk-ci-frontend";

# 设置默认的ico
location = /favicon.ico {
    include gray.conf;
    header_filter_by_lua_file 'conf/lua/cors_filter.lua';
    proxy_pass http://$frontend_upstream.$tag;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location / {
    include gray.conf;
    header_filter_by_lua_file 'conf/lua/cors_filter.lua';
    set_by_lua_file $fqdn 'conf/lua/set/set_fqdn.lua';
    add_header Cache-Control no-store;
    rewrite ^/(.*) https://$fqdn/console/ redirect;
}

location ~* \.(html)$ {
    header_filter_by_lua_file 'conf/lua/cors_filter.lua';
    more_set_headers "Origin-Trial: __BKCI_ORIGIN_TRIAL__";
    include gray.conf;
    add_header Cache-Control no-store;
    error_page 404 = @fallback;
    proxy_pass http://$frontend_upstream.$tag;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_intercept_errors on;
    # 匹配所有以 html结尾的请求
}

location ~* \.(js|css|ttf)$ {
    include gray.conf;
    header_filter_by_lua_file 'conf/lua/cors_filter.lua';
    add_header Cache-Control max-age=2592000;
    error_page 404 = @fallback;
    proxy_pass http://$frontend_upstream.$tag;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_intercept_errors on;
    # 匹配所有以 js,css或tff 结尾的请求
}

location ~* /([\w-_]+)/(.*)$ {
    include gray.conf;
    header_filter_by_lua_file 'conf/lua/cors_filter.lua';
    add_header Cache-Control max-age=2592000;
    error_page 404 = @fallback;
    proxy_pass http://$frontend_upstream.$tag;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_intercept_errors on;
}

location ~* /([\w-_]+) {
    include gray.conf;
    header_filter_by_lua_file 'conf/lua/cors_filter.lua';
    add_header Cache-Control max-age=2592000;
    error_page 404 = @fallback;
    proxy_pass http://$frontend_upstream.$tag;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_intercept_errors on;
}

location @fallback {
    set_by_lua_file $use_https 'conf/lua/set/set_use_https.lua';
    set_by_lua_file $fqdn 'conf/lua/set/set_fqdn.lua';
    set_by_lua_file $devops_identity 'conf/lua/set/set_devops_identity.lua';

    set_by_lua_block $appkey {
        return config.itlogin.paasId
    }
    set_by_lua_block $url {
        local sourceUrl = ngx.escape_uri('https://' .. ngx.var.host .. ngx.var.request_uri)
        return ngx.escape_uri('https://' .. config.bkci.host .. '/oauth/tof-api/code?url=' .. sourceUrl)
    }

    if ($use_https = "1") {
        rewrite ^/(.*) https://$fqdn/$1 redirect;
    }

    if ($devops_identity = "0") {
        rewrite ^/(.*) https://passport.woa.com/modules/passport/signin.ashx?oauth=true&url=$url&appkey=$appkey;
    }

    add_header Cache-Control no-store;
    more_set_headers "Origin-Trial: __BKCI_ORIGIN_TRIAL__";
    set $subsystem "console";
    if ($uri ~* ^/(\w+)) {
        set $subsystem $1;
    }
    # 转发到前端pod处理fallback逻辑
    rewrite ^(.*)$ /$subsystem/index.html break;
    proxy_pass http://$frontend_upstream.$tag;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
