// Code generated by "translation_generator"; DO NOT EDIT.

package translation

import "github.com/nicksnyder/go-i18n/v2/i18n"

// Translations 保存当前所有的翻译
var Translations map[string][]*i18n.Message = make(map[string][]*i18n.Message)

func init() {
	Translations["en-US"] = []*i18n.Message{}
	Translations["zh-CN"] = []*i18n.Message{}
}
