export const UPDATE_PUBLIC_VAR_MODE = 'UPDATE_PUBLIC_VAR_MODE'
export const UPDATE_GROUP_DATA = 'UPDATE_GROUP_DATA'
export const UPDATE_PUBLIC_VAR_YAML = 'UPDATE_PUBLIC_VAR_YAML'
export const ADD_VARIABLE = 'ADD_VARIABLE'
export const EDIT_VARIABLE = 'EDIT_VARIABLE'
export const UPDATE_OPERATE_TYPE = 'UPDATE_OPERATE_TYPE'
export const CONSTANT = 'CONSTANT'
export const VARIABLE = 'VARIABLE'
export const OTHER = 'OTHER'

export const OPERATE_TYPE = {
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE'
}