packages:
  - "devops-*"
  - "!devops-repo"
  - bk-pipeline
  - bk-permission
  - locale
  - common-lib

allowBuilds:
  '@parcel/watcher': true
  bufferutil: false
  core-js: false
  ejs: false
  es5-ext: false
  esbuild: true
  fsevents: true
  highlight.js: false
  nx: true
  utf-8-validate: false
  vue-demi: true
  vue-echarts: true
  yorkie: false
  less: false

catalogs:
  vue2:
    vue: "~2.7.16"
    vue-loader: "~15.10.0"
    vue-i18n: "~8.18.1"
  vue3:
    vue: "~3.4.31"
    vue-i18n: "~9.1.10"
  webpack5:
    webpack: "~5.76.1"
  bkMagicVue:
    bk-magic-vue: "2.5.9-beta.9"
