# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    puts "GRADLE_ALL_APK_OUTPUT_PATHS: #{Actions.lane_context[SharedValues::GRADLE_ALL_APK_OUTPUT_PATHS]}"
    puts "GRADLE_APK_OUTPUT_PATH: #{Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
end
