USE devops_ci_metrics;
SET NAMES utf8mb4;

DROP PROCEDURE IF EXISTS ci_metrics_schema_update;

DELIMITER <CI_UBF>

CREATE PROCEDURE ci_metrics_schema_update()
BEGIN
    DECLARE db VARCHAR(100);
    SET AUTOCOMMIT = 0;
SELECT DATABASE() INTO db;

IF NOT EXISTS(SELECT 1
              FROM information_schema.COLUMNS
              WHERE TABLE_SCHEMA = db
                AND TABLE_NAME = 'T_EPLUS_PIPELINE_METRICS_DATA_DAILY'
                AND COLUMN_NAME = 'INVALID_PIPELINE_FLAG') THEN
    ALTER TABLE T_EPLUS_PIPELINE_METRICS_DATA_DAILY ADD INVALID_PIPELINE_FLAG bit(1) NULL COMMENT '是否是无效流水线（连续90天失败并且构建次数大于14）';
END IF;

IF NOT EXISTS(SELECT 1
                  FROM information_schema.statistics
                  WHERE TABLE_SCHEMA = db
                    AND TABLE_NAME = 'T_EPLUS_PIPELINE_METRICS_DATA_DAILY'
                    AND INDEX_NAME = 'INX_TEPMD_PROJECT_STATISTICS_TIME') THEN
    ALTER TABLE T_EPLUS_PIPELINE_METRICS_DATA_DAILY ADD INDEX `INX_TEPMD_PROJECT_STATISTICS_TIME` (`PROJECT_ID`,`STATISTICS_TIME`);
END IF;

COMMIT;
END <CI_UBF>
DELIMITER ;
COMMIT;
CALL ci_metrics_schema_update();
