{
 "title": "制品库JVM监控大盘",
 "description": "Dashboard for Micrometer instrumented applications",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "服务",
    "query": "show tag values from jvm_memory_used with key = \"service\""
   },
   {
    "name": "instance",
    "label": "实例",
    "query": "show tag values from jvm_memory_used with key = \"instance\" where service = '$service'"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "show tag values from jvm_memory_used with key = \"id\" where service = '$service' and instance =~ /^$instance$/ and area = 'heap'"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "show tag values from jvm_memory_used with key = \"id\" where service = '$service' and instance =~ /^$instance$/ and area = 'nonheap'"
   }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "进程启动时长",
   "type": "stat",
   "description": "JVM进程启动时长",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "process_uptime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "进程启动时间",
   "type": "stat",
   "description": "JVM进程启动时间",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "process_start_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "堆内存使用率",
   "type": "stat",
   "description": "JVM堆内存使用率",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"jvm_memory_used\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"area\" = 'heap') AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"area\" = 'heap') AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "非堆内存使用率",
   "type": "stat",
   "description": "JVM非堆内存使用率",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"jvm_memory_used\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"area\" = 'nonheap') AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"area\" = 'nonheap') AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "HTTP Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "平均请求量",
   "type": "graph",
   "description": "平均每分钟处理的请求数",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT mean(\"count\") FROM \"http_server_requests\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), \"method\" fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "平均错误数",
   "type": "graph",
   "description": "平均每分钟错误请求数",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "alias": "HTTP - 4XX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT mean(\"count\") FROM \"http_server_requests\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"status\" =~ /^4.*$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^4.*$/" }
     ]
    },
    {
     "alias": "HTTP - 5XX",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT mean(\"count\") FROM \"http_server_requests\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"status\" =~ /^5.*$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^5.*$/" }
     ]
    }
   ]
  },
  {
   "title": "平均请求耗时",
   "type": "graph",
   "description": "平均请求耗时",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "HTTP - AVG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT mean(\"sum\")/mean(\"count\") FROM \"http_server_requests\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  { "title": "JVM 内存", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "堆内存",
   "type": "graph",
   "description": "JVM堆内存使用情况",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "query": "SELECT SUM(val) FROM (SELECT mean(value) AS val FROM jvm_memory_used WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"area\" = 'heap') AND $timeFilter GROUP BY time($__interval) ,*) GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "query": "SELECT SUM(val) FROM (SELECT mean(value) AS val FROM jvm_memory_committed WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"area\" = 'heap') AND $timeFilter GROUP BY time($__interval) ,*) GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "query": "SELECT SUM(val) FROM (SELECT mean(value) AS val FROM jvm_memory_max WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"area\" = 'heap') AND $timeFilter GROUP BY time($__interval) ,*) GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    }
   ]
  },
  {
   "title": "非堆内存",
   "type": "graph",
   "description": "JVM非堆内存使用情况",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "query": "SELECT SUM(val) FROM (SELECT mean(value) AS val FROM jvm_memory_used WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval) ,*) GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "query": "SELECT SUM(val) FROM (SELECT mean(value) AS val FROM jvm_memory_committed WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval) ,*) GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "query": "SELECT SUM(val) FROM (SELECT mean(value) AS val FROM jvm_memory_max WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"area\" = 'nonheap') AND $timeFilter GROUP BY time($__interval) ,*) GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    }
   ]
  },
  {
   "title": "总内存",
   "type": "graph",
   "description": "JVM总内存使用情况",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "query": "SELECT SUM(val) FROM (SELECT mean(value) AS val FROM jvm_memory_used WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval) ,*) GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "query": "SELECT SUM(val) FROM (SELECT mean(value) AS val FROM jvm_memory_committed WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval) ,*) GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "query": "SELECT SUM(val) FROM (SELECT mean(value) AS val FROM jvm_memory_max WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval) ,*) GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    }
   ]
  },
  { "title": "JVM 负载", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU 使用率",
   "type": "graph",
   "description": "JVM系统CPU使用率",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "process",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "description": "CPU负载",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "load1m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system_load_average_1m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "cpu核数",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system_cpu_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "线程数",
   "type": "graph",
   "description": "系统线程使用情况",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "live",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_live",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "daemon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_daemon",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "各状态线程数",
   "type": "graph",
   "description": "需特别关注blocked的线程数, 这意味着线程被阻塞了, 如果线程全部是blocked状态, 则系统无法处理新请求",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_threads_states",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Logback日志数",
   "type": "graph",
   "description": "Logback日志数量",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "logback_events",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "文件描述符",
   "type": "graph",
   "description": "JVM打开的文件描述符数量",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "open",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "process_files_open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "process_files_max",
     "query": "SELECT mean(\"value\") FROM \"process_files_max\" WHERE (\"service\" = 'select tag value') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  { "title": "JVM 堆内存详细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "query": "SELECT mean(\"value\") FROM \"jvm_memory_committed\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"id\" =~ /^$jvm_memory_pool_nonheap$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id", "operator": "=~", "value": "/^$jvm_memory_pool_nonheap$/" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "query": "SELECT mean(\"value\") FROM \"jvm_memory_used\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"id\" =~ 'select tag value') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id", "operator": "=~", "value": "/^$jvm_memory_pool_heap$/" }
     ]
    }
   ]
  },
  { "title": "JVM 非堆内存详细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id", "operator": "=~", "value": "/^$jvm_memory_pool_nonheap$/" }
     ]
    },
    {
     "alias": "commited",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_committed",
     "query": "SELECT mean(\"value\") FROM \"jvm_memory_committed\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"id\" =~ /^$jvm_memory_pool_nonheap$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id", "operator": "=~", "value": "/^$jvm_memory_pool_nonheap$/" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id", "operator": "=~", "value": "/^$jvm_memory_pool_nonheap$/" }
     ]
    }
   ]
  },
  { "title": "垃圾回收(GC)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "GC 次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "alias": "$tag_action($tag_cause)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "action" ], "type": "tag" },
      { "params": [ "cause" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_pause",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "GC暂停时间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "avg $tag_action ($tag_cause)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "action" ], "type": "tag" },
      { "params": [ "cause" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_pause",
     "query": "SELECT sum(\"sum\") FROM \"jvm_gc_pause\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), \"action\", \"cause\" fill(none)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "max $tag_action ($tag_cause)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "action" ], "type": "tag" },
      { "params": [ "cause" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_pause",
     "query": "SELECT mean(\"value\") FROM \"jvm_gc_pause\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" = 'select tag value') AND $timeFilter GROUP BY time($__interval), \"action\", \"cause\" fill(none)",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "内存分配/晋升",
   "type": "graph",
   "description": "内存分配的大小, 以及从新生代晋升到老年代的内存大小",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "allocated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_memory_allocated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "promoted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "类加载", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "已加载的类的数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "loaded",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "加载类数量变化",
   "type": "graph",
   "description": "可能增加或减少, 在Java中使用一些脚本语言例如groovy时, 需要关注, 防止因为逻辑异常产生大量的类, 进而导致metaspace满, 而metaspace满会触发full gc, 如无法释放则会导致JVM hang住",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "delta-1m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_buffer_memory_used",
     "query": "SELECT mean(\"value\") FROM \"jvm_buffer_memory_used\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"id\" = 'direct') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "direct" }
     ]
    },
    {
     "alias": "capacity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_buffer_total_capacity",
     "query": "SELECT mean(\"value\") FROM \"jvm_buffer_memory_used\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"id\" = 'direct') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "direct" }
     ]
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_buffer_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "direct" }
     ]
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_buffer_memory_used",
     "query": "SELECT mean(\"value\") FROM \"jvm_buffer_memory_used\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"id\" = 'direct') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "mapped" }
     ]
    },
    {
     "alias": "capacity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_buffer_total_capacity",
     "query": "SELECT mean(\"value\") FROM \"jvm_buffer_memory_used\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"id\" = 'direct') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "mapped" }
     ]
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_buffer_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "mapped" }
     ]
    }
   ]
  }
 ]
}