/*
 * Tencent is pleased to support the open source community by making BK-CI 蓝鲸持续集成平台 available.
 *
 * Copyright (C) 2019 THL A29 Limited, a Tencent company.  All rights reserved.
 *
 * BK-CI 蓝鲸持续集成平台 is licensed under the MIT license.
 *
 * A copy of the MIT License is included in this file.
 *
 *
 * Terms of the MIT License:
 * ---------------------------------------------------
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
 * NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.tencent.devops.common.test

/**
 * 单元测试基类
 * @version 1.0
 */
abstract class BaseTest {
    /**
     * 帮助mock出带泛型的任意对象
     */
//    inline fun <reified T : Any> mock() = Mockito.mock(T::class.java)!!
//    inline fun <reified T : Any> any(): T {
//        return Mockito.any(T::class.java) ?: createInstance()
//    }
//
//    inline fun <reified T : Any> createInstance(): T {
//        return createInstance(T::class)
//    }
//
//    fun <T : Any> createInstance(kClass: KClass<T>): T {
//        return castNull()
//    }
//
//    /**
//     * Uses a quirk in the bytecode generated by Kotlin
//     * to cast [null] to a non-null type.
//     *
//     * See https://youtrack.jetbrains.com/issue/KT-8135.
//     */
//    @Suppress("UNCHECKED_CAST")
//    private fun <T> castNull(): T = null as T
}
