package com.tencent.devops.common.util.constants

const val AUTH_HEADER_DEVOPS_USER_ID = "X-DEVOPS-UID"
const val AUTH_HEADER_DEVOPS_PROJECT_ID: String = "X-DEVOPS-PROJECT-ID"
const val AUTH_HEADER_DEVOPS_ACCESS_TOKEN: String = "X-DEVOPS-ACCESS-TOKEN"
const val AUTH_HEADER_DEVOPS_BK_TICKET: String = "X-DEVOPS-BK-TICKET"
const val AUTH_HEADER_DEVOPS_TASK_ID: String = "X-DEVOPS-TASK-ID"
const val AUTH_HEADER_DEVOPS_APP_CODE: String = "X-DEVOPS-APP-CODE"
const val AUTH_HEADER_DEVOPS_USER_ID_DEFAULT_VALUE: String = "admin"
