USE devops_ci_project;
SET NAMES utf8mb4;

INSERT INTO `T_SERVICE`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (3, '代码库(Code)', 2, 'devops/codelib/', '/codelib/', 'amd', '', '/codelib/codelib.css', '/codelib/codelib.js', b'1', b'1', 'path', 'ok', 'system', '2019-06-05 17:12:47', 'system', '2019-06-05 17:12:47', b'0', '', '', 99);
INSERT INTO `T_SERVICE`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (4, '流水线(Pipeline)', 2, 'devops/pipelines/', '/pipeline/', 'iframe', '/pipeline/', '', '', b'1', b'1', 'path', 'ok', 'system', '2019-06-05 17:12:47', NULL, '2019-06-05 17:12:47', b'0', NULL, NULL, 97);
INSERT INTO `T_SERVICE`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (5, '制品库(Artifactory)', 2, 'devops/artifactory/', '/artifactory/', 'amd', '', '/artifactory/artifactory.css', '/artifactory/artifactory.js', b'1', b'1', 'path', 'disable', 'system', '2019-06-05 17:12:48', 'system', '2019-06-05 17:12:48', b'1', '', '', 96);
INSERT INTO `T_SERVICE`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (22, '凭证管理(Ticket)', 8, 'devops/ticket/', '/ticket/', 'amd', '', '/ticket/ticket.css', '/ticket/ticket.js', b'1', b'1', 'path', 'ok', 'system', '2019-06-05 17:13:26', 'system', '2019-06-05 17:13:26', b'0', '', '', 95);
INSERT INTO `T_SERVICE`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (24, '环境管理(Env)', 4, 'devops/environment/', '/environment/', 'amd', '', '/environment/environment.css', '/environment/environment.js', b'1', b'1', 'path', 'ok', 'system', '2019-06-05 17:13:27', 'system', '2019-06-05 17:13:27', b'0', '', '', 94);
INSERT INTO `T_SERVICE`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (29, '研发商店(Store)', 8, '/devops/store/', '/store/', 'amd', '', '/store/store.css', '/store/store.js', b'0', b'1', 'path', 'ok', 'system', '2019-06-05 17:13:29', 'system', '2019-06-05 17:13:29', b'0', '', '', 93);
INSERT INTO `T_SERVICE`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (27, '质量红线(Gate)', 3, '/devops/quality/', '/quality/', 'amd', '', '/quality/quality.css', '/quality/quality.js', b'1', b'1', 'path', 'disable', 'system', '2019-06-05 17:13:29', 'system', '2019-06-05 17:13:29', b'1', '', '', 92);
INSERT INTO `T_SERVICE`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (32, '代码检查(CodeCC)', 2, 'devops/codecc/', '/codecc/', 'iframe', '/codecc/', '', '', b'1', b'1', 'path', 'disable', 'system', '2019-06-05 17:12:47', NULL, '2019-06-05 17:12:47', b'1', NULL, NULL, 89);
-- INSERT INTO `T_SERVICE`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (30, '度量数据(Measure)', 2, 'devops/measure/', '/measure/', 'iframe', '/measure/', '', '', b'1', b'1', 'path', 'ok', 'system', '2019-06-05 17:12:47', NULL, '2019-06-05 17:12:47', b'0', NULL, NULL, 91);
-- INSERT INTO `T_SERVICE`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (31, '敏捷开发(Teamwork)', 1, 'devops/teamwork/', '/teamwork/', 'amd', '', '/teamwork/teamwork.css', '/teamwork/teamwork.js', b'1', b'1', 'path', 'ok', 'system', '2019-06-05 17:12:48', 'system', '2019-06-05 17:12:48', b'0', '', '', 90);


-- INSERT INTO `T_SERVICE_TYPE`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (1, '项目管理', 'system', '2019-06-05 17:13:55', 'system', '2019-06-05 17:13:55', b'0', NULL);
INSERT INTO `T_SERVICE_TYPE`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (2, '开发', 'system', '2018-12-06 20:49:24', 'system', '2018-12-06 20:49:24', b'0', NULL);
INSERT INTO `T_SERVICE_TYPE`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (3, '测试', 'system', '2019-06-05 17:13:58', 'system', '2019-06-05 17:13:58', b'0', NULL);
INSERT INTO `T_SERVICE_TYPE`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (4, '部署', 'system', '2019-06-05 17:13:59', 'system', '2019-06-05 17:13:59', b'0', NULL);
-- INSERT INTO `T_SERVICE_TYPE`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (5, '运营', 'system', '2019-06-05 17:14:00', 'system', '2019-06-05 17:14:00', b'1', NULL);
-- INSERT INTO `T_SERVICE_TYPE`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (6, '安全', 'system', '2019-06-05 17:14:01', 'system', '2019-06-05 17:14:01', b'1', NULL);
-- INSERT INTO `T_SERVICE_TYPE`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (7, '研发商店', 'system', '2019-06-05 17:14:02', 'system', '2019-06-05 17:14:02', b'0', NULL);
INSERT INTO `T_SERVICE_TYPE`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (8, '管理工具', 'system', '2019-06-05 17:14:02', 'system', '2019-06-05 17:14:02', b'0', NULL);
