USE devops_ci_project;
SET NAMES utf8mb4;

REPLACE INTO  `T_MESSAGE_CODE_DETAIL`(`ID`, `MESSAGE_CODE`, `MODULE_CODE`, `MESSAGE_DETAIL_ZH_CN`, `MESSAGE_DETAIL_ZH_TW`, `MESSAGE_DETAIL_EN`) VALUES ('028dffc92d344f9186e267418dc4839d', 'NUMBER_STYLE', '00', '只允许输入数字', '只允許輸入數字', 'Only numbers are allowed');
REPLACE INTO  `T_MESSAGE_CODE_DETAIL`(`ID`, `MESSAGE_CODE`, `MODULE_CODE`, `MESSAGE_DETAIL_ZH_CN`, `MESSAGE_DETAIL_ZH_TW`, `MESSAGE_DETAIL_EN`) VALUES ('045ff045f5f64635b8a97930c3f1bbd6', 'AUTH_STYLE', '00', '权限认证类型不正确，只允许HTTP|HTTPS|OAUTH|SSH', '權限認證類型不正確，只允許HTTP|HTTPS|OAUTH|SSH', ' The authorization type is incorrect, only HTTP|HTTPS|OAUTH|SSH is allowed');
REPLACE INTO  `T_MESSAGE_CODE_DETAIL`(`ID`, `MESSAGE_CODE`, `MODULE_CODE`, `MESSAGE_DETAIL_ZH_CN`, `MESSAGE_DETAIL_ZH_TW`, `MESSAGE_DETAIL_EN`) VALUES ('79e905a97b444171b530e8079d2310cc', 'COMMON_STYLE', '00', '非法字符', '非法字符', 'Invaild symbol');
REPLACE INTO  `T_MESSAGE_CODE_DETAIL`(`ID`, `MESSAGE_CODE`, `MODULE_CODE`, `MESSAGE_DETAIL_ZH_CN`, `MESSAGE_DETAIL_ZH_TW`, `MESSAGE_DETAIL_EN`) VALUES ('a6809287bbb74d8f8c36c024b7a664d2', 'LANGUAGE_STYLE', '00', '开发语言不正确，只允许输入java|python|nodejs|golang|c|c++|php|c#', ' 開發語言不正確，只允許輸入java|python|nodejs|golang|c|c++|php|c#', 'The development language is incorrect, only java|python|nodejs|golang|c|c++|php|c#');
REPLACE INTO  `T_MESSAGE_CODE_DETAIL`(`ID`, `MESSAGE_CODE`, `MODULE_CODE`, `MESSAGE_DETAIL_ZH_CN`, `MESSAGE_DETAIL_ZH_TW`, `MESSAGE_DETAIL_EN`) VALUES ('b60a23db2cd142599ca0f3830bae0ba5', 'EMAIL_STYLE', '00', '电子邮箱格式不正确', '電子郵箱格式不正確', 'Incorrect email format');
REPLACE INTO  `T_MESSAGE_CODE_DETAIL`(`ID`, `MESSAGE_CODE`, `MODULE_CODE`, `MESSAGE_DETAIL_ZH_CN`, `MESSAGE_DETAIL_ZH_TW`, `MESSAGE_DETAIL_EN`) VALUES ('ef3c0f5fc66442a79841cc306a713bef', 'VISIBILITY_LEVEL_STYLE', '00', 'GIT项目可视范围类型不正确，只允许输入PRIVATE|LOGIN_PUBLIC', 'GIT項目可視範圍類型不正確，只允許輸入PRIVATE|LOGIN_PUBLIC', 'The type of the visible range of the GIT project is incorrect. Only PRIVATE|LOGIN_PUBLIC is allowed');
REPLACE INTO  `T_MESSAGE_CODE_DETAIL`(`ID`, `MESSAGE_CODE`, `MODULE_CODE`, `MESSAGE_DETAIL_ZH_CN`, `MESSAGE_DETAIL_ZH_TW`, `MESSAGE_DETAIL_EN`) VALUES ('ca1eea81ea524e64b0a4f4cf651c981e', 'PRIVATE_REASON_STYLE', '00', '不开源内容不正确，只允许输入中英文、数字、部分中英文标点等，长度在2-256之间', '不開源內容不正確，只允許輸入中英文、數字、部分中英文標點等，長度在2-256之間', ' Not open source content is incorrect, only allow input of Chinese and English, numbers, some Chinese and English punctuation, etc.');
REPLACE INTO  `T_MESSAGE_CODE_DETAIL`(`ID`, `MESSAGE_CODE`, `MODULE_CODE`, `MESSAGE_DETAIL_ZH_CN`, `MESSAGE_DETAIL_ZH_TW`, `MESSAGE_DETAIL_EN`) VALUES ('80367ad62d2848f39b7a950be63fd1b7', 'SERVICE_CODE_STYLE', '00', '扩展标识必须由小写字母、数字和中划线组成，首字母必须为小写字母，长度在1-32之间', '擴展標識必須由小寫字母、數字和中劃線組成，首字母必須為小寫字母，長度在1-32之間', ' The extended logo must be composed of lowercase letters, numbers, and underscores, and the first letter must be lowercase letters');
REPLACE INTO  `T_MESSAGE_CODE_DETAIL`(`ID`, `MESSAGE_CODE`, `MODULE_CODE`, `MESSAGE_DETAIL_ZH_CN`, `MESSAGE_DETAIL_ZH_TW`, `MESSAGE_DETAIL_EN`) VALUES ('b56955b043ca448fac04001144f96f0a', 'STORE_CODE_STYLE', '00', '标识只能由大小写字母、数字和下划线组成，首字母必须为字母或者下划线，长度在1-32之间', ' 標識只能由大小寫字母、數字和下劃線組成，首字母必須為字母或者下劃線，長度在1-32之間', ' The logo can only consist of uppercase and lowercase letters, numbers and underscores, the first letter must be a letter or underscore');
REPLACE INTO  `T_MESSAGE_CODE_DETAIL`(`ID`, `MESSAGE_CODE`, `MODULE_CODE`, `MESSAGE_DETAIL_ZH_CN`, `MESSAGE_DETAIL_ZH_TW`, `MESSAGE_DETAIL_EN`) VALUES ('333d5d9cef9e4b6d8af16e01b5ba623a', 'STORE_NAME_STYLE', '00', '名称只能由中文、大小字母、数字和下划线组成，长度在1-32之间', '名稱只能由中文、大小字母、數字和下劃線組成，長度在1-32之間', 'The name can only be composed of Chinese, capital letters, numbers, and underscores');
REPLACE INTO  `T_MESSAGE_CODE_DETAIL`(`ID`, `MESSAGE_CODE`, `MODULE_CODE`, `MESSAGE_DETAIL_ZH_CN`, `MESSAGE_DETAIL_ZH_TW`, `MESSAGE_DETAIL_EN`) VALUES ('00b5b76ff0844ce3adb84ed8dd43b657', '2100015', '00', '{0}参数校验错误: {1}', ' {0}參數校驗錯誤: {1}', '{0} Parameter check error: {1}');

