USE devops_ci_process;
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `T_PIPELINE_INFO_VERSION` (
  `PIPELINE_ID` varchar(34) NOT NULL DEFAULT '',
  `PROJECT_ID` varchar(64) NOT NULL,
  `PIPELINE_NAME` varchar(255) NOT NULL,
  `PIPELINE_DESC` varchar(255) DEFAULT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '1',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATOR` varchar(64) NOT NULL,
  `UPDATE_TIME` timestamp NULL DEFAULT NULL,
  `LAST_MODIFY_USER` varchar(64) NOT NULL,
  `CHANNEL` varchar(32) DEFAULT NULL,
  `MANUAL_STARTUP` int(11) DEFAULT '1',
  `ELEMENT_SKIP` int(11) DEFAULT '0',
  `TASK_COUNT` int(11) DEFAULT '0',
  `DELETE` bit(1) DEFAULT b'0',
  KEY `PROJECT_ID` (`PROJECT_ID`,`PIPELINE_ID`,`VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `T_PIPELINE_LABEL_PIPELINE_VERSION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PIPELINE_ID` varchar(34) NOT NULL,
  `LABEL_ID` bigint(20) NOT NULL,
  `CREATE_TIME` datetime NOT NULL,
  `CREATE_USER` varchar(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PIPELINE_ID` (`PIPELINE_ID`,`LABEL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `T_PIPELINE_MODEL_TASK_VERSION` (
  `PIPELINE_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '1',
  `STAGE_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  `CONTAINER_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  `TASK_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  `TASK_NAME` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL,
  `CLASS_TYPE` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  `TASK_ATOM` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL,
  `TASK_SEQ` int(11) DEFAULT '1',
  `TASK_PARAMS` mediumtext COLLATE utf8mb4_bin,
  `OS` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `ADDITIONAL_OPTIONS` mediumtext CHARACTER SET utf8mb4,
  `ATOM_CODE` varchar(32) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  KEY `STAT_PROJECT_RUN` (`PROJECT_ID`),
  KEY `PROJECT_PIPELINE` (`PROJECT_ID`,`PIPELINE_ID`),
  KEY `ATOM_CODE` (`ATOM_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `T_PIPELINE_RESOURCE_VERSION` (
  `PIPELINE_ID` varchar(34) NOT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '1',
  `MODEL` mediumtext,
  `CREATOR` varchar(64) DEFAULT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `SUCCESS_WECHAT_GROUP_MARKDOWN_FLAG` bit(1) NOT NULL DEFAULT b'0',
  `FAIL_WECHAT_GROUP_MARKDOWN_FLAG` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`PIPELINE_ID`,`VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `T_PIPELINE_SETTING_VERSION` (
  `PIPELINE_ID` varchar(34) NOT NULL,
  `DESC` varchar(1024) DEFAULT NULL,
  `RUN_TYPE` int(11) DEFAULT NULL,
  `NAME` varchar(64) DEFAULT NULL,
  `SUCCESS_RECEIVER` mediumtext,
  `FAIL_RECEIVER` mediumtext,
  `SUCCESS_GROUP` mediumtext,
  `FAIL_GROUP` mediumtext,
  `SUCCESS_TYPE` varchar(32) DEFAULT NULL,
  `FAIL_TYPE` varchar(32) DEFAULT NULL,
  `PROJECT_ID` varchar(64) DEFAULT NULL,
  `SUCCESS_WECHAT_GROUP_FLAG` bit(1) NOT NULL DEFAULT b'0',
  `SUCCESS_WECHAT_GROUP` varchar(1024) NOT NULL DEFAULT '',
  `FAIL_WECHAT_GROUP_FLAG` bit(1) NOT NULL DEFAULT b'0',
  `FAIL_WECHAT_GROUP` varchar(1024) NOT NULL DEFAULT '',
  `RUN_LOCK_TYPE` int(11) DEFAULT '1',
  `SUCCESS_DETAIL_FLAG` bit(1) DEFAULT b'0',
  `FAIL_DETAIL_FLAG` bit(1) DEFAULT b'0',
  `SUCCESS_CONTENT` longtext,
  `FAIL_CONTENT` longtext,
  `WAIT_QUEUE_TIME_SECOND` int(11) DEFAULT '7200',
  `MAX_QUEUE_SIZE` int(11) DEFAULT '10',
  `IS_TEMPLATE` bit(1) DEFAULT b'0',
  `VERSION` int(11) NOT NULL DEFAULT '1',
  `SUCCESS_WECHAT_GROUP_MARKDOWN_FLAG` bit(1) NOT NULL DEFAULT b'0',
  `FAIL_WECHAT_GROUP_MARKDOWN_FLAG` bit(1) NOT NULL DEFAULT b'0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `T_PIPELINE_USER_VERSION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PIPELINE_ID` varchar(34) NOT NULL,
  `CREATE_TIME` datetime NOT NULL,
  `UPDATE_TIME` datetime NOT NULL,
  `CREATE_USER` varchar(64) NOT NULL,
  `UPDATE_USER` varchar(64) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=447 DEFAULT CHARSET=utf8mb4;