USE devops_ci_project;
SET NAMES utf8mb4;

INSERT INTO `t_service`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (3, '代码库(Code)', 2, 'devops/codelib/', '/codelib/', 'amd', '', '/codelib/codelib.css', '/codelib/codelib.js', b'1', b'1', 'path', 'ok', 'system', '2019-06-05 17:12:47', 'system', '2019-06-05 17:12:47', b'0', '', '', NULL);
INSERT INTO `t_service`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (4, '流水线(Pipeline)', 2, 'devops/pipelines/', '/pipeline/', 'iframe', '/pipeline/', '', '', b'1', b'1', 'path', 'ok', 'system', '2019-06-05 17:12:47', NULL, '2019-06-05 17:12:47', b'0', NULL, NULL, NULL);
INSERT INTO `t_service`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (5, '版本仓库(Artifactory)', 2, 'devops/artifactory/', '/artifactory/', 'amd', '', '/artifactory/artifactory.css', '/artifactory/artifactory.js', b'1', b'1', 'path', 'disable', 'system', '2019-06-05 17:12:48', 'system', '2019-06-05 17:12:48', b'1', '', '', NULL);
INSERT INTO `t_service`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (22, '凭证管理(Ticket)', 2, 'devops/ticket/', '/ticket/', 'amd', '', '/ticket/ticket.css', '/ticket/ticket.js', b'1', b'1', 'path', 'ok', 'system', '2019-06-05 17:13:26', 'system', '2019-06-05 17:13:26', b'0', '', '', NULL);
INSERT INTO `t_service`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (24, '环境管理(Env)', 2, 'devops/environment/', '/environment/', 'amd', '', '/environment/environment.css', '/environment/environment.js', b'1', b'1', 'path', 'ok', 'system', '2019-06-05 17:13:27', 'system', '2019-06-05 17:13:27', b'0', '', '', NULL);
INSERT INTO `t_service`(`id`, `name`, `service_type_id`, `link`, `link_new`, `inject_type`, `iframe_url`, `css_url`, `js_url`, `show_project_list`, `show_nav`, `project_id_type`, `status`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `gray_css_url`, `gray_js_url`, `weight`) VALUES (29, '研发商店(Store)', 2, '/devops/store/', '/store/', 'amd', '', '/store/store.css', '/store/store.js', b'0', b'1', 'path', 'ok', 'system', '2019-06-05 17:13:29', 'system', '2019-06-05 17:13:29', b'0', '', '', NULL);

INSERT INTO `t_service_type`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (1, '需求', 'system', '2019-06-05 17:13:55', 'system', '2019-06-05 17:13:55', b'1', NULL);
INSERT INTO `t_service_type`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (2, '开发', 'system', '2018-12-06 20:49:24', 'system', '2018-12-06 20:49:24', b'0', NULL);
INSERT INTO `t_service_type`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (3, '测试', 'system', '2019-06-05 17:13:58', 'system', '2019-06-05 17:13:58', b'1', NULL);
INSERT INTO `t_service_type`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (4, '部署', 'system', '2019-06-05 17:13:59', 'system', '2019-06-05 17:13:59', b'1', NULL);
INSERT INTO `t_service_type`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (5, '运营', 'system', '2019-06-05 17:14:00', 'system', '2019-06-05 17:14:00', b'1', NULL);
INSERT INTO `t_service_type`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (6, '安全', 'system', '2019-06-05 17:14:01', 'system', '2019-06-05 17:14:01', b'1', NULL);
INSERT INTO `t_service_type`(`id`, `title`, `created_user`, `created_time`, `updated_user`, `updated_time`, `deleted`, `weight`) VALUES (7, '管理工具', 'system', '2019-06-05 17:14:02', 'system', '2019-06-05 17:14:02', b'1', NULL);
