USE devops_ci_ticket;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for T_CERT
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_CERT` (
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `CERT_ID` varchar(128) NOT NULL COMMENT '证书ID',
  `CERT_USER_ID` varchar(64) NOT NULL COMMENT '证书用户ID',
  `CERT_TYPE` varchar(32) NOT NULL COMMENT '证书类型',
  `CERT_REMARK` varchar(128) NOT NULL COMMENT '证书备注',
  `CERT_P12_FILE_NAME` varchar(128) NOT NULL COMMENT '证书 p12 文件名称',
  `CERT_P12_FILE_CONTENT` blob NOT NULL COMMENT '证书 p12 文件内容',
  `CERT_MP_FILE_NAME` varchar(128) NOT NULL COMMENT '证书 mp 文件名称',
  `CERT_MP_FILE_CONTENT` blob NOT NULL COMMENT '证书 mp 文件内容',
  `CERT_JKS_FILE_NAME` varchar(128) NOT NULL COMMENT '证书 jks 文件名称',
  `CERT_JKS_FILE_CONTENT` blob NOT NULL COMMENT '证书 jsk 文件内容',
  `CERT_JKS_ALIAS` varchar(128) DEFAULT NULL COMMENT '证书 jsk 别名',
  `CERT_JKS_ALIAS_CREDENTIAL_ID` varchar(64) DEFAULT NULL COMMENT '证书 jks 凭据ID',
  `CERT_DEVELOPER_NAME` varchar(128) NOT NULL COMMENT '证书 开发者名称',
  `CERT_TEAM_NAME` varchar(128) NOT NULL COMMENT '证书 团队名称',
  `CERT_UUID` varchar(64) NOT NULL COMMENT '证书 uuid',
  `CERT_EXPIRE_DATE` datetime DEFAULT NULL COMMENT '证书 过期时间',
  `CERT_CREATE_TIME` datetime DEFAULT NULL COMMENT '证书 创建时间',
  `CERT_UPDATE_TIME` datetime DEFAULT NULL COMMENT '证书 更新时间',
  `CREDENTIAL_ID` varchar(64) DEFAULT NULL COMMENT '凭证ID',
  PRIMARY KEY (`PROJECT_ID`,`CERT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证信息表';

-- ----------------------------
-- Table structure for T_CERT_ENTERPRISE
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_CERT_ENTERPRISE` (
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `CERT_ID` varchar(32) NOT NULL COMMENT '证书ID',
  `CERT_MP_FILE_NAME` varchar(128) NOT NULL COMMENT '证书 mp 文件名称',
  `CERT_MP_FILE_CONTENT` blob NOT NULL COMMENT '证书 mp 文件内容',
  `CERT_DEVELOPER_NAME` varchar(128) NOT NULL COMMENT '证书 开发者名称',
  `CERT_TEAM_NAME` varchar(128) NOT NULL COMMENT '证书 团队名称',
  `CERT_UUID` varchar(64) NOT NULL COMMENT '证书 uuid',
  `CERT_UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `CERT_EXPIRE_DATE` datetime NOT NULL DEFAULT '2019-08-01 00:00:00' COMMENT '证书 过期时间',
  `CERT_CREATE_TIME` datetime NOT NULL DEFAULT '2019-08-01 00:00:00' COMMENT '证书 创建时间',
  PRIMARY KEY (`PROJECT_ID`,`CERT_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='企业证书表';

-- ----------------------------
-- Table structure for T_CERT_TLS
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_CERT_TLS` (
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `CERT_ID` varchar(32) NOT NULL COMMENT '证书ID',
  `CERT_SERVER_CRT_FILE_NAME` varchar(128) NOT NULL COMMENT '服务器crt证书名',
  `CERT_SERVER_CRT_FILE` blob NOT NULL COMMENT 'Base64编码的加密后的证书内容',
  `CERT_SERVER_KEY_FILE_NAME` varchar(128) NOT NULL COMMENT '服务器key证书名',
  `CERT_SERVER_KEY_FILE` blob NOT NULL COMMENT 'Base64编码的加密后的证书内容',
  `CERT_CLIENT_CRT_FILE_NAME` varchar(128) DEFAULT NULL COMMENT '客户端crt证书名',
  `CERT_CLIENT_CRT_FILE` blob COMMENT 'Base64编码的加密后的证书内容',
  `CERT_CLIENT_KEY_FILE_NAME` varchar(128) DEFAULT NULL COMMENT '客户端key证书名',
  `CERT_CLIENT_KEY_FILE` blob COMMENT 'Base64编码的加密后的证书内容',
  `CERT_CREATE_TIME` timestamp NOT NULL DEFAULT '2019-08-01 00:00:00' COMMENT '证书创建时间',
  `CERT_UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '证书更新时间',
  PRIMARY KEY (`PROJECT_ID`,`CERT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='TLS证书表';

-- ----------------------------
-- Table structure for T_CREDENTIAL
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_CREDENTIAL` (
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `CREDENTIAL_ID` varchar(64) NOT NULL COMMENT '凭据 ID',
  `CREDENTIAL_NAME` VARCHAR(64) COMMENT '凭据名称',
  `CREDENTIAL_USER_ID` varchar(64) NOT NULL DEFAULT '' COMMENT '凭据用户ID',
  `CREDENTIAL_TYPE` varchar(64) NOT NULL COMMENT '凭据类型',
  `CREDENTIAL_REMARK` text COMMENT '凭据备注',
  `CREDENTIAL_V1` text NOT NULL COMMENT '凭据内容',
  `CREDENTIAL_V2` text COMMENT '凭据内容',
  `CREDENTIAL_V3` text COMMENT '凭据内容',
  `CREDENTIAL_V4` text COMMENT '凭据内容',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_TIME` datetime NOT NULL COMMENT '更新时间',
  `UPDATE_USER` VARCHAR(64) COMMENT '修改人',
  `ALLOW_ACROSS_PROJECT` bit(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`PROJECT_ID`,`CREDENTIAL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证表';

SET FOREIGN_KEY_CHECKS = 1;
