USE devops_ci_auth;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for T_LOG_INDICES
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_AUTH_GROUP_INFO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主健ID',
  `GROUP_NAME` VARCHAR(32) NOT NULL DEFAULT '""' COMMENT '用户组名称',
  `GROUP_CODE` VARCHAR(32) NOT NULL COMMENT '用户组标识 默认用户组标识一致',
  `GROUP_TYPE` BIT(1) NOT NULL COMMENT '用户组类型 0默认分组',
  `PROJECT_CODE` VARCHAR(64) NOT NULL DEFAULT '""' COMMENT '用户组所属项目',
  `IS_DELETE` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除 0 可用 1删除',
  `CREATE_USER` VARCHAR(64) NOT NULL DEFAULT '""' COMMENT '添加人',
  `UPDATE_USER` VARCHAR(64) DEFAULT NULL COMMENT '修改人',
  `CREATE_TIME` DATETIME(3) NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` DATETIME(3) DEFAULT NULL COMMENT '修改时间',
  `DISPLAY_NAME` VARCHAR(32) DEFAULT NULL COMMENT '用户组别名',
  `RELATION_ID` VARCHAR(32) DEFAULT NULL COMMENT '关联系统ID',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `GROUP_NAME+PROJECT_CODE` (`GROUP_NAME`,`PROJECT_CODE`),
  KEY `PROJECT_CODE` (`PROJECT_CODE`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='用户组信息表';

CREATE TABLE IF NOT EXISTS `T_AUTH_GROUP_PERSSION` (
  `ID` varchar(64) NOT NULL COMMENT '主健ID',
  `AUTH_ACTION` varchar(64) NOT NULL DEFAULT '""' COMMENT '权限动作',
  `GROUP_CODE` varchar(64) NOT NULL DEFAULT '""' COMMENT '用户组编号 默认7个内置组编号固定 自定义组编码随机',
  `CREATE_USER` varchar(64) NOT NULL DEFAULT '""' COMMENT '创建人',
  `UPDATE_USER` varchar(64) DEFAULT NULL COMMENT '修改人',
  `CREATE_TIME` datetime(3) NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime(3) DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

CREATE TABLE IF NOT EXISTS `T_AUTH_GROUP_USER` (
  `ID` varchar(64) NOT NULL COMMENT '主键ID',
  `USER_ID` varchar(64) NOT NULL DEFAULT '""' COMMENT '用户ID',
  `GROUP_ID` varchar(64) NOT NULL DEFAULT '""' COMMENT '用户组ID',
  `CREATE_USER` varchar(64) NOT NULL DEFAULT '""' COMMENT '添加用户',
  `CREATE_TIME` datetime(3) NOT NULL COMMENT '添加时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

CREATE TABLE IF NOT EXISTS `T_AUTH_STRATEGY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '策略主键ID',
  `STRATEGY_NAME` varchar(32) NOT NULL COMMENT '策略名称',
  `STRATEGY_BODY` varchar(2000) NOT NULL COMMENT '策略内容',
  `IS_DELETE` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除 0未删除 1删除',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `CREATE_USER` varchar(32) NOT NULL COMMENT '创建人',
  `UPDATE_USER` varchar(32) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='权限策略表';

CREATE TABLE IF NOT EXISTS `T_AUTH_MANAGER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `NAME` varchar(32) NOT NULL COMMENT '名称',
  `ORGANIZATION_ID` int(11) NOT NULL COMMENT '组织ID',
  `LEVEL` int(11) NOT NULL COMMENT '层级ID',
  `STRATEGYID` int(11) NOT NULL COMMENT '权限策略ID',
  `IS_DELETE` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',
  `CREATE_USER` varchar(11) NOT NULL DEFAULT '""' COMMENT '创建用户',
  `UPDATE_USER` varchar(11) DEFAULT '""' COMMENT '修改用户',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='管理员策略表';

CREATE TABLE IF NOT EXISTS `T_AUTH_MANAGER_USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `USER_ID` varchar(64) NOT NULL COMMENT '用户ID',
  `MANAGER_ID` int(11) NOT NULL COMMENT '管理员权限ID',
  `START_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '权限生效起始时间',
  `END_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '权限生效结束时间',
  `CREATE_USER` varchar(64) NOT NULL COMMENT '创建用户',
  `UPDATE_USER` varchar(64) DEFAULT NULL COMMENT '修改用户',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_ID+MANGER_ID` (`USER_ID`,`MANAGER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='管理员用户表(只存有效期内的用户)';

CREATE TABLE IF NOT EXISTS `T_AUTH_MANAGER_USER_HISTORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `USER_ID` varchar(64) NOT NULL COMMENT '用户ID',
  `MANAGER_ID` int(11) NOT NULL COMMENT '管理员权限ID',
  `START_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '权限生效起始时间',
  `END_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '权限生效结束时间',
  `CREATE_USER` varchar(64) NOT NULL COMMENT '创建用户',
  `UPDATE_USER` varchar(64) DEFAULT NULL COMMENT '修改用户',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  KEY `MANGER_ID` (`MANAGER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='管理员用户历史表';

CREATE TABLE IF NOT EXISTS `T_AUTH_MANAGER_WHITELIST` (
   `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
   `MANAGER_ID` int(11) NOT NULL COMMENT '管理策略ID',
   `USER_ID` varchar(64) NOT NULL COMMENT '用户ID',
   PRIMARY KEY (`ID`),
   KEY `idx_manager` (`MANAGER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='管理员自助申请表名单表';

CREATE TABLE IF NOT EXISTS `T_AUTH_IAM_CALLBACK` (
   `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
   `GATEWAY` varchar(255) NOT NULL DEFAULT '""' COMMENT '目标服务网关',
   `PATH` varchar(1024) NOT NULL DEFAULT '""' COMMENT '目标接口路径',
   `DELETE_FLAG` bit(1) DEFAULT b'0' COMMENT '是否删除 true-是 false-否',
   `RESOURCE` varchar(32) NOT NULL DEFAULT '""' COMMENT '资源类型',
   `SYSTEM` varchar(32) NOT NULL DEFAULT '""' COMMENT '接入系统',
   PRIMARY KEY (`ID`),
   UNIQUE INDEX `UNIQ_RESOURCE` (`RESOURCE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IAM回调地址';

CREATE TABLE IF NOT EXISTS `T_AUTH_USER_BLACKLIST` (
   `ID` int(11) NOT NULL AUTO_INCREMENT,
   `USER_ID` varchar(32) NOT NULL COMMENT '用户ID',
   `REMARK` varchar(255) NOT NULL COMMENT '拉黑原因',
   `CREATE_TIME` datetime NOT NULL COMMENT '拉黑时间',
   `STATUS` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否生效 1生效 0不生效',
   PRIMARY KEY (`ID`),
   KEY `bk_userId` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `T_AUTH_MANAGER_APPROVAL`
(
    `ID`           int(11)                             NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `USER_ID`      varchar(64)                         NOT NULL COMMENT '用户ID',
    `MANAGER_ID`   int                                 NOT NULL COMMENT '管理员权限ID',
    `EXPIRED_TIME` timestamp                           NOT NULL COMMENT '权限过期时间',
    `START_TIME`   timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '审批单生效时间',
    `END_TIME`     timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '审批单失效时间',
    `STATUS`       int(2)                              NOT NULL COMMENT '发送状态 0-审核流程中 ,1-用户拒绝续期,2-用户同意续期,3-审批人拒绝续期，4-审批人同意续期',
    `CREATE_TIME`  timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    `UPDATE_TIME`  timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间',
    INDEX `IDX_USER_ID` (`USER_ID`),
    INDEX `IDX_MANAGER_ID` (`MANAGER_ID`),
    PRIMARY KEY (`ID`)
) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4 COMMENT '蓝盾超级管理员权限续期审核表';

CREATE TABLE IF NOT EXISTS `T_AUTH_USER_INFO`  (
   `ID` int NOT NULL AUTO_INCREMENT,
   `userId` varchar(255) NOT NULL COMMENT '用户ID',
   `email` varchar(255) NULL COMMENT '邮箱',
   `phone` varchar(32) NULL COMMENT '手机号',
   `create_time` datetime NOT NULL COMMENT '注册时间',
   `user_type` int NOT NULL COMMENT '用户类型 0.页面注册 1.GitHub 2.Gitlab',
   `last_login_time` datetime NULL COMMENT '最后登陆时间',
  `user_status` int NOT NULL COMMENT '用户状态,0--正常,1--冻结',
   PRIMARY KEY (`ID`),
   UNIQUE INDEX `bk_user`(`userId`, `user_type`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='账号信息表';

CREATE TABLE IF NOT EXISTS `T_AUTH_TEMPORARY_VERIFY_RECORD`
(
    `USER_ID`          varchar(64)                        not null comment '用户ID',
    `PROJECT_CODE`     varchar(64)                        not null comment '项目ID',
    `RESOURCE_TYPE`    varchar(64)                        not null comment '资源类型',
    `RESOURCE_CODE`    varchar(255)                       not null comment '资源ID',
    `ACTION`           varchar(64)                        not null comment '操作ID',
    `VERIFY_RESULT`    bit                                not null comment '鉴权结果',
    `LAST_VERIFY_TIME` datetime default CURRENT_TIMESTAMP not null comment '最后鉴权时间',
    primary key (USER_ID, PROJECT_CODE, RESOURCE_TYPE, RESOURCE_CODE, ACTION)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '迁移-鉴权记录表';

CREATE TABLE IF NOT EXISTS `T_AUTH_ACTION` (
	`ACTION` varchar(64) NOT NULL COMMENT '操作ID',
	`RESOURCE_TYPE` varchar(64) NOT NULL COMMENT '蓝盾-关联资源类型',
	`RELATED_RESOURCE_TYPE` varchar(64) NOT NULL COMMENT 'IAM-关联资源类型',
	`ACTION_NAME` varchar(64) NOT NULL COMMENT '操作名称',
	`ENGLISH_NAME` varchar(64) DEFAULT NULL COMMENT '动作英文名称',
	`CREATE_USER` varchar(32) DEFAULT NULL COMMENT '创建者',
	`CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
	`DELETE` bit(1) DEFAULT NULL COMMENT '是否删除',
	`ACTION_TYPE` varchar(32) DEFAULT NULL COMMENT '操作类型',
	PRIMARY KEY (`ACTION`),
	UNIQUE INDEX `UNI_INX_RESOURCE_TYPE_ACTION_ID` (`RESOURCE_TYPE`, `ACTION`)
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT '权限操作表';

CREATE TABLE IF NOT EXISTS `T_AUTH_RESOURCE_TYPE` (
    `ID` int(11) NOT NULL COMMENT 'ID',
    `RESOURCE_TYPE` varchar(64) NOT NULL  COMMENT '资源类型',
    `NAME` varchar(64) NOT NULL  COMMENT '资源名称',
    `ENGLISH_NAME` varchar(64) DEFAULT NULL  COMMENT '资源英文名称',
    `DESC` varchar(255) NOT NULL  COMMENT '资源描述',
    `ENGLISH_DESC` varchar(255) DEFAULT NULL  COMMENT '资源英文描述',
    `PARENT` varchar(255) DEFAULT NULL  COMMENT '父类资源',
    `SYSTEM` varchar(255) NOT NULL  COMMENT '所属系统',
    `CREATE_USER` varchar(32) NOT NULL  COMMENT '创建者',
    `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '创建时间',
    `UPDATE_USER` varchar(32) DEFAULT NULL  COMMENT '更新者',
    `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '修改时间',
    `DELETE` bit(1) DEFAULT NULL  COMMENT '是否删除',
    UNIQUE KEY `ID` (`ID`),
    PRIMARY KEY (`RESOURCE_TYPE`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='权限资源类型表';

CREATE TABLE IF NOT EXISTS T_AUTH_RESOURCE (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	`PROJECT_CODE` varchar(32) NOT NULL COMMENT '项目ID',
	`RESOURCE_TYPE` varchar(32) NOT NULL COMMENT '资源类型',
	`RESOURCE_CODE` varchar(255) COLLATE utf8mb4_bin NOT NULL COMMENT '资源ID',
	`RESOURCE_NAME` varchar(255) NOT NULL COMMENT '资源名',
	`IAM_RESOURCE_CODE` varchar(32) NOT NULL COMMENT 'IAM资源ID',
	`ENABLE` bit(1) NOT NULL DEFAULT b'0' COMMENT '开启权限管理,0-不启用,1-启用',
	`RELATION_ID` varchar(32) NOT NULL COMMENT '关联的IAM分级管理员ID',
	`CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	`CREATE_USER` varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
	`UPDATE_USER` varchar(64) NOT NULL DEFAULT '' COMMENT '修改人',
	PRIMARY KEY (`ID`),
	UNIQUE KEY `IDX_PROJECT_RESOURCE` (`PROJECT_CODE`, `RESOURCE_TYPE`, `RESOURCE_CODE`),
	UNIQUE KEY `IDX_PROJECT_IAM_RESOURCE` (`PROJECT_CODE`, `RESOURCE_TYPE`, `IAM_RESOURCE_CODE`),
    INDEX `RESOURCE_TYPE_UPDATE_TIME_IDX` (`RESOURCE_TYPE`,`UPDATE_TIME`)
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT '资源表';

CREATE TABLE IF NOT EXISTS T_AUTH_RESOURCE_GROUP (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	`PROJECT_CODE` varchar(32) NOT NULL COMMENT '项目ID',
	`RESOURCE_TYPE` varchar(32) NOT NULL COMMENT '资源类型',
	`RESOURCE_CODE` varchar(255) COLLATE utf8mb4_bin NOT NULL COMMENT '资源ID',
	`RESOURCE_NAME` varchar(255) NOT NULL COMMENT '资源名',
	`IAM_RESOURCE_CODE` varchar(32) NOT NULL COMMENT 'IAM资源ID',
	`GROUP_CODE` varchar(32) NOT NULL COMMENT '用户组标识',
	`GROUP_NAME` varchar(255) NOT NULL COMMENT '用户组名称',
	`DEFAULT_GROUP` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否为默认组,0-非默认组,1-默认组',
	`RELATION_ID` varchar(32) NOT NULL COMMENT '关联的IAM组ID',
	`CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	`DESCRIPTION` varchar(512) DEFAULT NULL COMMENT '用户组描述',
    `IAM_TEMPLATE_ID` int(20) DEFAULT NULL COMMENT '人员模板ID',
	PRIMARY KEY (`ID`),
	UNIQUE KEY `UNIQ_PROJECT_RESOURCE` (`PROJECT_CODE`, `RESOURCE_TYPE`, `RESOURCE_CODE`, `GROUP_NAME`)
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT '资源关联用户组表';

CREATE TABLE IF NOT EXISTS T_AUTH_RESOURCE_GROUP_CONFIG (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	`RESOURCE_TYPE` varchar(32) NOT NULL COMMENT '资源类型',
	`GROUP_CODE` varchar(32) NOT NULL COMMENT '用户组标识',
	`GROUP_NAME` varchar(32) NOT NULL COMMENT '用户组名称',
	`CREATE_MODE` bit NOT NULL DEFAULT b'0' COMMENT '创建模式,0-开启时创建,1-启用权限管理时创建',
    `GROUP_TYPE` int(2) NOT NULL DEFAULT 0 COMMENT '用户组类型 0-默认组 1-自定义组',
	`DESCRIPTION` text DEFAULT NULL COMMENT '用户组描述',
	`AUTHORIZATION_SCOPES` mediumtext NOT NULL COMMENT '用户组授权范围',
	`ACTIONS` text DEFAULT NULL COMMENT '用户组拥有的资源操作',
	`CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`ID`),
	UNIQUE KEY `IDX_RESOURCE_TYPE_GROUP_CODE` (`RESOURCE_TYPE`, `GROUP_CODE`)
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT '资源用户组配置表';

CREATE TABLE IF NOT EXISTS `T_AUTH_ITSM_CALLBACK` (
	`ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
	`APPLY_ID` int(11) NOT NULL COMMENT '权限中心申请单ID',
	`SN` varchar(64) NOT NULL COMMENT 'ITSM申请单号',
	`ENGLISH_NAME` varchar(64) NOT NULL COMMENT '项目英文名',
	`CALLBACK_ID` varchar(32) NOT NULL COMMENT '权限中心审批单ID',
	`APPLICANT` varchar(32) NOT NULL COMMENT '申请人',
	`APPROVER` varchar(32) DEFAULT NULL COMMENT '最后审批人',
	`APPROVE_RESULT` bit(1) DEFAULT NULL COMMENT '审批结果，0-审批拒绝，1-审批成功',
	`UPDATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '修改时间',
	`CREATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
	PRIMARY KEY (`ID`),
	UNIQUE KEY `UNIQ_SN` (`SN`)
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT '权限itsm回调表';

CREATE TABLE IF NOT EXISTS T_AUTH_MIGRATION(
    `PROJECT_CODE` varchar(32) not null comment '项目ID',
    `STATUS` int(10) DEFAULT '0' COMMENT '迁移状态, 0-迁移中,1-迁移成功,2-迁移失败',
    `BEFORE_GROUP_COUNT` int default 0 comment '迁移前用户组数',
    `AFTER_GROUP_COUNT` int default 0 comment '迁移后用户组数',
    `RESOURCE_COUNT` text null comment '迁移后资源数和资源用户组数',
    `START_TIME` datetime NULL COMMENT '开始时间',
    `END_TIME` datetime NULL COMMENT '结束时间',
    `TOTAL_TIME` bigint null comment '总耗时',
    `ERROR_MESSAGE` text DEFAULT NULL COMMENT '错误信息',
    `ROUTER_TAG` varchar(32) DEFAULT NULL COMMENT '迁移项目的网关路由tags',
    `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`PROJECT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权限迁移';

CREATE TABLE IF NOT EXISTS `T_AUTH_MONITOR_SPACE` (
    `PROJECT_CODE` varchar(32) not null comment '项目ID',
    `SPACE_BIZ_ID` bigint(20) NOT NULL  COMMENT '监控空间业务ID',
    `SPACE_UID` varchar(64) NOT NULL  COMMENT '监控空间ID',
    `CREATOR` varchar(32) not null comment '创建人',
    `UPDATE_USER` varchar(32) DEFAULT NULL  COMMENT '更新者',
    `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
    `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`PROJECT_CODE`,`SPACE_BIZ_ID`)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT= '蓝盾监控空间权限表';

CREATE TABLE IF NOT EXISTS `T_AUTH_OAUTH2_CLIENT_DETAILS` (
    `CLIENT_ID` VARCHAR(32) NOT NULL COMMENT '客户端标识',
    `CLIENT_SECRET` VARCHAR(64) NOT NULL COMMENT '客户端秘钥',
    `CLIENT_NAME` VARCHAR(255) NOT NULL COMMENT '客户端名称',
    `SCOPE` MEDIUMTEXT DEFAULT NULL COMMENT '授权操作范围',
    `ICON` MEDIUMTEXT DEFAULT NULL COMMENT '图标',
    `AUTHORIZED_GRANT_TYPES` VARCHAR(64) NOT NULL  COMMENT '授权模式',
    `WEB_SERVER_REDIRECT_URI` MEDIUMTEXT DEFAULT NULL COMMENT '跳转链接',
    `ACCESS_TOKEN_VALIDITY` BIGINT(20)  NOT NULL COMMENT 'access_token有效时间',
    `REFRESH_TOKEN_VALIDITY` BIGINT(20) DEFAULT NULL COMMENT 'refresh_token有效时间',
    `CREATE_USER` VARCHAR(32) NOT NULL DEFAULT '""' COMMENT '创建人',
    `UPDATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '修改人',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`CLIENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户端信息表';

CREATE TABLE IF NOT EXISTS `T_AUTH_OAUTH2_CODE` (
    `CLIENT_ID` VARCHAR(32) NOT NULL COMMENT '客户端标识',
    `CODE` VARCHAR(64)  NOT NULL COMMENT '授权码',
    `USER_NAME` VARCHAR(32) NOT NULL COMMENT '用户名',
    `EXPIRED_TIME` BIGINT(20) NOT NULL COMMENT '过期时间',
    `SCOPE_ID` INT NOT NULL  COMMENT '授权范围ID',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX `IDX_CODE` (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权码表';

CREATE TABLE IF NOT EXISTS `T_AUTH_OAUTH2_ACCESS_TOKEN` (
    `ACCESS_TOKEN` VARCHAR(64) NOT NULL COMMENT 'ACCESS_TOKEN',
    `CLIENT_ID` VARCHAR(32) NOT NULL COMMENT '客户端ID',
    `USER_NAME` VARCHAR(32) DEFAULT NULL COMMENT '登录的用户名，客户端模式该值为空',
    `PASS_WORD` VARCHAR(64) DEFAULT NULL COMMENT '用于密码模式',
    `GRANT_TYPE` VARCHAR(32) NOT NULL  COMMENT '授权模式',
    `EXPIRED_TIME` BIGINT(20) NOT NULL COMMENT '过期时间',
    `REFRESH_TOKEN` VARCHAR(64) DEFAULT NULL COMMENT 'REFRESH_TOKEN，客户端模式该值为空',
    `SCOPE_ID` INT NOT NULL  COMMENT '授权范围ID',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX `IDX_CLIENT_ID_USER_NAME` (`ACCESS_TOKEN`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='ACCESS_TOKEN表';

CREATE TABLE IF NOT EXISTS `T_AUTH_OAUTH2_REFRESH_TOKEN` (
    `REFRESH_TOKEN` VARCHAR(64) NOT NULL COMMENT 'REFRESH_TOKEN',
    `CLIENT_ID` VARCHAR(32) NOT NULL COMMENT '客户端ID',
    `EXPIRED_TIME` BIGINT(20) NOT NULL COMMENT '过期时间',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX `IDX_REFRESH_TOKEN` (`REFRESH_TOKEN`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='REFRESH_TOKEN表';

CREATE TABLE IF NOT EXISTS `T_AUTH_OAUTH2_SCOPE` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主健ID',
    `SCOPE` MEDIUMTEXT NOT NULL  COMMENT '授权范围',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='授权范围表';

CREATE TABLE IF NOT EXISTS `T_AUTH_OAUTH2_SCOPE_OPERATION` (
   `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主健ID',
   `OPERATION_ID` VARCHAR(64) NOT NULL  COMMENT '授权操作ID',
   `OPERATION_NAME_CN` VARCHAR(64) NOT NULL  COMMENT '授权操作中文名称',
   `OPERATION_NAME_EN` VARCHAR(64) NOT NULL  COMMENT '授权操作英文名称',
   `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='授权操作信息表';

CREATE TABLE IF NOT EXISTS `T_AUTH_RESOURCE_GROUP_MEMBER`(
    `ID`              bigint auto_increment comment '主键ID',
    `PROJECT_CODE`  varchar(64)                        not null comment '项目ID',
    `RESOURCE_TYPE` varchar(32)                        not null comment '资源类型',
    `RESOURCE_CODE`     varchar(255) collate utf8mb4_bin   not null comment '资源ID',
    `GROUP_CODE`        varchar(32)                        not null comment '用户组标识',
    `IAM_GROUP_ID`  int(20)                         not null comment 'IAM组ID',
    `MEMBER_ID`     varchar(64)                        not null comment '成员ID',
    `MEMBER_NAME`   varchar(512)                       not null comment '成员名',
    `MEMBER_TYPE`   varchar(32)                        not null comment '成员类型,用户/组织/模板',
    `EXPIRED_TIME`  datetime                           not null comment '过期时间',
    `CREATE_TIME`   datetime default CURRENT_TIMESTAMP not null comment '创建时间',
    `UPDATE_TIME`   datetime default CURRENT_TIMESTAMP not null comment '更新时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UNIQ_PROJECT_GROUP_MEMBER` (`PROJECT_CODE`, `IAM_GROUP_ID`,`MEMBER_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT ='资源组成员';

CREATE TABLE IF NOT EXISTS T_AUTH_RESOURCE_AUTHORIZATION (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `PROJECT_CODE` varchar(32) NOT NULL COMMENT '项目ID',
    `RESOURCE_TYPE` varchar(32) NOT NULL COMMENT '资源类型',
    `RESOURCE_CODE` varchar(255) COLLATE utf8mb4_bin NOT NULL COMMENT '资源ID',
    `RESOURCE_NAME` varchar(255) NOT NULL COMMENT '资源名',
    `HANDOVER_FROM` VARCHAR(64) NOT NULL  COMMENT '授予人',
    `HANDOVER_FROM_CN_NAME` VARCHAR(64) NOT NULL  COMMENT '授予人中文名称',
    `HANDOVER_TIME` timestamp NOT NULL COMMENT '授予时间',
    `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UNIQ_PROJECT_RESOURCE` (`PROJECT_CODE`, `RESOURCE_TYPE`, `RESOURCE_CODE`),
    INDEX `HANDOVER_FROM_PROJECT_CODE_INDEX` (`HANDOVER_FROM`,`PROJECT_CODE`)
) ENGINE = InnoDB CHARSET = utf8mb4 COMMENT '资源授权管理表';

CREATE TABLE IF NOT EXISTS `T_AUTH_RESOURCE_SYNC`
(
    `PROJECT_CODE` varchar(64) not null comment '项目ID',
    `STATUS`             int(10)  default 0                 null comment '迁移状态, 0-同步中,1-同步成功,2-同步失败',
    `ERROR_MESSAGE`      text                               null comment '错误信息',
    `TOTAL_TIME`         bigint                             null comment '总耗时',
    `CREATE_TIME`   datetime default CURRENT_TIMESTAMP not null comment '创建时间',
    `UPDATE_TIME`   datetime default CURRENT_TIMESTAMP not null comment '更新时间',
    PRIMARY KEY (`PROJECT_CODE`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT ='同步IAM资源';

CREATE TABLE IF NOT EXISTS `T_AUTH_RESOURCE_GROUP_APPLY`
(
    `ID`            bigint auto_increment comment '主键ID',
    `PROJECT_CODE`  varchar(64)                not null comment '项目ID',
    `MEMBER_ID`     varchar(64)                not null comment '成员ID',
    `IAM_GROUP_ID`  int(20)                    not null comment 'IAM组ID',
    `STATUS`        int(2)       default 0     null comment '状态, 0-审批中,1-审批成功,2-审批超时',
    `NUMBER_OF_CHECKS`  int(10)  default 0     null comment '检查次数，用于同步组数据',
    `CREATE_TIME`   datetime default CURRENT_TIMESTAMP not null comment '创建时间',
    `UPDATE_TIME`   datetime default CURRENT_TIMESTAMP not null comment '更新时间',
    PRIMARY KEY (`ID`),
    INDEX `IDX_STATUS` (`STATUS`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT ='用户组申请记录表';

CREATE TABLE IF NOT EXISTS `T_AUTH_RESOURCE_GROUP_PERMISSION` (
    `ID` bigint(20) NOT NULL COMMENT '主键ID',
    `PROJECT_CODE` varchar(64) NOT NULL COMMENT '项目ID',
    `RESOURCE_TYPE` varchar(32) NOT NULL COMMENT '用户组关联的资源类型',
    `RESOURCE_CODE` varchar(255) COLLATE utf8mb4_bin NOT NULL COMMENT '用户组关联的资源ID',
    `IAM_RESOURCE_CODE` varchar(32) NOT NULL COMMENT '用户组关联的IAM资源ID',
    `GROUP_CODE` varchar(32) NOT NULL COMMENT '用户组标识',
    `IAM_GROUP_ID` int(20) NOT NULL COMMENT '关联的IAM组ID',
    `ACTION` varchar(64) NOT NULL COMMENT '操作ID',
    `ACTION_RELATED_RESOURCE_TYPE`  varchar(32) NOT NULL COMMENT '动作关联的资源类型',
    `RELATED_RESOURCE_TYPE`  varchar(32) NOT NULL COMMENT '组权限关联的资源类型',
    `RELATED_RESOURCE_CODE` varchar(255) COLLATE utf8mb4_bin NOT NULL COMMENT '组权限关联的资源ID',
    `RELATED_IAM_RESOURCE_CODE` varchar(255) COLLATE utf8mb4_bin NOT NULL COMMENT '组权限关联的资源ID',
    `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UNIQ_PERMISSION` (`PROJECT_CODE`, `IAM_GROUP_ID`, `RELATED_RESOURCE_TYPE`, `RELATED_RESOURCE_CODE`, `ACTION`),
    INDEX `IDX_PROJECT_AND_ACTION_RESOURCE_TYPE` (`PROJECT_CODE`, `ACTION_RELATED_RESOURCE_TYPE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='资源组权限表';

CREATE TABLE IF NOT EXISTS `T_AUTH_HANDOVER_OVERVIEW` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `PROJECT_CODE` varchar(64) NOT NULL COMMENT '项目ID',
    `PROJECT_NAME` varchar(64) NOT NULL COMMENT '项目名称',
    `FLOW_NO` varchar(64) NOT NULL COMMENT '流程单号',
    `TITLE` varchar(256) DEFAULT NULL COMMENT '标题',
    `APPLICANT` varchar(32) NOT NULL COMMENT '申请人',
    `APPROVER` varchar(32) DEFAULT NULL COMMENT '审批人',
    `STATUS` int DEFAULT 0 COMMENT '审批结果，0-审批中，1-审批成功，2-审批拒绝，3-撤销',
    `GROUP_COUNT` int DEFAULT 0 comment '用户组数',
    `AUTHORIZATION_COUNT` int DEFAULT 0 comment '授权个数',
    `REMARK` varchar(256) DEFAULT NULL COMMENT '备注',
    `LAST_OPERATOR` varchar(32) DEFAULT NULL COMMENT '最后操作人',
    `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UNIQ_FLOW_NO` (`FLOW_NO`),
    INDEX `IDX_PROJECT` (`PROJECT_CODE`),
    INDEX `IDX_APPLICANT` (`APPLICANT`),
    INDEX `IDX_APPROVER` (`APPROVER`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='权限交接总览表';

CREATE TABLE IF NOT EXISTS `T_AUTH_HANDOVER_DETAIL` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `PROJECT_CODE` varchar(64) NOT NULL COMMENT '项目ID',
    `FLOW_NO` varchar(64) NOT NULL COMMENT '流程单号',
    `ITEM_ID` varchar(255) NOT NULL COMMENT '组/授权资源ID',
    `RESOURCE_TYPE` varchar(32) NOT NULL COMMENT '组/授权资源关联的资源类型',
    `HANDOVER_TYPE` varchar(32) NOT NULL COMMENT '交接类型-group/authorization',
    `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`ID`),
    INDEX `IDX_PROJECT_FLOW` (`PROJECT_CODE`,`FLOW_NO`,`HANDOVER_TYPE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='权限交接详细表';

CREATE TABLE IF NOT EXISTS `T_USER_INFO` (
    `USER_ID` varchar(255) NOT NULL COMMENT '用户ID',
    `USER_NAME` varchar(255) NOT NULL COMMENT '用户名称',
    `ENABLED` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否离职',
    `DEPARTMENT_NAME` varchar(255) DEFAULT NULL COMMENT '部门名称',
    `DEPARTMENT_ID` int(11) DEFAULT NULL COMMENT '部门ID',
    `FULL_DEPARTMENTS` mediumtext COMMENT '完整部门信息',
    `PATH` varchar(255) DEFAULT NULL COMMENT '部门路径',
    `DEPARTED` bit(1) NOT NULL COMMENT '是否离职',
    `TASK_ID` varchar(255) NOT NULL COMMENT '同步',
    `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`USER_ID`),
    INDEX `IDX_TASK_ID` (`TASK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户信息表';

CREATE TABLE IF NOT EXISTS `T_AUTH_SYNC_DATA_TASK` (
    `TASK_ID` varchar(255) NOT NULL COMMENT '任务单号',
    `TASK_TYPE` varchar(64) NOT NULL COMMENT '任务类型，USER或DEPARTMENT',
    `START_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
    `END_TIME` timestamp NULL DEFAULT NULL COMMENT '结束时间',
    PRIMARY KEY (`TASK_ID`, `START_TIME`),
    UNIQUE  KEY `UNI_KEY`(`TASK_ID`),
    INDEX `IDX_END_TIME` (`END_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权限中心同步数据任务记录';

CREATE TABLE IF NOT EXISTS `T_DEPARTMENT` (
    `DEPARTMENT_ID` int(11) NOT NULL COMMENT '部门ID',
    `DEPARTMENT_NAME` varchar(255) NOT NULL COMMENT '部门名称',
    `PARENT` int(11) DEFAULT NULL COMMENT '父级',
    `LEVEL` int(11) DEFAULT NULL COMMENT '层级',
    `HAS_CHILDREN` bit(1) NOT NULL COMMENT '是否有子部门',
    `TASK_ID` varchar(255) NOT NULL COMMENT '同步任务单号',
    `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`DEPARTMENT_ID`),
    INDEX `IDX_TASK_ID` (`TASK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='部门信息表';

CREATE TABLE IF NOT EXISTS `T_DEPARTMENT_RELATION`(
    `PARENT_ID` int(11) NOT NULL COMMENT '父部门ID',
    `CHILDREN_ID` int(11) NOT NULL COMMENT '子部门ID',
    `DEPTH` int(11) NOT NULL COMMENT '深度',
    `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX `IDX_RELATION` (`PARENT_ID`,`CHILDREN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='部门信息关系表';

CREATE TABLE IF NOT EXISTS T_AUTH_MEMBER_PROJECT_PERMISSION (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `MEMBER_ID` VARCHAR(64) NOT NULL COMMENT '用户ID',
    `PROJECT_CODE` VARCHAR(64) NOT NULL COMMENT '项目ID',
    `ACTION` VARCHAR(32) NOT NULL COMMENT '权限',
    `IAM_GROUP_ID` int(20) NOT NULL COMMENT '权限来源的用户组',
    `EXPIRED_TIME` DATETIME NOT NULL COMMENT '该组授予的权限有效期',
    `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`ID`),
    UNIQUE  KEY `UNI_KEY` (`MEMBER_ID`, `ACTION`, `PROJECT_CODE`, `IAM_GROUP_ID`),
    INDEX `IDX_PROJECT_CODE_AND_GROUP_ID` (`PROJECT_CODE`,`IAM_GROUP_ID`)
) COMMENT='用户项目级权限表';

SET FOREIGN_KEY_CHECKS = 1;
