USE devops_ci_archive_process;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for T_PIPELINE_BUILD_HISTORY
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_HISTORY` (
  `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
  `PARENT_BUILD_ID` varchar(34) DEFAULT NULL COMMENT '父级构建ID',
  `PARENT_TASK_ID` varchar(34) DEFAULT NULL COMMENT '父级任务ID',
  `BUILD_NUM` int(20) DEFAULT '0' COMMENT '构建次数',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `VERSION` int(11) DEFAULT NULL COMMENT '版本号',
  `START_USER` varchar(64) DEFAULT NULL COMMENT '启动者',
  `TRIGGER` varchar(32) NOT NULL COMMENT '触发器',
  `START_TIME` timestamp NULL DEFAULT NULL COMMENT '开始时间',
  `END_TIME` timestamp NULL DEFAULT NULL COMMENT '结束时间',
  `STATUS` int(11) DEFAULT NULL COMMENT '状态',
  `STAGE_STATUS` text DEFAULT NULL COMMENT '流水线各阶段状态',
  `TASK_COUNT` int(11) DEFAULT NULL COMMENT '流水线任务数量',
  `FIRST_TASK_ID` varchar(34) DEFAULT NULL COMMENT '首次任务id',
  `CHANNEL` varchar(32) DEFAULT NULL COMMENT '项目渠道',
  `TRIGGER_USER` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '触发者',
  `MATERIAL` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '原材料',
  `QUEUE_TIME` timestamp NULL DEFAULT NULL COMMENT '排队开始时间',
  `ARTIFACT_INFO` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '构件列表信息',
  `ARTIFACT_QUALITY_INFO` mediumtext CHARACTER SET utf8mb4 comment '制品质量分析结果',
  `REMARK` varchar(4096) DEFAULT NULL COMMENT '评论',
  `EXECUTE_TIME` bigint(20) DEFAULT NULL COMMENT '执行时间',
  `BUILD_PARAMETERS` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '构建环境参数',
  `WEBHOOK_TYPE` varchar(64) DEFAULT NULL COMMENT 'WEBHOOK 类型',
  `RECOMMEND_VERSION` varchar(64) DEFAULT NULL COMMENT '推荐版本号',
  `ERROR_TYPE` int(11) DEFAULT NULL COMMENT '错误类型',
  `ERROR_CODE` int(11) DEFAULT NULL COMMENT '错误码',
  `ERROR_MSG` text COMMENT '错误描述',
  `WEBHOOK_INFO` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'WEBHOOK 信息',
  `IS_RETRY` BIT(1) DEFAULT b'0' COMMENT '是否重试',
  `EXECUTE_COUNT` int(11) DEFAULT NULL COMMENT '执行次数',
  `ERROR_INFO` text COMMENT '错误信息',
  `BUILD_MSG` VARCHAR(255) DEFAULT NULL COMMENT '构建信息',
  `BUILD_NUM_ALIAS` VARCHAR(256) COMMENT '自定义构建号',
  `CONCURRENCY_GROUP` varchar(255) DEFAULT NULL COMMENT '并发时,设定的group',
  `UPDATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `VERSION_NAME` varchar(64) DEFAULT NULL COMMENT '版本名称',
  `YAML_VERSION` varchar(34) DEFAULT NULL COMMENT 'YAML的版本标记',
  PRIMARY KEY (`BUILD_ID`),
  KEY `STATUS_KEY` (`PROJECT_ID`,`PIPELINE_ID`,`STATUS`),
  KEY `INX_TPBH_PROJECT_PIPELINE_NUM` (`PROJECT_ID`, `PIPELINE_ID`, `BUILD_NUM`),
  KEY `INX_TPBH_PROJECT_PIPELINE_START_TIME` (`PROJECT_ID`, `PIPELINE_ID`, `START_TIME`),
  KEY `inx_tpbh_status` (`STATUS`),
  KEY `inx_tpbh_start_time` (`START_TIME`),
  KEY `inx_tpbh_end_time` (`END_TIME`),
  KEY `IDX_PROJECT_STATUS_GROUP` (`PROJECT_ID`,`STATUS`,`CONCURRENCY_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线构建历史表';

-- ----------------------------
-- Table structure for T_PIPELINE_BUILD_SUMMARY
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_SUMMARY` (
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `BUILD_NUM` int(11) DEFAULT '0' COMMENT '构建次数',
  `BUILD_NO` int(11) DEFAULT '0' COMMENT '构建号',
  `FINISH_COUNT` int(11) DEFAULT '0' COMMENT '完成次数',
  `RUNNING_COUNT` int(11) DEFAULT '0' COMMENT '运行次数',
  `QUEUE_COUNT` int(11) DEFAULT '0' COMMENT '排队次数',
  `LATEST_BUILD_ID` varchar(34) DEFAULT NULL COMMENT '最近构建ID',
  `LATEST_TASK_ID` varchar(34) DEFAULT NULL COMMENT '最近任务ID',
  `LATEST_START_USER` varchar(64) DEFAULT NULL COMMENT '最近启动者',
  `LATEST_START_TIME` timestamp NULL DEFAULT NULL COMMENT '最近启动时间',
  `LATEST_END_TIME` timestamp NULL DEFAULT NULL COMMENT '最近结束时间',
  `LATEST_TASK_COUNT` int(11) DEFAULT NULL COMMENT '最近任务计数',
  `LATEST_TASK_NAME` varchar(128) DEFAULT NULL COMMENT '最近任务名称',
  `LATEST_STATUS` int(11) DEFAULT NULL COMMENT '最近状态',
  `BUILD_NUM_ALIAS` VARCHAR(256) COMMENT '自定义构建号',
  `DEBUG_BUILD_NUM` int(11) DEFAULT '0' COMMENT '调试构建次数',
  `DEBUG_BUILD_NO` int(11) DEFAULT '0' COMMENT '调试构建号',
  PRIMARY KEY (`PIPELINE_ID`),
  KEY `PRJOECT_ID` (`PROJECT_ID`,`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线构建摘要表';

-- ----------------------------
-- Table structure for T_PIPELINE_INFO
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_INFO` (
  `PIPELINE_ID` varchar(34) NOT NULL DEFAULT '' COMMENT '流水线ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `PIPELINE_NAME` varchar(255) NOT NULL COMMENT '流水线名称',
  `PIPELINE_DESC` varchar(255) DEFAULT NULL COMMENT '流水线描述',
  `VERSION` int(11) DEFAULT '1' COMMENT '版本号',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATOR` varchar(64) NOT NULL COMMENT '创建者',
  `UPDATE_TIME` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `LAST_MODIFY_USER` varchar(64) NOT NULL COMMENT '最近修改者',
  `CHANNEL` varchar(32) DEFAULT NULL COMMENT '项目渠道',
  `MANUAL_STARTUP` int(11) DEFAULT '1' COMMENT '是否手工启动',
  `ELEMENT_SKIP` int(11) DEFAULT '0' COMMENT '是否跳过插件',
  `TASK_COUNT` int(11) DEFAULT '0' COMMENT '流水线任务数量',
  `DELETE` bit(1) DEFAULT b'0' COMMENT '是否删除',
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PIPELINE_NAME_PINYIN` varchar(1300) DEFAULT NULL COMMENT '流水线名称拼音',
  `LATEST_START_TIME` datetime(3) DEFAULT NULL COMMENT '最近启动时间',
  `LATEST_VERSION_STATUS` varchar(64) DEFAULT NULL COMMENT '最新分布版本状态',
  `LOCKED` bit(1) DEFAULT b'0' COMMENT '是否锁定，PAC v3.0新增锁定，取代原来setting表中的LOCK',
  PRIMARY KEY (`PIPELINE_ID`),
  UNIQUE KEY `T_PIPELINE_INFO_NAME_uindex` (`PROJECT_ID`,`PIPELINE_NAME`),
  KEY `PROJECT_ID` (`PROJECT_ID`,`PIPELINE_ID`),
  KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线信息表';

-- ----------------------------
-- Table structure for T_PIPELINE_LABEL_PIPELINE
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_LABEL_PIPELINE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `LABEL_ID` bigint(20) NOT NULL COMMENT '标签ID',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `CREATE_USER` varchar(64) NOT NULL COMMENT '创建者',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_INX_TPLP_PROJECT_PIPELINE_LABEL` (`PROJECT_ID`, `PIPELINE_ID`,`LABEL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线-标签映射表';

-- ----------------------------
-- Table structure for T_PIPELINE_RESOURCE
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_RESOURCE` (
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '版本号',
  `VERSION_NAME` varchar(64) DEFAULT NULL COMMENT '版本名称',
  `MODEL` mediumtext COMMENT '流水线模型',
  `YAML` mediumtext COMMENT 'YAML编排',
  `YAML_VERSION` varchar(34) DEFAULT NULL COMMENT 'YAML的版本标记',
  `CREATOR` varchar(64) DEFAULT NULL COMMENT '创建者',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `VERSION_NUM` int(11) DEFAULT NULL COMMENT '流水线发布版本',
  `PIPELINE_VERSION` int(11) DEFAULT NULL COMMENT '流水线模型版本',
  `TRIGGER_VERSION` int(11) DEFAULT NULL COMMENT '触发器模型版本',
  `SETTING_VERSION` int(11) DEFAULT NULL COMMENT '关联的流水线设置版本号',
  PRIMARY KEY (`PIPELINE_ID`,`VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线资源表';

-- ----------------------------
-- Table structure for T_TEMPLATE_PIPELINE
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_TEMPLATE_PIPELINE` (
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `INSTANCE_TYPE` VARCHAR(32) NOT NULL DEFAULT 'CONSTRAINT' COMMENT '实例化类型：FREEDOM 自由模式  CONSTRAINT 约束模式',
  `ROOT_TEMPLATE_ID` VARCHAR(32) NULL COMMENT '源模板ID',
  `VERSION` bigint(20) NOT NULL COMMENT '版本号',
  `VERSION_NAME` varchar(64) NOT NULL COMMENT '版本名称',
  `TEMPLATE_ID` varchar(32) NOT NULL COMMENT '模板ID',
  `CREATOR` varchar(64) NOT NULL COMMENT '创建者',
  `UPDATOR` varchar(64) NOT NULL COMMENT '更新人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_TIME` datetime NOT NULL COMMENT '更新时间',
  `BUILD_NO` text COMMENT '构建号',
  `PARAM` mediumtext COMMENT '参数',
  `DELETED` bit(1) DEFAULT b'0' COMMENT '流水线已被软删除',
  `INSTANCE_ERROR_INFO` text null comment '实例化错误信息',
  PRIMARY KEY (`PIPELINE_ID`),
  KEY `TEMPLATE_ID` (`TEMPLATE_ID`),
  KEY `ROOT_TEMPLATE_ID` (`ROOT_TEMPLATE_ID`),
  KEY `INX_TTP_PROJECT_TEMPLATE_VERSION` (`PROJECT_ID`,`TEMPLATE_ID`,`VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线模板-实例映射表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_RESOURCE_VERSION` (
    `PROJECT_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
    `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
    `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '版本号',
    `VERSION_NAME` varchar(64) NOT NULL COMMENT '版本名称',
    `MODEL` mediumtext COMMENT '流水线模型',
    `YAML` mediumtext COMMENT 'YAML编排',
    `YAML_VERSION` varchar(34) DEFAULT NULL COMMENT 'YAML的版本标记',
    `CREATOR` varchar(64) DEFAULT NULL COMMENT '创建者',
    `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `REFER_FLAG` bit(1) DEFAULT NULL COMMENT '是否还有构建记录引用该版本标识',
    `REFER_COUNT` int(20) DEFAULT NULL COMMENT '关联构建记录总数',
    `VERSION_NUM` int(11) DEFAULT NULL COMMENT '流水线发布版本',
    `PIPELINE_VERSION` int(11) DEFAULT '0' COMMENT '流水线模型版本',
    `TRIGGER_VERSION` int(11) DEFAULT '0' COMMENT '触发器模型版本',
    `SETTING_VERSION` int(11) DEFAULT '0' COMMENT '关联的流水线设置版本号',
    `BASE_VERSION` int(11) DEFAULT NULL COMMENT '草稿的来源版本',
    `DEBUG_BUILD_ID` varchar(64) DEFAULT NULL COMMENT '调试构建ID',
    `STATUS` varchar(16) DEFAULT NULL COMMENT '版本状态',
    `BRANCH_ACTION` varchar(32) DEFAULT NULL COMMENT '分支状态',
    `DESCRIPTION` text COMMENT '版本变更说明',
    `UPDATER` varchar(64) DEFAULT NULL COMMENT '最近更新人',
    `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `RELEASE_TIME` TIMESTAMP NULL COMMENT '发布时间',
    PRIMARY KEY (`PIPELINE_ID`,`VERSION`),
    KEY `INX_PIPELINE_UPDATE_TIME` (`PROJECT_ID`,`PIPELINE_ID`,`UPDATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线资源版本表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_RECORD_CONTAINER` (
    `BUILD_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '构建ID',
    `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '项目ID',
    `PIPELINE_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '流水线ID',
    `RESOURCE_VERSION` int(11) NOT NULL COMMENT '编排版本',
    `STAGE_ID` varchar(64) CHARACTER SET utf8mb4 NOT NULL DEFAULT '' COMMENT '步骤ID',
    `CONTAINER_ID` varchar(64) CHARACTER SET utf8mb4 NOT NULL DEFAULT '' COMMENT '构建容器ID',
    `EXECUTE_COUNT` int(11) NOT NULL DEFAULT '1' COMMENT '执行次数',
    `STATUS` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '构建状态',
    `CONTAINER_VAR` mediumtext CHARACTER SET utf8mb4 NOT NULL COMMENT '当次执行的变量记录',
    `CONTAINER_TYPE` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '容器类型',
    `CONTAIN_POST_TASK` bit(1) DEFAULT NULL COMMENT '包含POST插件标识',
    `MATRIX_GROUP_FLAG` bit(1) DEFAULT NULL COMMENT '矩阵标识',
    `MATRIX_GROUP_ID` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '所属的矩阵组ID',
    `START_TIME` datetime(3) NULL DEFAULT NULL COMMENT '开始时间',
    `END_TIME` datetime(3) NULL DEFAULT NULL COMMENT '结束时间',
    `TIMESTAMPS` text CHARACTER SET utf8mb4 COMMENT '运行中产生的时间戳集合',
    PRIMARY KEY (`BUILD_ID`,`CONTAINER_ID`,`EXECUTE_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='流水线构建容器环境表';

CREATE TABLE IF NOT EXISTS  `T_PIPELINE_BUILD_RECORD_MODEL` (
    `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
    `PROJECT_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
    `PIPELINE_ID` varchar(34) NOT NULL DEFAULT '' COMMENT '流水线ID',
    `RESOURCE_VERSION` int(11) NOT NULL COMMENT '编排版本',
    `BUILD_NUM` int(20) NOT NULL COMMENT '构建次数',
    `EXECUTE_COUNT` int(11) NOT NULL COMMENT '执行次数',
    `START_USER` varchar(32) NOT NULL DEFAULT '' COMMENT '启动者',
    `MODEL_VAR` mediumtext NOT NULL COMMENT '当次执行的变量记录',
    `START_TYPE` varchar(32) NOT NULL DEFAULT '' COMMENT '触发方式',
    `QUEUE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '触发时间',
    `START_TIME` datetime(3) NULL DEFAULT NULL COMMENT '启动时间',
    `END_TIME` datetime(3) NULL DEFAULT NULL COMMENT '结束时间',
    `STATUS` varchar(32) DEFAULT NULL COMMENT '构建状态',
    `ERROR_INFO` text COMMENT '错误信息',
    `CANCEL_USER` varchar(32) DEFAULT NULL COMMENT '取消者',
    `TIMESTAMPS` text COMMENT '运行中产生的时间戳集合',
    PRIMARY KEY (`BUILD_ID`,`EXECUTE_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线构建详情表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_RECORD_STAGE` (
    `BUILD_ID` varchar(64) CHARACTER SET utf8mb4 NOT NULL COMMENT '构建ID',
    `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
    `PIPELINE_ID` varchar(64) CHARACTER SET utf8mb4 NOT NULL DEFAULT '' COMMENT '流水线ID',
    `RESOURCE_VERSION` int(11) DEFAULT NULL COMMENT '编排版本号',
    `STAGE_ID` varchar(64) CHARACTER SET utf8mb4 NOT NULL DEFAULT '' COMMENT '步骤ID',
    `SEQ` int(11) NOT NULL COMMENT '步骤序列',
    `STAGE_VAR` text CHARACTER SET utf8mb4 NOT NULL COMMENT '当次执行的变量记录',
    `STATUS` varchar(32) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '构建状态',
    `EXECUTE_COUNT` int(11) NOT NULL DEFAULT '1' COMMENT '执行次数',
    `START_TIME` datetime(3) NULL DEFAULT NULL COMMENT '开始时间',
    `END_TIME` datetime(3) NULL DEFAULT NULL COMMENT '结束时间',
    `TIMESTAMPS` text CHARACTER SET utf8mb4 COMMENT '运行中产生的时间戳集合',
    PRIMARY KEY (`BUILD_ID`,`STAGE_ID`,`EXECUTE_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='流水线构建阶段表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_RECORD_TASK` (
    `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
    `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
    `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
    `RESOURCE_VERSION` int(11) NOT NULL COMMENT '编排版本号',
    `STAGE_ID` varchar(34) NOT NULL DEFAULT '' COMMENT '步骤ID',
    `CONTAINER_ID` varchar(34) NOT NULL COMMENT '构建容器ID',
    `TASK_ID` varchar(34) NOT NULL COMMENT '任务ID',
    `TASK_SEQ` int(11) NOT NULL DEFAULT '1' COMMENT '任务序列',
    `EXECUTE_COUNT` int(11) NOT NULL DEFAULT '1' COMMENT '执行次数',
    `STATUS` varchar(32) DEFAULT NULL COMMENT '构建状态',
    `TASK_VAR` mediumtext NOT NULL COMMENT '当次执行的变量记录',
    `POST_INFO` text DEFAULT NULL COMMENT '市场插件的POST关联信息',
    `CLASS_TYPE` varchar(64) NOT NULL DEFAULT '' COMMENT '项目ID',
    `ATOM_CODE` varchar(128) NOT NULL DEFAULT '' COMMENT '插件的唯一标识',
    `ORIGIN_CLASS_TYPE` varchar(64) DEFAULT NULL COMMENT '所在矩阵组ID',
    `START_TIME` datetime(3) NULL DEFAULT NULL COMMENT '开始时间',
    `END_TIME` datetime(3) NULL DEFAULT NULL COMMENT '结束时间',
    `TIMESTAMPS` text COMMENT '运行中产生的时间戳集合',
    `ASYNC_STATUS` varchar(32) NULL DEFAULT NULL COMMENT '插件异步执行状态',
    PRIMARY KEY (`BUILD_ID`,`TASK_ID`,`EXECUTE_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线构建任务表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_HISTORY_DEBUG` (
    `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
    `PARENT_BUILD_ID` varchar(34) DEFAULT NULL COMMENT '父级构建ID',
    `PARENT_TASK_ID` varchar(34) DEFAULT NULL COMMENT '父级任务ID',
    `BUILD_NUM` int(20) DEFAULT '0' COMMENT '构建次数',
    `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
    `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
    `VERSION` int(11) DEFAULT NULL COMMENT '版本号',
    `START_USER` varchar(64) DEFAULT NULL COMMENT '启动者',
    `TRIGGER` varchar(32) NOT NULL COMMENT '触发器',
    `START_TIME` timestamp NULL DEFAULT NULL COMMENT '开始时间',
    `END_TIME` timestamp NULL DEFAULT NULL COMMENT '结束时间',
    `STATUS` int(11) DEFAULT NULL COMMENT '状态',
    `STAGE_STATUS` text COMMENT '流水线各阶段状态',
    `TASK_COUNT` int(11) DEFAULT NULL COMMENT '流水线任务数量',
    `FIRST_TASK_ID` varchar(34) DEFAULT NULL COMMENT '首次任务id',
    `CHANNEL` varchar(32) DEFAULT NULL COMMENT '项目渠道',
    `TRIGGER_USER` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '触发者',
    `MATERIAL` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '原材料',
    `QUEUE_TIME` timestamp NULL DEFAULT NULL COMMENT '排队开始时间',
    `ARTIFACT_INFO` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '构件列表信息',
    `ARTIFACT_QUALITY_INFO` mediumtext CHARACTER SET utf8mb4 comment '制品质量分析结果',
    `REMARK` varchar(4096) DEFAULT NULL COMMENT '评论',
    `EXECUTE_TIME` bigint(20) DEFAULT NULL COMMENT '执行时间',
    `BUILD_PARAMETERS` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '构建环境参数',
    `WEBHOOK_TYPE` varchar(64) DEFAULT NULL COMMENT 'WEBHOOK 类型',
    `RECOMMEND_VERSION` varchar(64) DEFAULT NULL COMMENT '推荐版本号',
    `ERROR_TYPE` int(11) DEFAULT NULL COMMENT '错误类型',
    `ERROR_CODE` int(11) DEFAULT NULL COMMENT '错误码',
    `ERROR_MSG` text COMMENT '错误描述',
    `WEBHOOK_INFO` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'WEBHOOK 信息',
    `ERROR_INFO` text COMMENT '错误信息',
    `BUILD_MSG` varchar(255) DEFAULT NULL COMMENT '构建信息',
    `BUILD_NUM_ALIAS` varchar(256) DEFAULT NULL COMMENT '自定义构建号',
    `CONCURRENCY_GROUP` varchar(255) DEFAULT NULL COMMENT '并发时,设定的group',
    `UPDATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `REPO_TRIGGER_INFO` text COMMENT '触发库信息',
    `EXECUTE_COUNT` int(11) DEFAULT NULL COMMENT '最大执行次数',
    `IS_RETRY` bit(1) DEFAULT NULL COMMENT '是否进行过重试',
    `YAML_VERSION` varchar(34) DEFAULT NULL COMMENT 'YAML的版本标记',
    `RESOURCE_MODEL` mediumtext COMMENT '本次调试的编排备份',
    `DELETE_TIME` timestamp NULL DEFAULT NULL COMMENT '记录删除时间',
    PRIMARY KEY (`BUILD_ID`),
    KEY `STATUS_KEY` (`PROJECT_ID`,`PIPELINE_ID`,`STATUS`),
    KEY `INX_TPBH_PROJECT_PIPELINE_NUM` (`PROJECT_ID`,`PIPELINE_ID`,`BUILD_NUM`),
    KEY `INX_TPBH_PROJECT_PIPELINE_START_TIME` (`PROJECT_ID`,`PIPELINE_ID`,`START_TIME`),
    KEY `inx_tpbh_status` (`STATUS`),
    KEY `inx_tpbh_start_time` (`START_TIME`),
    KEY `inx_tpbh_end_time` (`END_TIME`),
    KEY `IDX_PROJECT_STATUS_GROUP` (`PROJECT_ID`,`STATUS`,`CONCURRENCY_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线调试构建历史表';

-- ----------------------------
-- Table structure for T_PIPELINE_FAVOR
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_FAVOR` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
    `PIPELINE_ID` varchar(64) NOT NULL COMMENT '流水线ID',
    `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
    `CREATE_USER` varchar(64) NOT NULL COMMENT '创建者',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UNI_INX_TPF_PROJECT_PIPELINE_USER` (`PROJECT_ID`, `PIPELINE_ID`,`CREATE_USER`),
    KEY `PROJECT` (`PROJECT_ID`,`CREATE_USER`),
    KEY `USER` (`CREATE_USER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线收藏表';

-- ----------------------------
-- Table structure for T_PIPELINE_VIEW_GROUP
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_VIEW_GROUP` (
    `ID` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
    `VIEW_ID` bigint NOT NULL COMMENT '流水线组ID',
    `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
    `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
    `CREATOR` varchar(64) NOT NULL COMMENT '创建者',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UNI_PROJECT_VIEW_PIPELINE` (`PROJECT_ID` , `VIEW_ID` , `PIPELINE_ID`),
    KEY `IDX_PIPELINE` (`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线组关系表';

-- ----------------------------
-- Table structure for T_PIPELINE_TRIGGER_REVIEW
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_TRIGGER_REVIEW` (
    `BUILD_ID` varchar(34) NOT NULL DEFAULT '' COMMENT '构建ID',
    `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
    `PIPELINE_ID` varchar(34) NOT NULL DEFAULT '' COMMENT '流水线ID',
    `TRIGGER_REVIEWER` text NOT NULL COMMENT '触发审核人列表',
    `TRIGGER_OPERATOR` varchar(64) DEFAULT NULL COMMENT '触发审核操作人',
    `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '审核时间',
    PRIMARY KEY (`BUILD_ID`),
    KEY `PROJECT_BUILD` (`PROJECT_ID`,`PIPELINE_ID`,`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线触发审核信息';

-- ----------------------------
-- Table structure for T_PIPELINE_SETTING
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_SETTING` (
    `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
    `PROJECT_ID` varchar(64) DEFAULT NULL COMMENT '项目ID',
    `DESC` varchar(1024) DEFAULT NULL COMMENT '描述',
    `RUN_TYPE` int(11) DEFAULT NULL COMMENT '运行锁定类型',
    `NAME` varchar(255) DEFAULT NULL COMMENT '名称',
    `SUCCESS_RECEIVER` mediumtext COMMENT '成功接受者',
    `FAIL_RECEIVER` mediumtext COMMENT '失败接受者',
    `SUCCESS_GROUP` mediumtext COMMENT '成功组',
    `FAIL_GROUP` mediumtext COMMENT '失败组',
    `SUCCESS_TYPE` varchar(32) DEFAULT NULL COMMENT '成功的通知方式',
    `FAIL_TYPE` varchar(32) DEFAULT NULL COMMENT '失败的通知方式',
    `SUCCESS_WECHAT_GROUP_FLAG` bit(1) NOT NULL DEFAULT b'0' COMMENT '成功的企业微信群通知开关',
    `SUCCESS_WECHAT_GROUP` varchar(1024) NOT NULL DEFAULT '' COMMENT '成功的企业微信群通知群ID',
    `FAIL_WECHAT_GROUP_FLAG` bit(1) NOT NULL DEFAULT b'0' COMMENT '失败的企业微信群通知开关',
    `FAIL_WECHAT_GROUP` varchar(1024) NOT NULL DEFAULT '' COMMENT '失败的企业微信群通知群ID',
    `RUN_LOCK_TYPE` int(11) DEFAULT '1' COMMENT 'Lock 类型',
    `SUCCESS_DETAIL_FLAG` bit(1) DEFAULT b'0' COMMENT '成功的通知的流水线详情连接开关',
    `FAIL_DETAIL_FLAG` bit(1) DEFAULT b'0' COMMENT '失败的通知的流水线详情连接开关',
    `SUCCESS_CONTENT` longtext COMMENT '成功的自定义通知内容',
    `FAIL_CONTENT` longtext COMMENT '失败的自定义通知内容',
    `WAIT_QUEUE_TIME_SECOND` int(11) DEFAULT '7200' COMMENT '最大排队时长',
    `MAX_QUEUE_SIZE` int(11) DEFAULT '10' COMMENT '最大排队数量',
    `IS_TEMPLATE` bit(1) DEFAULT b'0' COMMENT '是否模板',
    `SUCCESS_WECHAT_GROUP_MARKDOWN_FLAG` bit(1) NOT NULL DEFAULT b'0' COMMENT '成功的企业微信群通知转为Markdown格式开关',
    `FAIL_WECHAT_GROUP_MARKDOWN_FLAG` bit(1) NOT NULL DEFAULT b'0' COMMENT '失败的企业微信群通知转为Markdown格式开关',
    `MAX_PIPELINE_RES_NUM` int(11) DEFAULT '500' COMMENT '保存流水线编排的最大个数',
    `MAX_CON_RUNNING_QUEUE_SIZE` int(11) DEFAULT NULL COMMENT '并发构建数量限制,为null时表示取系统默认值',
    `BUILD_NUM_RULE` varchar(512) DEFAULT NULL COMMENT '构建号生成规则',
    `CONCURRENCY_GROUP` varchar(255) DEFAULT NULL COMMENT '并发时,设定的group',
    `CONCURRENCY_CANCEL_IN_PROGRESS` bit(1) DEFAULT b'0' COMMENT '并发时,是否相同group取消正在执行的流水线',
    `CLEAN_VARIABLES_WHEN_RETRY` bit(1) DEFAULT b'0' COMMENT '重试时清理变量表',
    `PIPELINE_AS_CODE_SETTINGS` varchar(512) DEFAULT NULL COMMENT 'YAML流水线相关配置',
    `VERSION` int(11) DEFAULT '1' COMMENT '设置版本',
    `SUCCESS_SUBSCRIPTION` text COMMENT '成功订阅设置',
    `FAILURE_SUBSCRIPTION` text COMMENT '失败订阅设置',
    `FAIL_IF_VARIABLE_INVALID` bit(1) DEFAULT NULL COMMENT '是否配置流水线变量值超长时终止执行',
    PRIMARY KEY (`PIPELINE_ID`),
    UNIQUE KEY `PROJECT_ID` (`PROJECT_ID`,`NAME`,`IS_TEMPLATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线基础配置表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_SETTING_VERSION` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `PROJECT_ID` varchar(64) DEFAULT NULL COMMENT '项目ID',
    `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
    `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '版本号',
    `IS_TEMPLATE` bit(1) DEFAULT b'0' COMMENT '是否模板',
    `NAME` varchar(255) DEFAULT NULL COMMENT '名称',
    `DESC` varchar(1024) DEFAULT NULL COMMENT '描述',
    `LABELS` text DEFAULT NULL COMMENT '版本修改的标签',
    `WAIT_QUEUE_TIME_SECOND` int(11) DEFAULT '7200' COMMENT '最大排队时长',
    `MAX_QUEUE_SIZE` int(11) DEFAULT '10' COMMENT '最大排队数量',
    `BUILD_NUM_RULE` varchar(512) DEFAULT NULL COMMENT '构建号生成规则',
    `CONCURRENCY_GROUP` varchar(255) DEFAULT NULL COMMENT '并发时,设定的group',
    `CONCURRENCY_CANCEL_IN_PROGRESS` bit(1) DEFAULT b'0' COMMENT '并发时,是否相同group取消正在执行的流水线',
    `PIPELINE_AS_CODE_SETTINGS` varchar(512) DEFAULT NULL COMMENT 'YAML流水线相关配置',
    `SUCCESS_SUBSCRIPTION` text COMMENT '成功订阅设置',
    `FAILURE_SUBSCRIPTION` text COMMENT '失败订阅设置',
    `RUN_LOCK_TYPE` int(11) DEFAULT '1' COMMENT '运行并发配置',
    `SUCCESS_RECEIVER` mediumtext,
    `FAIL_RECEIVER` mediumtext,
    `SUCCESS_GROUP` mediumtext,
    `FAIL_GROUP` mediumtext,
    `SUCCESS_TYPE` varchar(32) DEFAULT NULL,
    `FAIL_TYPE` varchar(32) DEFAULT NULL,
    `SUCCESS_WECHAT_GROUP_FLAG` bit(1) NOT NULL DEFAULT b'0',
    `SUCCESS_WECHAT_GROUP` varchar(1024) NOT NULL DEFAULT '',
    `FAIL_WECHAT_GROUP_FLAG` bit(1) NOT NULL DEFAULT b'0',
    `FAIL_WECHAT_GROUP` varchar(1024) NOT NULL DEFAULT '',
    `SUCCESS_DETAIL_FLAG` bit(1) DEFAULT b'0',
    `FAIL_DETAIL_FLAG` bit(1) DEFAULT b'0',
    `SUCCESS_CONTENT` longtext,
    `FAIL_CONTENT` longtext,
    `SUCCESS_WECHAT_GROUP_MARKDOWN_FLAG` bit(1) NOT NULL DEFAULT b'0',
    `FAIL_WECHAT_GROUP_MARKDOWN_FLAG` bit(1) DEFAULT b'0',
    `MAX_CON_RUNNING_QUEUE_SIZE` int(11) DEFAULT NULL COMMENT '并发构建数量限制,值为-1时表示取系统默认值。',
    `FAIL_IF_VARIABLE_INVALID` bit(1) DEFAULT NULL COMMENT '是否配置流水线变量值超长时终止执行',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UNI_INX_TPSV_PROJECT_PIPELINE_VERSION` (`PROJECT_ID`,`PIPELINE_ID`,`VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线基础配置版本表';

-- ----------------------------
-- Table structure for T_REPORT
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_REPORT` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `PROJECT_ID` varchar(32) NOT NULL COMMENT '项目ID',
    `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
    `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
    `ELEMENT_ID` varchar(34) NOT NULL COMMENT '原子ID',
    `TYPE` varchar(32) NOT NULL DEFAULT 'INTERNAL' COMMENT '类型',
    `INDEX_FILE` mediumtext NOT NULL COMMENT '入口文件',
    `NAME` text NOT NULL COMMENT '名称',
    `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
    `UPDATE_TIME` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `TASK_NAME` varchar(128) NOT NULL DEFAULT '' COMMENT '任务名称',
    `ATOM_CODE` varchar(128) NOT NULL DEFAULT '' COMMENT '插件的唯一标识',
    PRIMARY KEY (`ID`),
    KEY `PROJECT_PIPELINE_BUILD_IDX` (`PROJECT_ID`,`PIPELINE_ID`,`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线产物表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_OPERATION_LOG` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
    `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
    `VERSION` int(11) NOT NULL COMMENT '操作版本号',
    `OPERATOR` varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
    `OPERATION_TYPE` varchar(32) NOT NULL DEFAULT '' COMMENT '操作类型',
    `PARAMS` varchar(255) DEFAULT NULL COMMENT '操作参数',
    `DESCRIPTION` text COMMENT '版本变更说明',
    `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`ID`),
    KEY `PROJECT_PIPELINE_IDX` (`PROJECT_ID`,`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线操作记录表';

SET FOREIGN_KEY_CHECKS = 1;
