USE devops_ci_process;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for T_BUILD_STARTUP_PARAM
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_BUILD_STARTUP_PARAM` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `BUILD_ID` varchar(64) NOT NULL COMMENT '构建ID',
  `PARAM` mediumtext NOT NULL COMMENT '参数',
  `PROJECT_ID` varchar(64) DEFAULT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(64) DEFAULT NULL COMMENT '流水线ID',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `BUILD_ID` (`BUILD_ID`),
  KEY `IDX_DEL` (`PROJECT_ID`,`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线启动变量表';

-- ----------------------------
-- Table structure for T_PIPELINE_BUILD_CONTAINER
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_CONTAINER` (
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '流水线ID',
  `BUILD_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '构建ID',
  `STAGE_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '当前stageId',
  `CONTAINER_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '构建容器ID',
  `CONTAINER_TYPE` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '容器类型',
  `SEQ` int(11) NOT NULL COMMENT '',
  `STATUS` int(11) DEFAULT NULL COMMENT '状态',
  `START_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
  `END_TIME` timestamp NULL DEFAULT NULL COMMENT '结束时间',
  `COST` int(11) DEFAULT '0' COMMENT '花费',
  `EXECUTE_COUNT` int(11) DEFAULT '1' COMMENT '执行次数',
  `CONDITIONS` mediumtext COLLATE utf8mb4_bin DEFAULT NULL COMMENT '状况',
  `CONTAINER_HASH_ID` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '容器全局唯一ID',
  `MATRIX_GROUP_FLAG` BIT(1) DEFAULT NULL COMMENT '是否为构建矩阵',
  `MATRIX_GROUP_ID` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '所属的矩阵组ID',
  PRIMARY KEY (`BUILD_ID`,`STAGE_ID`,`CONTAINER_ID`),
  KEY `idx_proj_pipeline` (`PROJECT_ID`,`PIPELINE_ID`),
  KEY `IDX_STATUS` (`STATUS`),
  KEY `INX_TPBC_PROJECT_BUILD_SEQ` (`PROJECT_ID`, `BUILD_ID`, `SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='流水线构建容器环境表';

-- ----------------------------
-- Table structure for T_PIPELINE_BUILD_DETAIL
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_DETAIL` (
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
  `BUILD_NUM` int(20) DEFAULT NULL COMMENT '构建次数',
  `MODEL` mediumtext COMMENT '流水线模型',
  `START_USER` varchar(32) DEFAULT NULL COMMENT '启动者',
  `TRIGGER` varchar(32) DEFAULT NULL COMMENT '触发器',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `STATUS` varchar(32) DEFAULT NULL COMMENT '状态',
  `CANCEL_USER` varchar(32) DEFAULT NULL COMMENT '取消者',
  PRIMARY KEY (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线构建详情表';

-- ----------------------------
-- Table structure for T_PIPELINE_BUILD_HISTORY
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_HISTORY` (
  `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
  `PARENT_BUILD_ID` varchar(34) DEFAULT NULL COMMENT '父级构建ID',
  `PARENT_TASK_ID` varchar(34) DEFAULT NULL COMMENT '父级任务ID',
  `BUILD_NUM` int(20) DEFAULT '0' COMMENT '构建次数',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `VERSION` int(11) DEFAULT NULL COMMENT '版本号',
  `START_USER` varchar(64) DEFAULT NULL COMMENT '启动者',
  `TRIGGER` varchar(32) NOT NULL COMMENT '触发器',
  `START_TIME` timestamp NULL DEFAULT NULL COMMENT '开始时间',
  `END_TIME` timestamp NULL DEFAULT NULL COMMENT '结束时间',
  `STATUS` int(11) DEFAULT NULL COMMENT '状态',
  `STAGE_STATUS` text DEFAULT NULL COMMENT '流水线各阶段状态',
  `TASK_COUNT` int(11) DEFAULT NULL COMMENT '流水线任务数量',
  `FIRST_TASK_ID` varchar(34) DEFAULT NULL COMMENT '首次任务id',
  `CHANNEL` varchar(32) DEFAULT NULL COMMENT '项目渠道',
  `TRIGGER_USER` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '触发者',
  `MATERIAL` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '原材料',
  `QUEUE_TIME` timestamp NULL DEFAULT NULL COMMENT '排队开始时间',
  `ARTIFACT_INFO` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '构件列表信息',
  `REMARK` varchar(4096) DEFAULT NULL COMMENT '评论',
  `EXECUTE_TIME` bigint(20) DEFAULT NULL COMMENT '执行时间',
  `BUILD_PARAMETERS` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '构建环境参数',
  `WEBHOOK_TYPE` varchar(64) DEFAULT NULL COMMENT 'WEBHOOK 类型',
  `RECOMMEND_VERSION` varchar(64) DEFAULT NULL COMMENT '推荐版本号',
  `ERROR_TYPE` int(11) DEFAULT NULL COMMENT '错误类型',
  `ERROR_CODE` int(11) DEFAULT NULL COMMENT '错误码',
  `ERROR_MSG` text COMMENT '错误描述',
  `WEBHOOK_INFO` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'WEBHOOK 信息',
  `IS_RETRY` BIT(1) DEFAULT b'0' COMMENT '是否重试',
  `EXECUTE_COUNT` int(11) DEFAULT NULL COMMENT '执行次数',
  `ERROR_INFO` text COMMENT '错误信息',
  `BUILD_MSG` VARCHAR(255) DEFAULT NULL COMMENT '构建信息',
  `BUILD_NUM_ALIAS` VARCHAR(256) COMMENT '自定义构建号',
  `CONCURRENCY_GROUP` varchar(255) DEFAULT NULL COMMENT '并发时,设定的group',
  `UPDATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`BUILD_ID`),
  KEY `STATUS_KEY` (`PROJECT_ID`,`PIPELINE_ID`,`STATUS`),
  KEY `INX_TPBH_PROJECT_PIPELINE_NUM` (`PROJECT_ID`, `PIPELINE_ID`, `BUILD_NUM`),
  KEY `INX_TPBH_PROJECT_PIPELINE_START_TIME` (`PROJECT_ID`, `PIPELINE_ID`, `START_TIME`),
  KEY `inx_tpbh_status` (`STATUS`),
  KEY `inx_tpbh_start_time` (`START_TIME`),
  KEY `inx_tpbh_end_time` (`END_TIME`),
  KEY `IDX_PROJECT_STATUS_GROUP` (`PROJECT_ID`,`STATUS`,`CONCURRENCY_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线构建历史表';
-- ----------------------------
-- Table structure for T_PIPELINE_BUILD_STAGE
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_STAGE` (
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '流水线ID',
  `BUILD_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '构建ID',
  `STAGE_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '当前stageId',
  `SEQ` int(11) NOT NULL COMMENT '',
  `STATUS` int(11) DEFAULT NULL COMMENT '状态',
  `START_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
  `END_TIME` timestamp NULL DEFAULT NULL COMMENT '结束时间',
  `COST` int(11) DEFAULT '0' COMMENT '花费',
  `EXECUTE_COUNT` int(11) DEFAULT '1' COMMENT '执行次数',
  `CONDITIONS` mediumtext COLLATE utf8mb4_bin DEFAULT NULL COMMENT '状况',
  `CHECK_IN` mediumtext COLLATE utf8mb4_bin DEFAULT NULL COMMENT '准入检查配置',
  `CHECK_OUT` mediumtext COLLATE utf8mb4_bin DEFAULT NULL COMMENT '准出检查配置',
  PRIMARY KEY (`BUILD_ID`,`STAGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='流水线构建阶段表';

-- ----------------------------
-- Table structure for T_PIPELINE_BUILD_SUMMARY
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_SUMMARY` (
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `BUILD_NUM` int(11) DEFAULT '0' COMMENT '构建次数',
  `BUILD_NO` int(11) DEFAULT '0' COMMENT '构建号',
  `FINISH_COUNT` int(11) DEFAULT '0' COMMENT '完成次数',
  `RUNNING_COUNT` int(11) DEFAULT '0' COMMENT '运行次数',
  `QUEUE_COUNT` int(11) DEFAULT '0' COMMENT '排队次数',
  `LATEST_BUILD_ID` varchar(34) DEFAULT NULL COMMENT '最近构建ID',
  `LATEST_TASK_ID` varchar(34) DEFAULT NULL COMMENT '最近任务ID',
  `LATEST_START_USER` varchar(64) DEFAULT NULL COMMENT '最近启动者',
  `LATEST_START_TIME` timestamp NULL DEFAULT NULL COMMENT '最近启动时间',
  `LATEST_END_TIME` timestamp NULL DEFAULT NULL COMMENT '最近结束时间',
  `LATEST_TASK_COUNT` int(11) DEFAULT NULL COMMENT '最近任务计数',
  `LATEST_TASK_NAME` varchar(128) DEFAULT NULL COMMENT '最近任务名称',
  `LATEST_STATUS` int(11) DEFAULT NULL COMMENT '最近状态',
  `BUILD_NUM_ALIAS` VARCHAR(256) COMMENT '自定义构建号',
  PRIMARY KEY (`PIPELINE_ID`),
  KEY `PRJOECT_ID` (`PROJECT_ID`,`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线构建摘要表';

-- ----------------------------
-- Table structure for T_PIPELINE_BUILD_TASK
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_TASK` (
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
  `STAGE_ID` varchar(34) NOT NULL COMMENT '当前stageId',
  `CONTAINER_ID` varchar(34) NOT NULL COMMENT '构建容器ID',
  `TASK_NAME` varchar(128) DEFAULT NULL COMMENT '任务名称',
  `TASK_ID` varchar(34) NOT NULL COMMENT '任务ID',
  `TASK_PARAMS` mediumtext COMMENT '任务参数集合',
  `TASK_TYPE` varchar(64) NOT NULL COMMENT '任务类型',
  `TASK_ATOM` varchar(128) DEFAULT NULL COMMENT '任务atom代码',
  `ATOM_CODE` varchar(128) DEFAULT NULL COMMENT '插件的唯一标识',
  `START_TIME` timestamp NULL DEFAULT NULL COMMENT '开始时间',
  `END_TIME` timestamp NULL DEFAULT NULL COMMENT '结束时间',
  `STARTER` varchar(64) NOT NULL COMMENT '执行人',
  `APPROVER` varchar(64) DEFAULT NULL COMMENT '批准人',
  `STATUS` int(11) DEFAULT NULL COMMENT '状态',
  `EXECUTE_COUNT` int(11) DEFAULT '0' COMMENT '执行次数',
  `TASK_SEQ` int(11) DEFAULT '1' COMMENT '任务序列',
  `SUB_PROJECT_ID` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '子项目id',
  `SUB_BUILD_ID` varchar(34) DEFAULT NULL COMMENT '子构建id',
  `CONTAINER_TYPE` varchar(45) DEFAULT NULL COMMENT '容器类型',
  `ADDITIONAL_OPTIONS` mediumtext COMMENT '其他选项',
  `TOTAL_TIME`        bigint(20)  DEFAULT NULL COMMENT '总共时间',
  `ERROR_TYPE`        int(11)     DEFAULT NULL COMMENT '错误类型',
  `ERROR_CODE`        int(11)     DEFAULT NULL COMMENT '错误码',
  `ERROR_MSG`         text COMMENT '错误描述',
  `PLATFORM_CODE` varchar(64) DEFAULT NULL COMMENT '对接平台代码',
  `PLATFORM_ERROR_CODE` int(11) DEFAULT NULL COMMENT '对接平台错误码',
  `CONTAINER_HASH_ID` varchar(64) DEFAULT NULL COMMENT '构建Job唯一标识',
  `STEP_ID` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '标识上下文的自定义ID',
  PRIMARY KEY (`BUILD_ID`,`TASK_ID`),
  KEY `STAT_PROJECT_RUN` (`PROJECT_ID`,`STATUS`),
  KEY `PROJECT_PIPELINE` (`PROJECT_ID`,`PIPELINE_ID`),
  KEY `INX_TPBT_PROJECT_BUILD_CONTAINER_SEQ` (`PROJECT_ID`, `BUILD_ID`, `CONTAINER_ID`, `TASK_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线构建任务表';

-- ----------------------------
-- Table structure for T_PIPELINE_BUILD_VAR
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_VAR` (
  `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
  `KEY` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '键',
  `VALUE` varchar(4000) DEFAULT NULL COMMENT '值',
  `PROJECT_ID` varchar(64) DEFAULT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(64) DEFAULT NULL COMMENT '流水线ID',
  `VAR_TYPE` VARCHAR(64) COMMENT '变量类型',
  `READ_ONLY` bit(1) DEFAULT NULL COMMENT '是否只读',
  PRIMARY KEY (`BUILD_ID`,`KEY`),
  KEY `IDX_SEARCH_BUILD_ID` (`PROJECT_ID`,`PIPELINE_ID`, `KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线变量表';

-- ----------------------------
-- Table structure for T_PIPELINE_CONTAINER_MONITOR
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_CONTAINER_MONITOR` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `OS_TYPE` varchar(32) NOT NULL COMMENT '系统类型',
  `BUILD_TYPE` varchar(32) NOT NULL COMMENT '构建类型',
  `MAX_STARTUP_TIME` bigint(20) NOT NULL COMMENT '最长启动时间',
  `MAX_EXECUTE_TIME` bigint(20) NOT NULL COMMENT '最长执行时间',
  `USERS` varchar(1024) NOT NULL COMMENT '用户列表',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `OS_TYPE` (`OS_TYPE`,`BUILD_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

-- ----------------------------
-- Table structure for T_PIPELINE_FAILURE_NOTIFY_USER
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_FAILURE_NOTIFY_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `USER_ID` varchar(32) DEFAULT '' COMMENT '用户ID',
  `NOTIFY_TYPES` varchar(32) DEFAULT '' COMMENT '通知类型',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

-- ----------------------------
-- Table structure for T_PIPELINE_FAVOR
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_FAVOR` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(64) NOT NULL COMMENT '流水线ID',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `CREATE_USER` varchar(64) NOT NULL COMMENT '创建者',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_INX_TPF_PROJECT_PIPELINE_USER` (`PROJECT_ID`, `PIPELINE_ID`,`CREATE_USER`),
  KEY `PROJECT` (`PROJECT_ID`,`CREATE_USER`),
  KEY `USER` (`CREATE_USER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线收藏表';

-- ----------------------------
-- Table structure for T_PIPELINE_GROUP
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_GROUP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PROJECT_ID` varchar(32) NOT NULL COMMENT '项目ID',
  `NAME` varchar(64) NOT NULL COMMENT '名称',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新时间',
  `CREATE_USER` varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
  `UPDATE_USER` varchar(64) NOT NULL DEFAULT '' COMMENT '修改人',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROJECT_ID` (`PROJECT_ID`,`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线分组表';

-- ----------------------------
-- Table structure for T_PIPELINE_INFO
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_INFO` (
  `PIPELINE_ID` varchar(34) NOT NULL DEFAULT '' COMMENT '流水线ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `PIPELINE_NAME` varchar(255) NOT NULL COMMENT '流水线名称',
  `PIPELINE_DESC` varchar(255) DEFAULT NULL COMMENT '流水线描述',
  `VERSION` int(11) DEFAULT '1' COMMENT '版本号',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATOR` varchar(64) NOT NULL COMMENT '创建者',
  `UPDATE_TIME` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `LAST_MODIFY_USER` varchar(64) NOT NULL COMMENT '最近修改者',
  `CHANNEL` varchar(32) DEFAULT NULL COMMENT '项目渠道',
  `MANUAL_STARTUP` int(11) DEFAULT '1' COMMENT '是否手工启动',
  `ELEMENT_SKIP` int(11) DEFAULT '0' COMMENT '是否跳过插件',
  `TASK_COUNT` int(11) DEFAULT '0' COMMENT '流水线任务数量',
  `DELETE` bit(1) DEFAULT b'0' COMMENT '是否删除',
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PIPELINE_NAME_PINYIN` varchar(1300) DEFAULT NULL COMMENT '流水线名称拼音',
  `LATEST_START_TIME` datetime(3) DEFAULT NULL COMMENT '最近启动时间',
  PRIMARY KEY (`PIPELINE_ID`),
  UNIQUE KEY `T_PIPELINE_INFO_NAME_uindex` (`PROJECT_ID`,`PIPELINE_NAME`),
  KEY `PROJECT_ID` (`PROJECT_ID`,`PIPELINE_ID`),
  KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线信息表';

-- ----------------------------
-- Table structure for T_PIPELINE_JOB_MUTEX_GROUP
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_JOB_MUTEX_GROUP` (
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `JOB_MUTEX_GROUP_NAME` varchar(127) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Job互斥组名字',
  PRIMARY KEY (`PROJECT_ID`,`JOB_MUTEX_GROUP_NAME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

-- ----------------------------
-- Table structure for T_PIPELINE_LABEL
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_LABEL` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
  `GROUP_ID` bigint(20) NOT NULL COMMENT '用户组ID',
  `NAME` varchar(64) NOT NULL COMMENT '名称',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新时间',
  `CREATE_USER` varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
  `UPDATE_USER` varchar(64) NOT NULL DEFAULT '' COMMENT '修改人',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_INX_TPL_PROJECT_GROUP_NAME` (`PROJECT_ID`, `GROUP_ID`,`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线标签表';

-- ----------------------------
-- Table structure for T_PIPELINE_LABEL_PIPELINE
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_LABEL_PIPELINE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `LABEL_ID` bigint(20) NOT NULL COMMENT '标签ID',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `CREATE_USER` varchar(64) NOT NULL COMMENT '创建者',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_INX_TPLP_PROJECT_PIPELINE_LABEL` (`PROJECT_ID`, `PIPELINE_ID`,`LABEL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线-标签映射表';

-- ----------------------------
-- Table structure for T_PIPELINE_MODEL_TASK
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_MODEL_TASK` (
  `PIPELINE_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '流水线ID',
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '项目ID',
  `STAGE_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '当前stageId',
  `CONTAINER_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '构建容器ID',
  `TASK_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '任务ID',
  `TASK_NAME` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '任务名称',
  `CLASS_TYPE` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '插件大类',
  `TASK_ATOM` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '任务atom代码',
  `TASK_SEQ` int(11) DEFAULT '1' COMMENT '任务序列',
  `TASK_PARAMS` mediumtext COLLATE utf8mb4_bin COMMENT '任务参数集合',
  `OS` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作系统',
  `ADDITIONAL_OPTIONS` mediumtext CHARACTER SET utf8mb4 COMMENT '其他选项',
  `ATOM_CODE` varchar(32) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '插件的唯一标识',
  `ATOM_VERSION` varchar(20) COMMENT '插件版本号',
  `CREATE_TIME` datetime(3) COMMENT '创建时间',
  `UPDATE_TIME` datetime(3) COMMENT '更新时间',
  PRIMARY KEY (`PIPELINE_ID`,`PROJECT_ID`,`STAGE_ID`,`CONTAINER_ID`,`TASK_ID`),
  KEY `PROJECT_PIPELINE` (`PROJECT_ID`,`PIPELINE_ID`),
  KEY `INX_TPMT_PROJECT_ATOM` (`PROJECT_ID`,`ATOM_CODE`),
  KEY `INX_TPMT_ATOM_UPDATE_TIME` (`ATOM_CODE`,`UPDATE_TIME`),
  KEY `INX_TPMT_UPDATE_TIME` (`UPDATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='流水线模型task任务表';

-- ----------------------------
-- Table structure for T_PIPELINE_MUTEX_GROUP
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_MUTEX_GROUP` (
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `GROUP_NAME` varchar(127) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '用户组名称',
  PRIMARY KEY (`PROJECT_ID`,`GROUP_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线互斥表';

-- ----------------------------
-- Table structure for T_PIPELINE_REMOTE_AUTH
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_REMOTE_AUTH` (
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `PIPELINE_AUTH` varchar(32) NOT NULL COMMENT '流水线权限',
  `PROJECT_ID` varchar(32) NOT NULL COMMENT '项目ID',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `CREATE_USER` varchar(64) NOT NULL COMMENT '创建者',
  PRIMARY KEY (`PIPELINE_ID`),
  UNIQUE KEY `PIPELINE_AUTH` (`PIPELINE_AUTH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线远程触发auth表';

-- ----------------------------
-- Table structure for T_PIPELINE_RESOURCE
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_RESOURCE` (
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '版本号',
  `MODEL` mediumtext COMMENT '流水线模型',
  `CREATOR` varchar(64) DEFAULT NULL COMMENT '创建者',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`PIPELINE_ID`,`VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线资源表';

-- ----------------------------
-- Table structure for T_PIPELINE_SETTING
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_SETTING` (
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `DESC` varchar(1024) DEFAULT NULL COMMENT '描述',
  `RUN_TYPE` int(11) DEFAULT NULL COMMENT '',
  `NAME` varchar(255) DEFAULT NULL COMMENT '名称',
  `SUCCESS_RECEIVER` mediumtext COMMENT '成功接受者',
  `FAIL_RECEIVER` mediumtext COMMENT '失败接受者',
  `SUCCESS_GROUP` mediumtext COMMENT '成功组',
  `FAIL_GROUP` mediumtext COMMENT '失败组',
  `SUCCESS_TYPE` varchar(32) DEFAULT NULL COMMENT '成功的通知方式',
  `FAIL_TYPE` varchar(32) DEFAULT NULL COMMENT '失败的通知方式',
  `PROJECT_ID` varchar(64) DEFAULT NULL COMMENT '项目ID',
  `SUCCESS_WECHAT_GROUP_FLAG` bit(1) NOT NULL DEFAULT b'0' COMMENT '成功的企业微信群通知开关',
  `SUCCESS_WECHAT_GROUP` varchar(1024) NOT NULL DEFAULT '' COMMENT '成功的企业微信群通知群ID',
  `FAIL_WECHAT_GROUP_FLAG` bit(1) NOT NULL DEFAULT b'0' COMMENT '失败的企业微信群通知开关',
  `FAIL_WECHAT_GROUP` varchar(1024) NOT NULL DEFAULT '' COMMENT '失败的企业微信群通知群ID',
  `RUN_LOCK_TYPE` int(11) DEFAULT '1' COMMENT 'Lock 类型',
  `SUCCESS_DETAIL_FLAG` bit(1) DEFAULT b'0' COMMENT '成功的通知的流水线详情连接开关',
  `FAIL_DETAIL_FLAG` bit(1) DEFAULT b'0' COMMENT '失败的通知的流水线详情连接开关',
  `SUCCESS_CONTENT` longtext COMMENT '成功的自定义通知内容',
  `FAIL_CONTENT` longtext COMMENT '失败的自定义通知内容',
  `WAIT_QUEUE_TIME_SECOND` int(11) DEFAULT '7200' COMMENT '最大排队时长',
  `MAX_QUEUE_SIZE` int(11) DEFAULT '10' COMMENT '最大排队数量',
  `IS_TEMPLATE` bit(1) DEFAULT b'0' COMMENT '是否模板',
  `SUCCESS_WECHAT_GROUP_MARKDOWN_FLAG` bit(1) NOT NULL DEFAULT b'0' COMMENT '成功的企业微信群通知转为Markdown格式开关',
  `FAIL_WECHAT_GROUP_MARKDOWN_FLAG` bit(1) NOT NULL DEFAULT b'0' COMMENT '失败的企业微信群通知转为Markdown格式开关',
  `MAX_PIPELINE_RES_NUM` int(11) DEFAULT '500' COMMENT '保存流水线编排的最大个数',
  `MAX_CON_RUNNING_QUEUE_SIZE` int(11) DEFAULT '50' COMMENT '并发构建数量限制',
  `BUILD_NUM_RULE` VARCHAR(512) COMMENT '构建号生成规则',
  `CONCURRENCY_GROUP` varchar(255) DEFAULT NULL COMMENT '并发时,设定的group',
  `CONCURRENCY_CANCEL_IN_PROGRESS` BIT(1) DEFAULT b'0' COMMENT '并发时,是否相同group取消正在执行的流水线',
  `CLEAN_VARIABLES_WHEN_RETRY` BIT(1) DEFAULT b'0' COMMENT '重试时清理变量表',
  `PIPELINE_AS_CODE_SETTINGS` VARCHAR(512) COMMENT 'YAML流水线相关配置',
  PRIMARY KEY (`PIPELINE_ID`),
  UNIQUE KEY `PROJECT_ID` (`PROJECT_ID`,`NAME`,`IS_TEMPLATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线基础配置表';

-- ----------------------------
-- Table structure for T_PIPELINE_TEMPLATE
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_TEMPLATE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `TYPE` varchar(32) NOT NULL DEFAULT 'FREEDOM' COMMENT '类型',
  `CATEGORY` varchar(128) DEFAULT NULL COMMENT '应用范畴',
  `TEMPLATE_NAME` varchar(64) NOT NULL COMMENT '模板名称',
  `ICON` varchar(32) NOT NULL DEFAULT '' COMMENT '模板图标',
  `LOGO_URL` varchar(512) DEFAULT NULL COMMENT 'LOGO URL地址',
  `PROJECT_CODE` varchar(32) DEFAULT NULL COMMENT '用户组所属项目',
  `SRC_TEMPLATE_ID` varchar(32) DEFAULT NULL COMMENT '源模版ID',
  `AUTHOR` varchar(64) NOT NULL DEFAULT '' COMMENT '作者',
  `ATOMNUM` int(11) NOT NULL COMMENT '插件数量',
  `PUBLIC_FLAG` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否为公共镜像',
  `TEMPLATE` mediumtext COMMENT '模板',
  `CREATOR` varchar(32) NOT NULL COMMENT '创建者',
  `CREATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  KEY `SRC_TEMPLATE_ID` (`SRC_TEMPLATE_ID`),
  KEY `PROJECT_CODE` (`PROJECT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线模板表';

-- ----------------------------
-- Table structure for T_PIPELINE_TIMER
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_TIMER` (
  `PROJECT_ID` varchar(32) NOT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `CRONTAB` varchar(2048) NOT NULL COMMENT '任务ID',
  `CREATOR` varchar(64) NOT NULL COMMENT '创建者',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CHANNEL` varchar(32) NOT NULL DEFAULT 'BS' COMMENT '项目渠道',
  PRIMARY KEY (`PROJECT_ID`,`PIPELINE_ID`),
  UNIQUE KEY `IDX_PIPELINE_ID` (`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_TRIGGER_REVIEW` (
  `BUILD_ID` varchar(34) NOT NULL DEFAULT '' COMMENT '构建ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(34) NOT NULL DEFAULT '' COMMENT '流水线ID',
  `TRIGGER_REVIEWER` text NOT NULL COMMENT '触发审核人列表',
  `TRIGGER_OPERATOR` varchar(64) DEFAULT NULL COMMENT '触发审核操作人',
  `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '审核时间',
  PRIMARY KEY (`BUILD_ID`),
  KEY `PROJECT_BUILD` (`PROJECT_ID`,`PIPELINE_ID`,`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线触发审核信息';

-- ----------------------------
-- Table structure for T_PIPELINE_USER
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新时间',
  `CREATE_USER` varchar(64) NOT NULL COMMENT '创建者',
  `UPDATE_USER` varchar(64) NOT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PIPELINE_ID` (`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

-- ----------------------------
-- Table structure for T_PIPELINE_VIEW
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_VIEW` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PROJECT_ID` varchar(32) NOT NULL COMMENT '项目ID',
  `NAME` varchar(64) NOT NULL COMMENT '名称',
  `FILTER_BY_PIPEINE_NAME` varchar(128) DEFAULT '' COMMENT '流水线名称过滤器,已废弃,统一到filters管理',
  `FILTER_BY_CREATOR` varchar(64) DEFAULT '' COMMENT '创建者过滤器,已废弃,统一到filters管理',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新时间',
  `CREATE_USER` varchar(64) NOT NULL COMMENT '创建者',
  `IS_PROJECT` bit(1) DEFAULT b'0' COMMENT '是否项目',
  `LOGIC` varchar(32) DEFAULT 'AND' COMMENT '逻辑符',
  `FILTERS` mediumtext COMMENT '过滤器',
  `VIEW_TYPE` int NOT NULL DEFAULT '1' COMMENT '1:动态流水线组 , 2:静态流水线组',
  PRIMARY KEY (`ID`),
  KEY `IDX_PROJECT_ID` (`PROJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

-- ----------------------------
-- Table structure for T_PIPELINE_VIEW_GROUP
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_VIEW_GROUP` (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `VIEW_ID` bigint NOT NULL COMMENT '流水线组ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `CREATOR` varchar(64) NOT NULL COMMENT '创建者',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_PROJECT_VIEW_PIPELINE` (`PROJECT_ID` , `VIEW_ID` , `PIPELINE_ID`),
  KEY `IDX_PIPELINE` (`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线组关系表';

-- ----------------------------
-- Table structure for T_PIPELINE_VIEW_TOP
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_VIEW_TOP` (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `VIEW_ID` bigint NOT NULL COMMENT '流水线组ID',
  `CREATOR` varchar(64) NOT NULL COMMENT '创建者',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_PROJECT_CREATOR_VIEW` (`PROJECT_ID`, `CREATOR` , `VIEW_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线组置顶表';

-- ----------------------------
-- Table structure for T_PIPELINE_VIEW_LABEL
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_VIEW_LABEL` (
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
  `VIEW_ID` bigint(20) NOT NULL COMMENT '视图ID',
  `LABEL_ID` bigint(20) NOT NULL COMMENT '标签ID',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`VIEW_ID`,`LABEL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

-- ----------------------------
-- Table structure for T_PIPELINE_VIEW_PROJECT
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_VIEW_PROJECT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `VIEW_ID` bigint(20) NOT NULL COMMENT '视图ID',
  `PROJECT_ID` varchar(32) NOT NULL COMMENT '项目ID',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新时间',
  `CREATE_USER` varchar(64) NOT NULL COMMENT '创建者',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROJECT_ID` (`PROJECT_ID`,`CREATE_USER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

-- ----------------------------
-- Table structure for T_PIPELINE_VIEW_USER_LAST_VIEW
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_VIEW_USER_LAST_VIEW` (
  `USER_ID` varchar(32) NOT NULL COMMENT '用户ID',
  `PROJECT_ID` varchar(32) NOT NULL COMMENT '项目ID',
  `VIEW_ID` varchar(64) NOT NULL COMMENT '视图ID',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`USER_ID`,`PROJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

-- ----------------------------
-- Table structure for T_PIPELINE_VIEW_USER_SETTINGS
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_VIEW_USER_SETTINGS` (
  `USER_ID` varchar(255) NOT NULL COMMENT '用户ID',
  `PROJECT_ID` varchar(32) NOT NULL COMMENT '项目ID',
  `SETTINGS` mediumtext NOT NULL COMMENT '属性配置表',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`USER_ID`,`PROJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

-- ----------------------------
-- Table structure for T_PIPELINE_WEBHOOK
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_WEBHOOK` (
  `REPOSITORY_TYPE` varchar(64) NOT NULL COMMENT '新版的git插件的类型',
  `PROJECT_ID` varchar(32) NOT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `REPO_HASH_ID` varchar(45) DEFAULT NULL COMMENT '存储库 HASH ID',
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `REPO_NAME` varchar(128) DEFAULT NULL COMMENT '代码库别名',
  `REPO_TYPE` varchar(32) DEFAULT NULL COMMENT '代码库类型',
  `PROJECT_NAME` VARCHAR(128) DEFAULT NULL COMMENT '项目名称',
  `TASK_ID` VARCHAR(34) DEFAULT NULL COMMENT '任务id',
  `DELETE` BIT(1) DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_INX_TPW_PROJECT_PIPELINE_TASK` (`PROJECT_ID`, `PIPELINE_ID`,`TASK_ID`),
  KEY `IDX_PROJECT_NAME_REPOSITORY_TYPE` (`PROJECT_NAME`, `REPOSITORY_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

-- ----------------------------
-- Table structure for T_REPORT
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_REPORT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PROJECT_ID` varchar(32) NOT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
  `ELEMENT_ID` varchar(34) NOT NULL COMMENT '原子ID',
  `TYPE` varchar(32) NOT NULL DEFAULT 'INTERNAL' COMMENT '类型',
  `INDEX_FILE` mediumtext NOT NULL COMMENT '入口文件',
  `NAME` text NOT NULL COMMENT '名称',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `TASK_NAME` varchar(128) NOT NULL DEFAULT '' COMMENT '任务名称',
  `ATOM_CODE` varchar(128) NOT NULL DEFAULT '' COMMENT '插件的唯一标识',
  PRIMARY KEY (`ID`),
  KEY `PROJECT_PIPELINE_BUILD_IDX` (`PROJECT_ID`,`PIPELINE_ID`,`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线产物表';

-- ----------------------------
-- Table structure for T_TEMPLATE
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_TEMPLATE` (
  `VERSION` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `ID` varchar(32) NOT NULL COMMENT '主键ID',
  `TEMPLATE_NAME` varchar(64) NOT NULL COMMENT '模板名称',
  `PROJECT_ID` varchar(34) NOT NULL COMMENT '项目ID',
  `VERSION_NAME` varchar(64) NOT NULL COMMENT '版本名称',
  `CREATOR` varchar(64) NOT NULL COMMENT '创建者',
  `CREATED_TIME` datetime(3) DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime(3) DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `TEMPLATE` mediumtext COMMENT '模板',
  `TYPE` varchar(32) NOT NULL DEFAULT 'CUSTOMIZE' COMMENT '类型',
  `CATEGORY` varchar(128) DEFAULT NULL COMMENT '应用范畴',
  `LOGO_URL` varchar(512) DEFAULT NULL COMMENT 'LOGO URL地址',
  `SRC_TEMPLATE_ID` varchar(32) DEFAULT NULL COMMENT '源模版ID',
  `STORE_FLAG` bit(1) DEFAULT b'0' COMMENT '是否已关联到store',
  `WEIGHT` int(11) DEFAULT '0' COMMENT '权值',
  PRIMARY KEY (`VERSION`),
  KEY `PROJECT_ID` (`PROJECT_ID`),
  KEY `SRC_TEMPLATE_ID` (`SRC_TEMPLATE_ID`),
  KEY `TYPE` (`TYPE`),
  KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线模板信息表';

-- ----------------------------
-- Table structure for T_TEMPLATE_PIPELINE
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_TEMPLATE_PIPELINE` (
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `INSTANCE_TYPE` VARCHAR(32) NOT NULL DEFAULT 'CONSTRAINT' COMMENT '实例化类型：FREEDOM 自由模式  CONSTRAINT 约束模式',
  `ROOT_TEMPLATE_ID` VARCHAR(32) NULL COMMENT '源模板ID',
  `VERSION` bigint(20) NOT NULL COMMENT '版本号',
  `VERSION_NAME` varchar(64) NOT NULL COMMENT '版本名称',
  `TEMPLATE_ID` varchar(32) NOT NULL COMMENT '模板ID',
  `CREATOR` varchar(64) NOT NULL COMMENT '创建者',
  `UPDATOR` varchar(64) NOT NULL COMMENT '更新人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_TIME` datetime NOT NULL COMMENT '更新时间',
  `BUILD_NO` text COMMENT '构建号',
  `PARAM` mediumtext COMMENT '参数',
  `DELETED` bit(1) DEFAULT b'0' COMMENT '流水线已被软删除',
  PRIMARY KEY (`PIPELINE_ID`),
  KEY `TEMPLATE_ID` (`TEMPLATE_ID`),
  KEY `ROOT_TEMPLATE_ID` (`ROOT_TEMPLATE_ID`),
  KEY `INX_TTP_PROJECT_TEMPLATE_VERSION` (`PROJECT_ID`,`TEMPLATE_ID`,`VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线模板-实例映射表';

-- ----------------------------
-- Table structure for T_PROJECT_PIPELINE_CALLBACK
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PROJECT_PIPELINE_CALLBACK` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `EVENTS` varchar(255) DEFAULT NULL COMMENT '事件',
  `CALLBACK_URL` varchar(255) NOT NULL COMMENT '回调url地址',
  `CREATOR` varchar(64) NOT NULL COMMENT '创建者',
  `UPDATOR` varchar(64) NOT NULL COMMENT '更新人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_TIME` datetime NOT NULL COMMENT '更新时间',
  `SECRET_TOKEN` text DEFAULT NULL COMMENT 'Send to your with http header: X-DEVOPS-WEBHOOK-TOKEN',
  `ENABLE` bit(1) NOT NULL DEFAULT b'1' COMMENT '启用',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_PROJECT_CALLBACK_EVENTS` (`PROJECT_ID`, `CALLBACK_URL`, `EVENTS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

-- ----------------------------
-- Table structure for T_PIPELINE_STAGE_TAG
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_STAGE_TAG` (
  `ID` varchar(32) NOT NULL DEFAULT '' COMMENT '主键',
  `STAGE_TAG_NAME` varchar(45) NOT NULL DEFAULT '' COMMENT '阶段标签名称',
  `WEIGHT` int(11) NOT NULL DEFAULT '0' COMMENT '阶段标签权值',
  `CREATOR` varchar(50) NOT NULL DEFAULT 'system' COMMENT '创建人',
  `MODIFIER` varchar(50) NOT NULL DEFAULT 'system' COMMENT '最近修改人',
  `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='';

-- ----------------------------
-- Table structure for T_PIPELINE_BUILD_HIS_DATA_CLEAR
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_HIS_DATA_CLEAR` (
  `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `DEL_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '',
  PRIMARY KEY (`BUILD_ID`),
  KEY `INX_PROJECT_PIPELINE` (`PROJECT_ID`,`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='流水线构建数据清理统计表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_PAUSE_VALUE` (
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
  `TASK_ID` varchar(34) NOT NULL COMMENT '任务ID',
  `DEFAULT_VALUE` text COMMENT '默认变量',
  `NEW_VALUE` text COMMENT '暂停后用户提供的变量',
  `CREATE_TIME` timestamp NULL DEFAULT NULL COMMENT '添加时间',
  PRIMARY KEY (`BUILD_ID`,`TASK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='流水线暂停变量表';

CREATE TABLE IF NOT EXISTS `T_PROJECT_PIPELINE_CALLBACK_HISTORY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `EVENTS` VARCHAR(255) DEFAULT NULL COMMENT '事件',
  `CALLBACK_URL` VARCHAR(255) NOT NULL COMMENT '回调url地址',
  `STATUS` VARCHAR(20) NOT NULL COMMENT '状态',
  `ERROR_MSG` TEXT DEFAULT NULL COMMENT '错误描述',
  `REQUEST_HEADER` TEXT DEFAULT NULL COMMENT '请求头',
  `REQUEST_BODY` TEXT NOT NULL COMMENT '请求body',
  `RESPONSE_CODE` INT(10) DEFAULT NULL COMMENT '响应code',
  `RESPONSE_BODY` TEXT DEFAULT NULL COMMENT '响应body',
  `START_TIME` DATETIME NOT NULL COMMENT '开始时间',
  `END_TIME` DATETIME NOT NULL COMMENT '结束时间',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY `pk_t_project_pipeline_callback_history` (`ID`, `CREATED_TIME`),
  KEY `idx_project_id_callback_url_events`(`PROJECT_ID`, `CALLBACK_URL`, `EVENTS`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='';

CREATE TABLE IF NOT EXISTS `T_TEMPLATE_INSTANCE_BASE` (
  `ID` varchar(32) NOT NULL DEFAULT '' COMMENT '主键ID',
  `TEMPLATE_ID` varchar(32) DEFAULT '' COMMENT '模板ID',
  `TEMPLATE_VERSION` varchar(32) NOT NULL DEFAULT '' COMMENT '模板版本',
  `USE_TEMPLATE_SETTINGS_FLAG` bit(1)  NOT NULL COMMENT '是否使用模板配置',
  `PROJECT_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '项目ID',
  `TOTAL_ITEM_NUM` int(11) NOT NULL DEFAULT '0' COMMENT '总实例化数量',
  `SUCCESS_ITEM_NUM` int(11) NOT NULL DEFAULT '0' COMMENT '实例化成功数量',
  `FAIL_ITEM_NUM` int(11) NOT NULL DEFAULT '0' COMMENT '实例化失败数量',
  `STATUS` varchar(32) NOT NULL DEFAULT '' COMMENT '状态',
  `CREATOR` varchar(50) NOT NULL DEFAULT 'system' COMMENT '创建者',
  `MODIFIER` varchar(50) NOT NULL DEFAULT 'system' COMMENT '修改者',
  `UPDATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  `CREATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  KEY `INX_TTIB_PROJECT_ID` (`PROJECT_ID`),
  KEY `INX_TTIB_STATUS` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='模板实列化基本信息表';

CREATE TABLE IF NOT EXISTS `T_TEMPLATE_INSTANCE_ITEM` (
  `ID` varchar(32) NOT NULL DEFAULT '' COMMENT '主键ID',
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `PIPELINE_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin  NOT NULL COMMENT '流水线名称',
  `BUILD_NO_INFO` varchar(512) COMMENT '构建号信息',
  `STATUS` varchar(32) NOT NULL DEFAULT '' COMMENT '状态',
  `BASE_ID` varchar(32) NOT NULL DEFAULT '' COMMENT '实列化基本信息ID',
  `PARAM` mediumtext COMMENT '参数',
  `CREATOR` varchar(50) NOT NULL DEFAULT 'system' COMMENT '创建者',
  `MODIFIER` varchar(50) NOT NULL DEFAULT 'system' COMMENT '修改者',
  `UPDATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  `CREATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_INX_TTI_PIPELINE_ID` (`PIPELINE_ID`),
  KEY `INX_TTI_BASE_ID` (BASE_ID),
  KEY `INX_TTI_STATUS` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='模板实列化项信息表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_WEBHOOK_QUEUE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
  `PIPELINE_ID` VARCHAR(64) NOT NULL COMMENT '流水线ID',
  `SOURCE_PROJECT_ID` BIGINT(20) NOT NULL COMMENT '源项目ID',
  `SOURCE_REPO_NAME` VARCHAR(255) NOT NULL COMMENT '源代码库名称',
  `SOURCE_BRANCH` VARCHAR(255) NOT NULL COMMENT '源分支',
  `TARGET_PROJECT_ID` BIGINT(20) COMMENT '目标项目ID',
  `TARGET_REPO_NAME` VARCHAR(255) COMMENT '目标代码库名称',
  `TARGET_BRANCH` VARCHAR(255) COMMENT '目标分支',
  `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
  `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_INX_TPWQ_PROJECT_BUILD` (`PROJECT_ID`, `BUILD_ID`),
  KEY `IDX_PIPELINE_ID_PROJECT_ID_BRANCH`(`PIPELINE_ID`, `SOURCE_PROJECT_ID`,`SOURCE_BRANCH`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_ATOM_REPLACE_BASE` (
  `ID` varchar(32) NOT NULL DEFAULT '' COMMENT '主键ID',
  `PROJECT_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '项目ID',
  `PIPELINE_ID_INFO` text COMMENT '流水线ID信息',
  `FROM_ATOM_CODE` varchar(64) NOT NULL COMMENT '被替换插件代码',
  `TO_ATOM_CODE` varchar(64) NOT NULL COMMENT '被替换插件代码',
  `STATUS` varchar(32) NOT NULL DEFAULT 'INIT' COMMENT '状态',
  `CREATOR` varchar(50) NOT NULL DEFAULT 'system' COMMENT '创建者',
  `MODIFIER` varchar(50) NOT NULL DEFAULT 'system' COMMENT '修改者',
  `UPDATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  `CREATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  KEY `INX_TPARB_PROJECT_ID` (`PROJECT_ID`),
  KEY `INX_TPARB_FROM_ATOM_CODE` (`FROM_ATOM_CODE`),
  KEY `INX_TPARB_STATUS` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线插件替换基本信息表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_ATOM_REPLACE_ITEM` (
  `ID` varchar(32) NOT NULL DEFAULT '' COMMENT '主键ID',
  `FROM_ATOM_CODE` varchar(64) NOT NULL COMMENT '被替换插件代码',
  `FROM_ATOM_VERSION` varchar(20) NOT NULL COMMENT '被替换插件版本号',
  `TO_ATOM_CODE` varchar(64) NOT NULL COMMENT '替换插件代码',
  `TO_ATOM_VERSION` varchar(20) NOT NULL COMMENT '替换插件版本号',
  `STATUS` varchar(32) NOT NULL DEFAULT 'INIT' COMMENT '状态',
  `PARAM_REPLACE_INFO` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '插件参数替换信息',
  `BASE_ID` varchar(32) NOT NULL COMMENT '插件替换基本信息ID',
  `CREATOR` varchar(50) NOT NULL DEFAULT 'system' COMMENT '创建者',
  `MODIFIER` varchar(50) NOT NULL DEFAULT 'system' COMMENT '修改者',
  `UPDATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  `CREATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  KEY `INX_TPARI_FROM_ATOM_CODE` (`FROM_ATOM_CODE`),
  KEY `INX_TPARI_STATUS` (`STATUS`),
  KEY `INX_TPARI_BASE_ID` (`BASE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线插件替换项信息表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_ATOM_REPLACE_HISTORY` (
  `ID` varchar(32) NOT NULL DEFAULT '' COMMENT '主键ID',
  `PROJECT_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '项目ID',
  `BUS_ID` varchar(34) NOT NULL DEFAULT '' COMMENT '业务ID',
  `BUS_TYPE` varchar(32) NOT NULL DEFAULT 'PIPELINE' COMMENT '业务类型',
  `SOURCE_VERSION` int(11) NOT NULL COMMENT '源版本号',
  `TARGET_VERSION` int(11) COMMENT '目标版本号',
  `STATUS` varchar(32) NOT NULL COMMENT '状态',
  `LOG` varchar(128) COMMENT '日志',
  `BASE_ID` varchar(32) NOT NULL COMMENT '插件替换基本信息ID',
  `ITEM_ID` varchar(32) NOT NULL COMMENT '插件替换项信息ID',
  `CREATOR` varchar(50) NOT NULL DEFAULT 'system' COMMENT '创建者',
  `MODIFIER` varchar(50) NOT NULL DEFAULT 'system' COMMENT '修改者',
  `UPDATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  `CREATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  KEY `INX_TPARH_PROJECT_BUS` (`PROJECT_ID`,`BUS_TYPE`,`BUS_ID`),
  KEY `INX_TPARH_BASE_ID` (`BASE_ID`),
  KEY `INX_TPARH_ITEM_ID` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线插件替换历史信息表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_WEBHOOK_BUILD_LOG` (
   `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
   `CODE_TYPE` VARCHAR(32) NOT NULL COMMENT '代码库类型',
   `REPO_NAME` VARCHAR(128) NOT NULL COMMENT '代码库别名',
   `COMMIT_ID` VARCHAR(64) NOT NULL COMMENT '代码提交ID',
   `REQUEST_CONTENT` TEXT COMMENT '事件内容',
   `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   `RECEIVED_TIME` DATETIME NOT NULL COMMENT '接收时间',
   `FINISHED_TIME` DATETIME NOT NULL COMMENT '完成时间',
   PRIMARY KEY (`ID`,`CREATED_TIME`),
   KEY `IDX_REPO_NAME_COMMIT_ID`(`REPO_NAME`, `COMMIT_ID`)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_WEBHOOK_BUILD_LOG_DETAIL` (
   `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
   `LOG_ID` BIGINT(20) NOT NULL COMMENT '',
   `CODE_TYPE` VARCHAR(32) NOT NULL COMMENT '代码库类型',
   `REPO_NAME` VARCHAR(128) NOT NULL COMMENT '代码库别名',
   `COMMIT_ID` VARCHAR(64) NOT NULL COMMENT '代码提交ID',
   `PROJECT_ID` varchar(32) NOT NULL COMMENT '项目ID',
   `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
   `TASK_ID` VARCHAR(34) NOT NULL COMMENT '任务id',
   `TASK_NAME` VARCHAR(128) COMMENT '任务名称',
   `SUCCESS` BIT(1) DEFAULT b'0' COMMENT '是否成功',
   `TRIGGER_RESULT` TEXT COMMENT '触发结果',
   `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   PRIMARY KEY (`ID`,`CREATED_TIME`),
   KEY `IDX_PIPELINE_ID_COMMIT_ID`(`PIPELINE_ID`,`COMMIT_ID`)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_RESOURCE_VERSION` (
    `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
    `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
    `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '版本号',
    `VERSION_NAME` varchar(64) NOT NULL COMMENT '版本名称',
    `MODEL` mediumtext COMMENT '流水线模型',
	`REFER_FLAG` bit(1) DEFAULT NULL COMMENT '是否还有构建记录引用该版本标识',
	`REFER_COUNT` int(20) DEFAULT NULL COMMENT '关联构建记录总数',
    `CREATOR` varchar(64) DEFAULT NULL COMMENT '创建者',
    `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`PIPELINE_ID`,`VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线资源版本表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_SETTING_VERSION` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
    `SUCCESS_RECEIVER` mediumtext COMMENT '成功接受者',
    `FAIL_RECEIVER` mediumtext COMMENT '失败接受者',
    `SUCCESS_GROUP` mediumtext COMMENT '成功组',
    `FAIL_GROUP` mediumtext COMMENT '失败组',
    `SUCCESS_TYPE` varchar(32) DEFAULT NULL COMMENT '成功的通知方式',
    `FAIL_TYPE` varchar(32) DEFAULT NULL COMMENT '失败的通知方式',
    `PROJECT_ID` varchar(64) DEFAULT NULL COMMENT '项目ID',
    `SUCCESS_WECHAT_GROUP_FLAG` bit(1) NOT NULL DEFAULT b'0' COMMENT '成功的企业微信群通知开关',
    `SUCCESS_WECHAT_GROUP` varchar(1024) NOT NULL DEFAULT '' COMMENT '成功的企业微信群通知群ID',
    `FAIL_WECHAT_GROUP_FLAG` bit(1) NOT NULL DEFAULT b'0' COMMENT '失败的企业微信群通知开关',
    `FAIL_WECHAT_GROUP` varchar(1024) NOT NULL DEFAULT '' COMMENT '失败的企业微信群通知群ID',
    `SUCCESS_DETAIL_FLAG` bit(1) DEFAULT b'0' COMMENT '成功的通知的流水线详情连接开关',
    `FAIL_DETAIL_FLAG` bit(1) DEFAULT b'0' COMMENT '失败的通知的流水线详情连接开关',
    `SUCCESS_CONTENT` longtext COMMENT '成功的自定义通知内容',
    `FAIL_CONTENT` longtext COMMENT '失败的自定义通知内容',
    `IS_TEMPLATE` bit(1) DEFAULT b'0' COMMENT '是否模板',
    `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '版本号',
    `SUCCESS_WECHAT_GROUP_MARKDOWN_FLAG` bit(1) NOT NULL DEFAULT b'0' COMMENT '成功的企业微信群通知转为Markdown格式开关',
    `FAIL_WECHAT_GROUP_MARKDOWN_FLAG` bit(1) NOT NULL DEFAULT b'0' COMMENT '失败的企业微信群通知转为Markdown格式开关',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UNI_INX_TPSV_PROJECT_PIPELINE_VERSION` (`PROJECT_ID`, `PIPELINE_ID`, `VERSION`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线基础配置版本表';

-- ----------------------------
-- Table structure for T_AUDIT_RESOURCE
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_AUDIT_RESOURCE` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `RESOURCE_TYPE` varchar(32) NOT NULL COMMENT '资源类型',
    `RESOURCE_ID` varchar(128) NOT NULL COMMENT '资源ID',
    `RESOURCE_NAME` varchar(128) NOT NULL COMMENT '资源名称',
    `USER_ID` varchar(64) NOT NULL DEFAULT '' COMMENT '用户ID',
    `ACTION` varchar(64) NOT NULL DEFAULT '' COMMENT '操作',
    `ACTION_CONTENT` varchar(1024) NOT NULL DEFAULT '' COMMENT '操作内容',
    `CREATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `STATUS` varchar(32) DEFAULT NULL COMMENT '状态',
    `PROJECT_ID` varchar(128) NOT NULL COMMENT '项目ID',
    PRIMARY KEY (`ID`),
    KEY IDX_SEARCH (`RESOURCE_TYPE`, `PROJECT_ID`, `USER_ID`),
    KEY IDX_SEARCH_ID (`RESOURCE_TYPE`, `PROJECT_ID`, `RESOURCE_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_DATA_CLEAR` (
  `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `DEL_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '',
  PRIMARY KEY (`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线数据清理统计表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_RULE` (
  `ID` varchar(32) NOT NULL DEFAULT '' COMMENT '主键ID',
  `RULE_NAME` varchar(256) NOT NULL DEFAULT '' COMMENT '规则名称',
  `BUS_CODE` varchar(128) NOT NULL DEFAULT '' COMMENT '业务标识',
  `PROCESSOR` varchar(128) NOT NULL DEFAULT '' COMMENT '处理器',
  `CREATOR` varchar(50) NOT NULL DEFAULT 'system' COMMENT '创建者',
  `MODIFIER` varchar(50) NOT NULL DEFAULT 'system' COMMENT '修改者',
  `UPDATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  `CREATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY  `uni_inx_tpr_rule_name_bus` (`RULE_NAME`,`BUS_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线规则信息表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_TEMPLATE_ACROSS_INFO`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `TEMPLATE_ID` char(34) NOT NULL COMMENT '模板唯一UUID',
  `PROJECT_ID` varchar(64)  NOT NULL COMMENT '项目ID',
  `PIPELINE_ID` varchar(34)  NOT NULL COMMENT '流水线ID （P-32位UUID)=34位',
  `BUILD_ID` varchar(34) COMMENT '构建ID',
  `TEMPLATE_TYPE` varchar(64) NOT NULL COMMENT '模板类型',
  `TEMPLATE_INSTANCE_IDS` text NOT NULL COMMENT '模板对应的实例ID',
  `TARGET_PROJECT_ID` varchar(64) NOT NULL COMMENT '使用的项目ID',
  `CREATE_TIME` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATOR` varchar(64)  NOT NULL COMMENT '创建人',
  PRIMARY KEY (`ID`),
  KEY `PROJECT_TEMPLATE_IDX` (`PROJECT_ID`,`TEMPLATE_ID`,`PIPELINE_ID`),
  KEY `PROJECT_PIPELINE_IDX` (`PROJECT_ID`,`PIPELINE_ID`,`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线模板跨项目访问表';


-- ----------------------------
-- Table structure for T_PIPELINE_WEBHOOK_REVISION
-- ----------------------------

CREATE TABLE IF NOT EXISTS `T_PIPELINE_WEBHOOK_REVISION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PROJECT_NAME` varchar(255) DEFAULT NULL,
  `REVISION` varchar(64) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQ_PROJECT_NAME` (`PROJECT_NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Table structure for T_PIPELINE_BUILD_COMMITS
-- ----------------------------
CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_COMMITS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` varchar(32) NOT NULL,
  `PIPELINE_ID` varchar(34) NOT NULL,
  `BUILD_ID` varchar(34) NOT NULL,
  `COMMIT_ID` varchar(64) NOT NULL,
  `MESSAGE` longtext NOT NULL,
  `AUTHOR_NAME` varchar(64) NOT NULL,
  `MERGE_REQUEST_ID` varchar(256) DEFAULT NULL,
  `REPOSITORY_TYPE` varchar(20) NOT NULL,
  `COMMIT_TIME` datetime NOT NULL,
  `CREATE_TIME` datetime NOT NULL,
  `URL` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '仓库url',
  `EVENT_TYPE` varchar(32) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '触发事件类型',
  `CHANNEL` varchar(32) DEFAULT NULL,
  `ACTION` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_PROJECT_ID_BUILD_ID` (`PROJECT_ID`,`BUILD_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;


-- ----------------------------
-- Table structure for T_PIPELINE_WEBHOOK_BUILD_PARAMETER
-- ----------------------------
CREATE TABLE IF NOT EXISTS `T_PIPELINE_WEBHOOK_BUILD_PARAMETER` (
	`BUILD_ID` varchar(34) NOT NULL,
	`PROJECT_ID` varchar(64) NOT NULL,
  	`PIPELINE_ID` varchar(34) NOT NULL,
  	`BUILD_PARAMETERS` text,
  	`CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	`UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	PRIMARY KEY (`BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='webhook构建参数';

-- ----------------------------
-- Table structure for T_PIPELINE_RECENT_USE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `T_PIPELINE_RECENT_USE` (
  `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
  `USER_ID` varchar(64) NOT NULL COMMENT '用户ID',
  `PIPELINE_ID` varchar(64) NOT NULL COMMENT '流水线ID',
  `USE_TIME` datetime NOT NULL COMMENT '使用时间',
  PRIMARY KEY (`PROJECT_ID` ,`USER_ID` , `PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='最近使用的流水线';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_RECORD_CONTAINER` (
    `BUILD_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '构建ID',
    `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '项目ID',
    `PIPELINE_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL COMMENT '流水线ID',
    `RESOURCE_VERSION` int(11) NOT NULL COMMENT '编排版本',
    `STAGE_ID` varchar(64) CHARACTER SET utf8mb4 NOT NULL DEFAULT '' COMMENT '步骤ID',
    `CONTAINER_ID` varchar(64) CHARACTER SET utf8mb4 NOT NULL DEFAULT '' COMMENT '构建容器ID',
    `EXECUTE_COUNT` int(11) NOT NULL DEFAULT '1' COMMENT '执行次数',
    `STATUS` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '构建状态',
    `CONTAINER_VAR` mediumtext CHARACTER SET utf8mb4 NOT NULL COMMENT '当次执行的变量记录',
    `CONTAINER_TYPE` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '容器类型',
    `CONTAIN_POST_TASK` bit(1) DEFAULT NULL COMMENT '包含POST插件标识',
    `MATRIX_GROUP_FLAG` bit(1) DEFAULT NULL COMMENT '矩阵标识',
    `MATRIX_GROUP_ID` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '所属的矩阵组ID',
    `START_TIME` datetime(3) NULL DEFAULT NULL COMMENT '开始时间',
    `END_TIME` datetime(3) NULL DEFAULT NULL COMMENT '结束时间',
    `TIMESTAMPS` text CHARACTER SET utf8mb4 COMMENT '运行中产生的时间戳集合',
    PRIMARY KEY (`BUILD_ID`,`CONTAINER_ID`,`EXECUTE_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='流水线构建容器环境表';

CREATE TABLE IF NOT EXISTS  `T_PIPELINE_BUILD_RECORD_MODEL` (
    `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
    `PROJECT_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
    `PIPELINE_ID` varchar(34) NOT NULL DEFAULT '' COMMENT '流水线ID',
    `RESOURCE_VERSION` int(11) NOT NULL COMMENT '编排版本',
    `BUILD_NUM` int(20) NOT NULL COMMENT '构建次数',
    `EXECUTE_COUNT` int(11) NOT NULL COMMENT '执行次数',
    `START_USER` varchar(32) NOT NULL DEFAULT '' COMMENT '启动者',
    `MODEL_VAR` mediumtext NOT NULL COMMENT '当次执行的变量记录',
    `START_TYPE` varchar(32) NOT NULL DEFAULT '' COMMENT '触发方式',
    `QUEUE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '触发时间',
    `START_TIME` datetime(3) NULL DEFAULT NULL COMMENT '启动时间',
    `END_TIME` datetime(3) NULL DEFAULT NULL COMMENT '结束时间',
    `STATUS` varchar(32) DEFAULT NULL COMMENT '构建状态',
    `ERROR_INFO` text COMMENT '错误信息',
    `CANCEL_USER` varchar(32) DEFAULT NULL COMMENT '取消者',
    `TIMESTAMPS` text COMMENT '运行中产生的时间戳集合',
    PRIMARY KEY (`BUILD_ID`,`EXECUTE_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线构建详情表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_RECORD_STAGE` (
    `BUILD_ID` varchar(64) CHARACTER SET utf8mb4 NOT NULL COMMENT '构建ID',
    `PROJECT_ID` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '项目ID',
    `PIPELINE_ID` varchar(64) CHARACTER SET utf8mb4 NOT NULL DEFAULT '' COMMENT '流水线ID',
    `RESOURCE_VERSION` int(11) DEFAULT NULL COMMENT '编排版本号',
    `STAGE_ID` varchar(64) CHARACTER SET utf8mb4 NOT NULL DEFAULT '' COMMENT '步骤ID',
    `SEQ` int(11) NOT NULL COMMENT '步骤序列',
    `STAGE_VAR` text CHARACTER SET utf8mb4 NOT NULL COMMENT '当次执行的变量记录',
    `STATUS` varchar(32) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '构建状态',
    `EXECUTE_COUNT` int(11) NOT NULL DEFAULT '1' COMMENT '执行次数',
    `START_TIME` datetime(3) NULL DEFAULT NULL COMMENT '开始时间',
    `END_TIME` datetime(3) NULL DEFAULT NULL COMMENT '结束时间',
    `TIMESTAMPS` text CHARACTER SET utf8mb4 COMMENT '运行中产生的时间戳集合',
    PRIMARY KEY (`BUILD_ID`,`STAGE_ID`,`EXECUTE_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='流水线构建阶段表';

CREATE TABLE IF NOT EXISTS `T_PIPELINE_BUILD_RECORD_TASK` (
    `BUILD_ID` varchar(34) NOT NULL COMMENT '构建ID',
    `PROJECT_ID` varchar(64) NOT NULL COMMENT '项目ID',
    `PIPELINE_ID` varchar(34) NOT NULL COMMENT '流水线ID',
    `RESOURCE_VERSION` int(11) NOT NULL COMMENT '编排版本号',
    `STAGE_ID` varchar(34) NOT NULL DEFAULT '' COMMENT '步骤ID',
    `CONTAINER_ID` varchar(34) NOT NULL COMMENT '构建容器ID',
    `TASK_ID` varchar(34) NOT NULL COMMENT '任务ID',
    `TASK_SEQ` int(11) NOT NULL DEFAULT '1' COMMENT '任务序列',
    `EXECUTE_COUNT` int(11) NOT NULL DEFAULT '1' COMMENT '执行次数',
    `STATUS` varchar(32) DEFAULT NULL COMMENT '构建状态',
    `TASK_VAR` mediumtext NOT NULL COMMENT '当次执行的变量记录',
    `POST_INFO` text DEFAULT NULL COMMENT '市场插件的POST关联信息',
    `CLASS_TYPE` varchar(64) NOT NULL DEFAULT '' COMMENT '项目ID',
    `ATOM_CODE` varchar(128) NOT NULL DEFAULT '' COMMENT '插件的唯一标识',
    `ORIGIN_CLASS_TYPE` varchar(64) DEFAULT NULL COMMENT '所在矩阵组ID',
    `START_TIME` datetime(3) NULL DEFAULT NULL COMMENT '开始时间',
    `END_TIME` datetime(3) NULL DEFAULT NULL COMMENT '结束时间',
    `TIMESTAMPS` text COMMENT '运行中产生的时间戳集合',
    PRIMARY KEY (`BUILD_ID`,`TASK_ID`,`EXECUTE_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流水线构建任务表';

SET FOREIGN_KEY_CHECKS = 1;
