use devops_ci_quality;
set names utf8mb4;

-- 创建红线的构建历史表
CREATE TABLE IF NOT EXISTS `T_QUALITY_RULE_BUILD_HIS` (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `PROJECT_ID` VARCHAR(64) DEFAULT NULL,
    `PIPELINE_ID` VARCHAR(40) DEFAULT NULL,
    `RULE_POS` VARCHAR(8) DEFAULT NULL,
    `RULE_NAME` VARCHAR(123) DEFAULT NULL,
    `RULE_DESC` VARCHAR(256) DEFAULT NULL,
    `GATEWAY_ID` VARCHAR(128) DEFAULT NULL,
    `PIPELINE_RANGE` TEXT DEFAULT NULL,
    `TEMPLATE_RANGE` TEXT DEFAULT NULL,
    `INDICATOR_IDS` TEXT DEFAULT NULL,
    `INDICATOR_OPERATIONS` TEXT DEFAULT NULL,
    `INDICATOR_THRESHOLDS` TEXT DEFAULT NULL,
    `OPERATION_LIST` TEXT DEFAULT NULL,
    `CREATE_TIME` DATETIME,
    `CREATE_USER` VARCHAR(32),
    PRIMARY KEY (`ID`),
    KEY project_id_pipeline_id_idx (`PROJECT_ID`,`PIPELINE_ID`),
    KEY create_time_idx (`CREATE_TIME`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;