use devops_ci_quality;
set names utf8mb4;

-- 创建红线的构建历史表
CREATE TABLE IF NOT EXISTS `T_QUALITY_RULE_BUILD_HIS` (
   `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
   `PROJECT_ID` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,
   `PIPELINE_ID` VARCHAR(40) COLLATE utf8_bin DEFAULT NULL,
   `BUILD_ID` VARCHAR(40) COLLATE utf8_bin DEFAULT NULL,
   `RULE_POS` VARCHAR(8) COLLATE utf8_bin DEFAULT NULL,
   `RULE_NAME` VARCHAR(123) COLLATE utf8_bin DEFAULT NULL,
   `RULE_DESC` VARCHAR(256) COLLATE utf8_bin DEFAULT NULL,
   `GATEWAY_ID` VARCHAR(128) COLLATE utf8_bin DEFAULT NULL,
   `PIPELINE_RANGE` TEXT COLLATE utf8_bin DEFAULT NULL,
   `TEMPLATE_RANGE` TEXT COLLATE utf8_bin DEFAULT NULL,
   `INDICATOR_IDS` TEXT COLLATE utf8_bin DEFAULT NULL,
   `INDICATOR_OPERATIONS` TEXT COLLATE utf8_bin DEFAULT NULL,
   `INDICATOR_THRESHOLDS` TEXT COLLATE utf8_bin DEFAULT NULL,
   `OPERATION_LIST` TEXT COLLATE utf8_bin,
   `CREATE_TIME` DATETIME,
   `CREATE_USER` VARCHAR(32),
   PRIMARY KEY (`ID`),
   KEY project_id_pipeline_id_idx (`PROJECT_ID`,`PIPELINE_ID`),
   KEY create_time_idx (`CREATE_TIME`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;