
use devops_ee_environment;

ALTER TABLE `T_ENVIRONMENT_THIRDPARTY_AGENT` ADD COLUMN `PARALLEL_TASK_COUNT` int(11) DEFAULT NULL;
ALTER TABLE `T_ENVIRONMENT_THIRDPARTY_AGENT` ADD COLUMN `AGENT_INSTALL_PATH` varchar (512) DEFAULT NULL;
ALTER TABLE `T_ENVIRONMENT_THIRDPARTY_AGENT` ADD COLUMN `STARTED_USER` varchar (64) DEFAULT NULL;
ALTER TABLE `T_ENVIRONMENT_THIRDPARTY_AGENT` ADD COLUMN `AGENT_ENVS` text;

CREATE TABLE IF NOT EXISTS `T_ENVIRONMENT_THIRDPARTY_AGENT_ACTION`
(
    `ID`          bigint(20)  NOT NULL AUTO_INCREMENT,
    `AGENT_ID`    bigint(20)  NOT NULL,
    `PROJECT_ID`  varchar(64) NOT NULL,
    `ACTION`      varchar(64) NOT NULL,
    `ACTION_TIME` datetime    NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `AGENT_ID` (`AGENT_ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

use devops_ee_dispatch;

ALTER TABLE `T_DISPATCH_THIRDPARTY_AGENT_BUILD` ADD COLUMN `BUILD_NUM` int(20) DEFAULT '0';
ALTER TABLE `T_DISPATCH_THIRDPARTY_AGENT_BUILD` ADD COLUMN `PIPELINE_NAME` varchar(255) DEFAULT '';
ALTER TABLE `T_DISPATCH_THIRDPARTY_AGENT_BUILD` ADD COLUMN `TASK_NAME` varchar(255) DEFAULT '';
