object Release {
    const val Group = "com.tencent.devops"
    const val Version = "0.0.1"
}

object Versions {
    const val kotlinVersion = "1.4.10"
    const val swaggerVersion = "1.6.2"
    const val jaxrsVersion = "2.0"
    const val jacksonVersion = "2.11.4"
    const val hashidsVersion = "1.0.3"
    const val feignVersion = "10.10.1"
    const val svnkitVersion = "1.9.3"
    const val vmwareVersion = "5.1"
    const val okHttpVersion = "3.14.9"
    const val commonExecVersion = "1.3"
    const val bouncyCastleVersion = "1.70"
    const val dom4jVersion = "1.6.1"
    const val slf4jVersion = "1.7.30"
    const val mockitoVersion = "1.10.19"
    const val httpclientVersion = "4.5.13"
    const val compressVersion = "1.21"
    const val jjwtVersion = "0.9.0"
    const val jsonLibVersion = "2.4"
    const val cronutilsVersion = "9.1.6"
    const val reflectionsVersion = "0.9.11"
    const val jsonSchemaVersion = "2.2.6"
    const val logbackVersion = "1.1.11"
    const val jasyptVersion = "2.0.0"
    const val jolokiaVersion = "1.6.2"
    const val awsS3Version = "1.11.461"
    const val poiVersion = "4.1.1"
    const val lombokVersion = "1.18.16"
    const val tomcatEmbedCoreVersion = "9.0.39"
    const val commonCollection = "3.2.2"
    const val commonPool2Version = "2.9.0"
    const val lettuceVersion = "4.5.0.Final"
    const val springRedisVersion = "2.4.5.RELEASE"
    const val springWebSocketVersion = "2.3.4.RELEASE"
    const val commonsIOVersion = "2.8.0"
    const val commonsHttpclientVersion = "3.1"
    const val ktlintVersion = "0.29.0"
    const val devopsVersion = "1.7.37-RELEASE"
    const val easyexcel = "2.2.7"
    const val redisson = "3.15.4"
    const val lucene = "8.11.0"
    const val log4j = "2.17.1"
    const val beanUtils = "1.9.4"
    const val jersey = "2.34"
    const val guava = "30.0-jre"
    const val fastjson = "1.2.83"
}
