export const UPDATE_SELECTED_FILE = 'UPDATE_SELECTED_FILE'
export const UPDATE_IS_EXPIRED = 'UPDATE_IS_EXPIRED'
export const UPDATE_USER_GROUP = 'UPDATE_USER_GROUP'
export const SET_CURRELEASE_DETAIL = 'SET_CURRELEASE_DETAIL'
